Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2020-08, with the labels that each got.

#442 fix(module: table): clear cached items that are not on current page
  components/checkbox/CheckboxGroup.razor
  components/checkbox/CheckboxGroup.razor.cs
  components/table/ColumnBase.cs
  components/table/ColumnContext.cs
  components/table/IColumn.cs
  components/table/ISelectionColumn.cs
  components/table/ITable.cs
  components/table/RowNode.cs
  components/table/Selection.razor.cs
  components/table/Table.razor
  components/table/Table.razor.RowData.cs
  components/table/Table.razor.Selection.cs
  components/table/Table.razor.cs
  components/table/TableModels/RowData.cs
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
Labels: PR: unreviewed

#443 chore: add npm release action
  .github/workflows/release.yml
Labels: PR: unreviewed

#444 chore: prepare for 0.3.0 version
  .github/workflows/gh-pages.yml
Labels: PR: unreviewed

#433 chore: sync ant-design v4.5.1
  components/avatar/style/group.less
  components/avatar/style/index.less
  components/avatar/style/rtl.less
  components/badge/style/index.less
  components/badge/style/ribbon.less
  components/badge/style/rtl.less
  components/date-picker/style/index.less
  components/descriptions/style/index.less
  components/divider/style/index.less
  components/form/style/rtl.less
  components/form/style/status.less
  components/form/style/vertical.less
  components/input/style/mixin.less
  components/menu/style/dark.less
  components/menu/style/index.less
  components/message/style/index.less
  components/pagination/style/index.less
  components/steps/style/index.less
  components/steps/style/progress.less
  components/steps/style/small.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/tabs/style/index.less
Labels: PR: unreviewed

#448 fix(module: form): null check for submit
  components/form/Form.razor.cs
Labels: PR: unreviewed

#450 feat(module: table): add router pagging demo
  components/table/Selection.razor.cs
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
  site/AntBlazor.Docs/Demos/Table/demo/RouterPagging.razor
  site/AntBlazor.Docs/Demos/Table/demo/router-pagging.md
  site/AntBlazor.Docs/Pages/Mock.razor
Labels: PR: unreviewed

#451 chore: sync ant-design v4.5.2
  components/badge/style/index.less
  components/carousel/style/index.less
  components/list/style/index.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/style/rtl.less
  components/tabs/style/rtl.less
  components/typography/style/index.less
Labels: PR: unreviewed

#454 docs: fix styles
  components/icon/Icon.razor
  components/icon/Icon.razor.cs
  components/icon/IconFont.razor.cs
  components/icon/IconService.cs
  scripts/gh-pages/index.html
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
  site/AntBlazor.Docs/Shared/CodeBox.razor
  site/AntBlazor.Docs/style/static/colors.less
  site/AntBlazor.Docs/style/static/common.less
  site/AntBlazor.Docs/style/static/contributors.less
  site/AntBlazor.Docs/style/static/dark.less
  site/AntBlazor.Docs/style/static/demo.less
  site/AntBlazor.Docs/style/static/design-doc.less
  site/AntBlazor.Docs/style/static/docsearch.less
  site/AntBlazor.Docs/style/static/footer.less
  site/AntBlazor.Docs/style/static/header.less
  site/AntBlazor.Docs/style/static/highlight.less
  site/AntBlazor.Docs/style/static/home.less
  site/AntBlazor.Docs/style/static/icon-pic-searcher.less
  site/AntBlazor.Docs/style/static/icons.less
  site/AntBlazor.Docs/style/static/markdown.less
  site/AntBlazor.Docs/style/static/mock-browser.less
  site/AntBlazor.Docs/style/static/motion.less
  site/AntBlazor.Docs/style/static/new-version-info-modal.less
  site/AntBlazor.Docs/style/static/not-found.less
  site/AntBlazor.Docs/style/static/nprogress.less
  site/AntBlazor.Docs/style/static/page-nav.less
  site/AntBlazor.Docs/style/static/preview-img.less
  site/AntBlazor.Docs/style/static/reset.less
  site/AntBlazor.Docs/style/static/rtl.less
  site/AntBlazor.Docs/style/static/theme.less
  site/AntBlazor.Docs/style/static/toc.less
  site/AntBlazor.Docs/style/template/Home/Banner/index.less
  site/AntBlazor.Docs/style/template/Home/DesignPage/index.less
  site/AntBlazor.Docs/style/template/Home/RecommendPage.less
  site/AntBlazor.Docs/style/template/Home/index.less
  site/AntBlazor.Docs/style/template/Layout/Header/Github.less
  site/AntBlazor.Docs/style/template/Layout/Header/Logo.less
  site/AntBlazor.Docs/style/template/Layout/Header/Navigation.less
  site/AntBlazor.Docs/style/template/Layout/Header/SearchBox.less
  site/AntBlazor.Docs/style/template/Layout/Header/index.less
  site/AntBlazor.Docs/style/template/Resources/AffixTabs.less
  site/AntBlazor.Docs/style/template/Resources/index.less
  site/AntBlazor.Docs/wwwroot/data/recommend.zh-CN.json
  site/AntDesign.Docs.Wasm/wwwroot/index.html
Labels: PR: unreviewed

#455 feat(module: drawer): add parameter handler
  components/drawer/Drawer.razor
  components/drawer/Drawer.razor.cs
Labels: PR: reviewed-approved

#459 fix(module:date-picker): fix inability to select new start date (#458)
  components/date-picker/RangePicker.razor.cs
Labels: PR: reviewed-approved

#460 test(button): add some button tests
  AntDesign.sln
  components/button/Button.razor.cs
  tests/AntDesign.Tests.csproj
  tests/AntDesignTestBase.cs
  tests/Properties/AssemblyInfo.cs
  tests/TestNavigationManager.cs
  tests/button/ButtonTests.cs
Labels: PR: unreviewed

#457 build(gulp): add .less source files as part of the output
  components/gulpfile.js
Labels: PR: reviewed-approved

#463 chore: add codecov step for actions
  .github/workflows/gh-pages.yml
  .github/workflows/pull-request.yml
  .gitignore
  README-zh_CN.md
  README.md
Labels: PR: unreviewed

#465 Add missing "run" from wasm start command
  package.json
Labels: PR: reviewed-approved

#462 feat(module:carousel): add new methods (#461)
  components/carousel/Carousel.razor.cs
  site/AntBlazor.Docs/Demos/Components/Carousel/demo/CustomButtons.md
  site/AntBlazor.Docs/Demos/Components/Carousel/demo/CustomButtons.razor
Labels: PR: unreviewed

#467 fix: remove the last message DOM after message disappears
  components/message/Message.razor.cs
Labels: PR: reviewed-approved

#470 fix(docs): handles fallback to en-US if resources are not available
  site/AntBlazor.Docs/Localization/InAssemblyLanguageService.cs
Labels: PR: unreviewed

#468 feat: add progress step
  components/steps/Step.razor
  components/steps/Step.razor.cs
  components/steps/Steps.razor.cs
  site/AntBlazor.Docs/Demos/Components/Steps/demo/Progress.razor
  site/AntBlazor.Docs/Demos/Components/Steps/demo/progress.md
Labels: PR: reviewed-approved

#480 chore: sync ant-design v4.5.3
  components/button/style/index.less
  components/cascader/style/index.less
  components/form/style/index.less
  components/mentions/style/index.less
  components/menu/style/dark.less
  components/menu/style/index.less
  components/menu/style/rtl.less
  components/pagination/style/index.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/steps/style/progress.less
  components/steps/style/rtl.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/transfer/style/index.less
Labels: PR: unreviewed

#485 Remove mention of typescript in PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
Labels: PR: reviewed-approved

#484 feat: add badge ribbon
  components/badge/BadgeRibbon.razor
  components/badge/BadgeRibbon.razor.cs
  components/badge/style/entry.less
  site/AntBlazor.Docs/Demos/Components/Badge/demo/Ribbon.razor
  site/AntBlazor.Docs/Demos/Components/Badge/demo/ribbon.md
  site/AntBlazor.Docs/Demos/Components/Badge/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Badge/doc/index.zh-CN.md
  tests/badge/RibbonTests.cs
Labels: PR: reviewed-approved

#486 chore: update license 3rd party
  LICENSE
  LICENSE-ant-design.txt
Labels: PR: unreviewed

#487 fix(module: table): formatting with nullable type
  components/core/Helpers/Formatter.cs
  components/core/Reflection/TypeDefined.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Blazor.razor
Labels: PR: unreviewed

#490 fix: ignore wwwroot for copying .less source files
  components/gulpfile.js
Labels: PR: unreviewed

#489 feat(module: list): add OnItemClick event callback for list items
  components/list/AntList.razor
  components/list/AntList.razor.cs
  components/list/AntListItem.razor
  components/list/AntListItem.razor.cs
  site/AntBlazor.Docs/Demos/Components/List/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/List/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/List/doc/index.zh-CN.md
Labels: PR: unreviewed

#477 chore: add format hook
  .config/dotnet-tools.json
  package.json
Labels: PR: unreviewed

#493 fix(module: table): empty column count and formatter
  components/core/Helpers/Formatter.cs
  components/table/Table.razor
Labels: PR: unreviewed

#494 fix(module: typography): missing Style property
  components/typography/Paragraph.cs
  components/typography/Text.cs
  components/typography/Title.cs
Labels: PR: unreviewed

#497 fix(module: tabs): missing event callbacks
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
  site/AntBlazor.Docs/Demos/Components/Tabs/demo/Basic.razor
Labels: PR: unreviewed

#498 fix(module: sider): cannot update theme dynamically
  components/layout/Sider.razor.cs
Labels: PR: reviewed-approved

#499 chore: sync ant-design v4.5.4
  components/alert/style/index.less
  components/badge/style/index.less
  components/date-picker/style/rtl.less
  components/form/style/index.less
  components/input/style/rtl.less
  components/style/themes/default.less
  components/tree/style/mixin.less
Labels: PR: unreviewed

#502 fix(module: alert): close motion 'Smoothly Unmount'
  components/alert/Alert.razor
  components/alert/Alert.razor.cs
  site/AntBlazor.Docs/Demos/Components/Alert/demo/Icon_.razor
  site/AntBlazor.Docs/Demos/Components/Alert/demo/SmoothClosed.razor
  site/AntBlazor.Docs/Demos/Components/Alert/demo/smooth-closed.md
Labels: PR: unreviewed, enhancement

#503 fix(module: radio): disabled in radio group doesn't work
  components/radio/Radio.razor.cs
  components/radio/style/entry.less
  site/AntBlazor.Docs/Demos/Components/Radio/demo/Style.razor
Labels: PR: unreviewed

#496 feat(module: range-picker): support form
  components/calendar/Calendar.razor.cs
  components/date-picker/IDatePicker.cs
  components/date-picker/RangePicker.razor
  components/date-picker/RangePicker.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerStatus.cs
  components/date-picker/internal/DatePickerTemplate.razor.cs
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/DateRender.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Disabled.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/DisabledDate.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/ExtraFooter.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/RangePickerDemo.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Size.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Time.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/Size.razor
Labels: PR: unreviewed

#506 feat: get the icon list of application icons from existed IconServices
  components/icon/IconService.cs
  site/AntBlazor.Docs/Demos/Components/Icon/demo/List.razor
  site/AntBlazor.Docs/Services/IconListService.cs
Labels: PR: reviewed-approved

#488 feat: add more demo on area chart
  site/AntBlazor.Docs/Demos/Charts/Area/demo/Area_.razor
  site/AntBlazor.Docs/Demos/Charts/Area/demo/StackedArea_.razor
Labels: PR: unreviewed

#513 fix(module: sider): can't collapse in demo
  components/core/Extensions/EnumerableExtensions.cs
  components/layout/Sider.razor
  components/layout/Sider.razor.cs
  components/menu/Menu.razor.cs
  components/menu/SubMenu.razor.cs
Labels: PR: unreviewed

#519 docs: use correct vs version
  docs/getting-started.zh-CN.md
Labels: PR: reviewed-approved

#523 feat(module: modal): allow drag Modal
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/core/JsInterop/modules/Caret.ts
  components/core/JsInterop/modules/dragHelper.ts
  components/modal/Dialog.razor
  components/modal/Dialog.razor.cs
  components/modal/Modal.razor.cs
  components/modal/config/DialogOptions.cs
  site/AntBlazor.Docs/Demos/Components/Modal/demo/DraggableModal.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/button-props.md
  site/AntBlazor.Docs/Demos/Components/Modal/demo/confirm-router.md
  site/AntBlazor.Docs/Demos/Components/Modal/demo/confirm_service.md
  site/AntBlazor.Docs/Demos/Components/Modal/demo/draggable_modal.md
  site/AntBlazor.Docs/Demos/Components/Modal/demo/manual.md
  site/AntBlazor.Docs/Demos/Components/Modal/demo/modal_service.md
  site/AntBlazor.Docs/Demos/Components/Modal/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Modal/doc/index.zh-CN.md
Labels: PR: unreviewed

#466 feat: subscribe to js event listener
  components/affix/Affix.razor.cs
  components/anchor/Anchor.razor.cs
  components/core/JsInterop/DomEventService.cs
  components/core/JsInterop/DomEventSubscription.cs
  components/descriptions/Descriptions.razor.cs
  components/grid/Row.razor.cs
  components/layout/Sider.razor.cs
  components/list/AntListItem.razor.cs
Labels: PR: unreviewed

#529 feat: auto complete refactor
  components/auto-complete/AutoComplete.razor
  components/auto-complete/AutoComplete.razor.cs
  components/auto-complete/AutoCompleteInput.cs
  components/auto-complete/AutoCompleteOptGroup.razor
  components/auto-complete/AutoCompleteOptGroup.razor.cs
  components/auto-complete/AutoCompleteOption.razor
  components/auto-complete/AutoCompleteOption.razor.cs
  components/auto-complete/AutoCompleteSearch.cs
  components/auto-complete/IAutoCompleteInput.cs
  components/auto-complete/IAutoCompleteRef.cs
  components/input/Input.cs
  components/input/TextArea.razor
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/CertainCategory.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Custom.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/NonCaseSensitive.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/ObjectValue.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/ObjectValue.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Options.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Property.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/UncertainCategory.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/basic.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/property.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/doc/index.zh-CN.md
Labels: PR: unreviewed

#535 fix：Repair SubMenu Bug
  components/menu/Menu.razor.cs
  components/menu/SubMenu.razor.cs
Labels: PR: unreviewed

#538 fix(module: statistic): separate decimal incorrectly
  components/statistic/Statistic.razor
  components/statistic/Statistic.razor.cs
Labels: PR: unreviewed

#539 fix(module: menu): can't open submenu while sider is collapsed
  components/core/Component/overlay/Overlay.razor.cs
  components/menu/SubMenu.razor.cs
Labels: PR: reviewed-approved

#542 fix(module: input): composition event conflict
  components/input/Input.cs
Labels: PR: unreviewed

#543 Update README-zh_CN.md
  README-zh_CN.md
Labels: PR: reviewed-approved

#544 feat: fix pageheader onbackicon
  components/anchor/Anchor.razor.cs
  components/page-header/PageHeader.razor
  components/page-header/PageHeader.razor.cs
  components/statistic/Statistic.razor.cs
  site/AntBlazor.Docs/Demos/Components/PageHeader/demo/Actions.razor
  site/AntBlazor.Docs/Demos/Components/PageHeader/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/PageHeader/demo/Content.razor
  site/AntBlazor.Docs/Demos/Components/PageHeader/demo/Ghost.razor
  site/AntBlazor.Docs/Demos/Components/PageHeader/demo/Responsive.razor
  site/AntBlazor.Docs/Demos/Components/PageHeader/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/PageHeader/doc/index.zh-CN.md
Labels: PR: unreviewed

#549 refactor: make the extensions class for HttpClient internal
  components/AntDesign.csproj
  components/core/Extensions/HttpClientExtensions.cs
  components/core/Extensions/ServiceCollectionExtensions.cs
  components/icon/IconService.cs
Labels: PR: unreviewed

#554 fix(module: checkbox): options.value works incorrectly
  components/checkbox/Checkbox.razor.cs
  components/checkbox/CheckboxGroup.razor
  components/checkbox/CheckboxGroup.razor.cs
  site/AntBlazor.Docs/Demos/Components/Checkbox/demo/Group.razor
Labels: PR: unreviewed

#537 add chart demo
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Demos/Charts/Bubble/demo/Bubble_.razor
  site/AntBlazor.Docs/Demos/Charts/Bullet/demo/Bullet_.razor
  site/AntBlazor.Docs/Demos/Charts/Column/demo/Column_.razor
  site/AntBlazor.Docs/Demos/Charts/Column/demo/Histogram_.razor
  site/AntBlazor.Docs/Demos/Charts/Column/demo/RangedColumn_.razor
  site/AntBlazor.Docs/Demos/Charts/Column/demo/StackedColumn_.razor
  site/AntBlazor.Docs/Demos/Charts/Combo/demo/ColumnLineCombo_.razor
  site/AntBlazor.Docs/Demos/Charts/Combo/demo/DualLineCombo_.razor
  site/AntBlazor.Docs/Demos/Charts/Combo/demo/GroupedColumnLineCombo_.razor
  site/AntBlazor.Docs/Demos/Charts/Combo/demo/StackedColumnLineCombo_.razor
  site/AntBlazor.Docs/Demos/Charts/Funnel/demo/Funnel_.razor
  site/AntBlazor.Docs/Demos/Charts/Gauge/demo/Gauge_.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Axis.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Guideline.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Legend.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/SetState.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/TitleAndDescription.razor
  site/AntBlazor.Docs/Demos/Charts/Heatmap/demo/Heatmap_.razor
  site/AntBlazor.Docs/Demos/Charts/Line/demo/MarkerPoint_.razor
  site/AntBlazor.Docs/Demos/Charts/Line/demo/MultipleLine_.razor
  site/AntBlazor.Docs/Demos/Charts/Liquid/demo/Liquid_.razor
  site/AntBlazor.Docs/Demos/Charts/Pie/demo/Donut_.razor
  site/AntBlazor.Docs/Demos/Charts/Pie/demo/Pie_.razor
  site/AntBlazor.Docs/Demos/Charts/Radar/demo/Radar_.razor
  site/AntBlazor.Docs/Demos/Charts/Rose/demo/Rose_.razor
  site/AntBlazor.Docs/Demos/Charts/Scatter/demo/Scatter_.razor
  site/AntBlazor.Docs/Demos/Charts/Step/demo/BasicStepLine_.razor
  site/AntBlazor.Docs/Demos/Charts/Step/demo/MultipleStepLine_.razor
  site/AntBlazor.Docs/Demos/Charts/Treemap/demo/Treemap_.razor
Labels: PR: reviewed-approved
