Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2020-09, with the labels that each got.

#558 fix(module: carousel): make carousel responsive
  components/carousel/Carousel.razor.cs
Labels: PR: unreviewed

#559 refactor: get PropertyInfo from expression
  components/core/Extensions/DataAnnotationsExtensions.cs
  components/core/Extensions/DataConvertionExtensions.cs
  components/core/Extensions/FieldIdentifierExtensions.cs
  components/core/Extensions/ServiceCollectionExtensions.cs
  components/core/Reflection/PropertyReflector.cs
  components/core/Reflection/TypeDefined.cs
  components/form/FormItem.razor.cs
  components/table/Column.razor.cs
  components/table/Table.razor.cs
  components/table/TableModels/QueryModel.cs
  components/table/TableModels/SortModel.cs
Labels: PR: unreviewed

#560 fix(module: upload): files that aren't pictures can't be downloaded
  components/upload/Upload.razor
Labels: PR: unreviewed

#553 fix: modal button sort
  components/modal/ConfirmDialog.razor
  components/modal/ModalFooter.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/Footer.razor
Labels: PR: unreviewed

#561 fix(module: upload): fileList can't be refreshed while it was changed
  components/core/Base/AntComponentBase.cs
  components/core/JsInterop/interop.ts
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
  site/AntBlazor.Docs/Demos/Components/Upload/demo/PictureCard.razor
  site/AntDesign.Docs.Server/Pages/_Host.cshtml
Labels: PR: unreviewed

#564 fix(module: button): allows type and shape to change
  components/button/Button.razor.cs
  tests/button/ButtonTests.cs
Labels: PR: reviewed-approved

#566 feat: add text keyboard parameter,and update demo
  components/typography/Paragraph.cs
  components/typography/Text.cs
  site/AntBlazor.Docs/Demos/Components/Typography/demo/Style.razor
Labels: PR: reviewed-approved

#569 fix(module: statistic): there is no title but the element is rendered
  components/statistic/Statistic.razor
Labels: PR: unreviewed

#573 fix(module: modal and drawer): body scroll bar does not respond correctly (#568)
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/drawer/Drawer.razor.cs
  components/modal/Dialog.razor.cs
Labels: PR: reviewed-approved

#572 fix(module: cascader): crashes when options is null
  components/cascader/Cascader.razor
Labels: PR: unreviewed

#570 fix(module: table): fix collection modified exception
  components/AntDesign.csproj
  components/core/Extensions/EnumerableExtensions.cs
  components/table/Table.razor.RowData.cs
  components/table/Table.razor.cs
  tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html
  tests/AntDesign.Tests.csproj
  tests/AntDesignTestBase.cs
  tests/RecordedTestExtensions.cs
  tests/table/TableTests.cs
Labels: PR: reviewed-approved

#575 refactor(formatter): merge the special method of timespan into formatter
  components/AssemblyInfo.cs
  components/core/Helpers/Formatter.cs
  components/slider/Slider.razor.cs
  components/statistic/CountDown.razor
  components/statistic/CountDown.razor.cs
  components/table/Column.razor
  site/AntBlazor.Docs/Demos/Components/Statistic/demo/Countdown.razor
  tests/Core/FormatterTests.cs
Labels: PR: unreviewed

#578 feat: support for globalization & localization
  components/AntDesign.csproj
  components/Properties/AssemblyInfo.cs
  components/calendar/Calendar.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerLocaleHelper.cs
  components/date-picker/locale/DatePickerLocale.cs
  components/date-picker/locale/IDateLocale.cs
  components/empty/Empty.razor.cs
  components/empty/EmptyLocale.cs
  components/form/FormLocale.cs
  components/icon/IconLocale.cs
  components/locale-provider/GlobalLocale.cs
  components/locale-provider/Locale.cs
  components/locale-provider/LocaleProvider.cs
  components/locales/en-US.json
  components/locales/zh-CN.json
  components/locales/zh-TW.json
  components/modal/ModalLocale.cs
  components/page-header/PageHeaderLocale.cs
  components/pagination/Pagination.razor.cs
  components/pagination/PaginationItem.razor.cs
  components/pagination/PaginationLocale.cs
  components/pagination/PaginationOptions.razor
  components/pagination/PaginationOptions.razor.cs
  components/popconfirm/PopconfirmLocale.cs
  components/select/SelectLocale.cs
  components/table/Column.razor.cs
  components/table/ITable.cs
  components/table/Table.razor.cs
  components/table/TableLocale.cs
  components/time-picker/TimePickerLocale.cs
  components/transfer/TransferLocale.cs
  components/typography/TextLocale.cs
  components/upload/UploadLocale.cs
  site/AntBlazor.Docs/Localization/InAssemblyLanguageService.cs
  tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html
  tests/AntDesign.Tests.csproj
  tests/AntDesignTestBase.cs
  tests/RecordedTestExtensions.cs
Labels: PR: unreviewed

#580 feat(module: i18n): add more languages
  components/locale-provider/LocaleProvider.cs
  components/locales/ar-EG.json
  components/locales/az-AZ.json
  components/locales/bg-BG.json
  components/locales/ca-ES.json
  components/locales/cs-CZ.json
  components/locales/da-DK.json
  components/locales/de-DE.json
  components/locales/el-GR.json
  components/locales/en-GB.json
  components/locales/es-ES.json
  components/locales/et-EE.json
  components/locales/fa-IR.json
  components/locales/fi-FI.json
  components/locales/fr-BE.json
  components/locales/fr-FR.json
  components/locales/he-IL.json
  components/locales/hi-IN.json
  components/locales/hr-HR.json
  components/locales/hu-HU.json
  components/locales/hy-AM.json
  components/locales/id-ID.json
  components/locales/is-IS.json
  components/locales/it-IT.json
  components/locales/ja-JP.json
  components/locales/ka-GE.json
  components/locales/kn-IN.json
  components/locales/ko-KR.json
  components/locales/ku-IQ.json
  components/locales/lv-LV.json
  components/locales/mk-MK.json
  components/locales/mn-MN.json
  components/locales/ms-MY.json
  components/locales/nb-NO.json
  components/locales/ne-NP.json
  components/locales/nl-BE.json
  components/locales/nl-NL.json
  components/locales/pl-PL.json
  components/locales/pt-BR.json
  components/locales/pt-PT.json
  components/locales/ro-RO.json
  components/locales/ru-RU.json
  components/locales/sk-SK.json
  components/locales/sl-SI.json
  components/locales/sr-RS.json
  components/locales/sv-SE.json
  components/locales/ta-IN.json
  components/locales/th-TH.json
  components/locales/tr-TR.json
  components/locales/uk-UA.json
  components/locales/vi-VN.json
Labels: PR: unreviewed

#581 docs: add i18n docs
  components/core/Extensions/ServiceCollectionExtensions.cs
  components/locale-provider/Locale.cs
  components/locale-provider/LocaleProvider.cs
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
  tests/AntDesignTestBase.cs
Labels: PR: unreviewed

#582 fix(module: table): the sorter doesn't work
  components/table/Table.razor.cs
Labels: PR: unreviewed

#547 fix(module: drawer): merge oncancel and onclose (#522)
  components/drawer/DrawerContainer.razor.cs
  components/drawer/DrawerRef.cs
  components/drawer/DrawerService.cs
  components/drawer/config/DrawerOptions.cs
  site/AntBlazor.Docs/Demos/Components/Drawer/demo/Drawer_service.razor
  site/AntBlazor.Docs/Demos/Components/Drawer/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Drawer/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#584 refactor(module: select): add overlay, fix some serious bugs
  components/core/Component/overlay/Overlay.razor
  components/core/Component/overlay/Overlay.razor.cs
  components/core/Component/overlay/OverlayTrigger.razor
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/select/Select.razor
  components/select/Select.razor.cs
  components/select/SelectOption.razor.cs
  components/select/internal/SelectBase.cs
  components/select/internal/SelectContent.razor
  site/AntBlazor.Docs/Demos/Components/Select/demo/CustomDropdownMenu.razor
  site/AntBlazor.Docs/Demos/Components/Select/demo/Search.razor
Labels: PR: reviewed-approved

#586 fix(module: select): wrong overlay style
  components/select/Select.razor
Labels: PR: reviewed-approved

#587 fix(module: list) grid not working
  components/list/AntListItem.razor
Labels: PR: reviewed-approved

#590 Fix Bug: When Menu is in Sider, Initial state of being collapsed not …
  components/menu/Menu.razor.cs
  package.json
Labels: PR: reviewed-approved

#592 chore: prepare for 0.4.0
  .github/workflows/gh-pages.yml
  .github/workflows/pr-preview.yml
  LICENSE
  LICENSE-ant-design.txt
Labels: PR: unreviewed

#589 feat(module: tabs): add support to ForceRender
  components/tabs/TabPane.razor.cs
  components/tabs/Tabs.razor
  tests/tabs/TabsTests.cs
Labels: PR: reviewed-approved

#591 Add link for discord chat
  README.md
Labels: PR: reviewed-approved

#577 chore: sync ant-design v4.6.3
  components/grid/style/rtl.less
  components/modal/style/modal.less
  components/pagination/style/index.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/table/style/index.less
  components/tree-select/style/index.less
  components/tree/style/index.less
  components/tree/style/mixin.less
  components/upload/style/index.less
Labels: PR: unreviewed

#595 extend steps to repoduce title
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: PR: unreviewed

#596 chore: sync ant-design v4.6.4
  components/card/style/index.less
  components/select/style/index.less
  components/select/style/single.less
  components/style/core/motion/zoom.less
  components/table/style/index.less
  components/table/style/rtl.less
Labels: PR: unreviewed

#601 chore: revert the pr preview action
  .github/workflows/pr-preview.yml
Labels: PR: unreviewed

#599 fix: drawer close event bug
  components/core/Base/TemplateComponentBase.cs
  components/drawer/DrawerContainer.razor
  components/drawer/DrawerContainer.razor.cs
  components/drawer/DrawerRef.cs
  components/drawer/DrawerService.cs
  components/drawer/DrawerTemplate.razor.cs
  components/drawer/IDrawerRef.cs
  components/drawer/config/DrawerClosingEventArgs.cs
  components/modal/ModalService.cs
  components/modal/ModalTemplate.razor.cs
  site/AntBlazor.Docs/Demos/Components/Drawer/DrawerTemplateDemo.razor
  site/AntBlazor.Docs/Demos/Components/Drawer/demo/Drawer_service.razor
  site/AntBlazor.Docs/Demos/Components/Modal/ModalTemplateDemo.razor
Labels: PR: reviewed-approved

#606 fix(module: select): add PopupContainerSelector parameter
  components/select/Select.razor
  components/select/internal/SelectBase.cs
Labels: PR: unreviewed

#603 refactor(module: list): allow to setup each list item
  components/list/AntList.razor
  components/list/AntList.razor.cs
  components/list/AntListItemMeta.razor
  components/list/ListItem.razor
  components/list/ListItem.razor.cs
  components/list/ListItemLayout.cs
  components/list/ListItemMeta.razor
  components/list/ListItemMeta.razor.cs
  site/AntBlazor.Docs/Demos/Components/Comment/demo/Editor.razor
  site/AntBlazor.Docs/Demos/Components/Comment/demo/List.razor
  site/AntBlazor.Docs/Demos/Components/Drawer/demo/Userprofile.razor
  site/AntBlazor.Docs/Demos/Components/List/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/List/demo/Grid.razor
  site/AntBlazor.Docs/Demos/Components/List/demo/Loadmore.razor
  site/AntBlazor.Docs/Demos/Components/List/demo/Resposive.razor
  site/AntBlazor.Docs/Demos/Components/List/demo/Simple.razor
  site/AntBlazor.Docs/Demos/Components/List/demo/Vertical.razor
  site/AntBlazor.Docs/Demos/Components/Skeleton/demo/List.razor
Labels: PR: unreviewed

#607 docs: add popupContainer
  components/auto-complete/AutoComplete.razor
  components/auto-complete/AutoComplete.razor.cs
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/select/Select.razor
  components/select/internal/SelectBase.cs
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/PopupContainer.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/popup-container.md
  site/AntBlazor.Docs/Demos/Components/Dropdown/demo/PopupContainer.razor
  site/AntBlazor.Docs/Demos/Components/Dropdown/demo/popup-container.md
  site/AntBlazor.Docs/Demos/Components/Select/demo/PopupContainer.razor
  site/AntBlazor.Docs/Demos/Components/Select/demo/popup-container.md
Labels: PR: unreviewed

#611 fix(module: menu): the selected menu item would unselect itself after is clicked again
  components/menu/Menu.razor.cs
Labels: PR: unreviewed

#613 fix(module: select): broken removing of selected tag
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor
Labels: PR: reviewed-approved

#612 chore: update the docs project to .net 5 rc1
  .github/workflows/gh-pages.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pull-request.yml
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj
  site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
  site/AntDesign.Docs.WasmHost/AntDesign.Docs.WasmHost.csproj
  tests/AntDesign.Tests.csproj
Labels: PR: unreviewed

#615 fix: follow up the .net 5 docs and fix the culture issue
  components/menu/Menu.razor.cs
  site/AntBlazor.Docs/Routing/ConventionRouter.cs
Labels: PR: unreviewed, documentation

#618 fix(module: list): list item layout in listitem
  components/list/AntList.razor
  components/list/AntList.razor.cs
  components/list/ListItem.razor
  components/list/ListItem.razor.cs
  site/AntBlazor.Docs/Demos/Components/Drawer/demo/Userprofile.razor
Labels: PR: unreviewed

#620 fix(module select): works incorrectly in modal
  components/select/Select.razor.cs
Labels: PR: reviewed-approved

#621 fix: [dropdown、select] work incorrectly in modal
  components/core/Component/overlay/Overlay.razor
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/modal/Dialog.razor.cs
  components/modal/Modal.razor
  components/select/Select.razor
  components/select/Select.razor.cs
  components/select/internal/SelectBase.cs
  components/select/internal/SelectContent.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/DropdownInModal.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/dropdown-in-modal.md
Labels: PR: reviewed-approved

#625 docs: fix prev-next navbar
  site/AntBlazor.Docs/Pages/Components.razor.cs
  site/AntBlazor.Docs/Pages/Docs.razor.cs
  site/AntBlazor.Docs/Services/DemoService.cs
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
  site/AntBlazor.Docs/Shared/NavMenu.razor.cs
  site/AntBlazor.Docs/Shared/PrevNextNav.razor
  site/AntDesign.Docs.Build.CLI/Command/GenerateMenuJsonCommand.cs
Labels: PR: unreviewed

#629 fix(module: select): incorrect dropdown style
  components/modal/Modal.razor
  components/select/Select.razor.cs
  components/select/internal/SelectBase.cs
  site/AntBlazor.Docs/Demos/Components/Modal/demo/DropdownInModal.razor
Labels: PR: reviewed-approved

#627 fix(module: card): grid and tabs has wrong styles
  components/card/Card.razor
  components/card/Card.razor.cs
  components/card/CardGrid.razor
  components/card/CardGrid.razor.cs
  components/card/CardMeta.razor
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
  site/AntBlazor.Docs/Demos/Components/Card/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/Card/demo/Customized.razor
  site/AntBlazor.Docs/Demos/Components/Card/demo/Loading.razor
  site/AntBlazor.Docs/Demos/Components/Card/demo/Noborder.razor
  site/AntBlazor.Docs/Demos/Components/Card/demo/Support.razor
  site/AntBlazor.Docs/Demos/Components/Card/demo/Tabs1.razor
  site/AntBlazor.Docs/Demos/Components/Card/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Card/doc/index.zh-CN.md
  site/AntBlazor.Docs/Pages/Index.razor
  site/AntBlazor.Docs/Services/DemoService.cs
Labels: PR: unreviewed

#632 fix: allow setting class for statistic component
  components/statistic/CountDown.razor
  components/statistic/CountDown.razor.cs
  components/statistic/Statistic.razor
  components/statistic/StatisticComponentBase.razor.cs
Labels: PR: reviewed-approved

#633 chore: sync ant-design v4.6.5
  components/button/style/index.less
  components/date-picker/style/panel.less
  components/descriptions/style/index.less
  components/layout/style/index.less
  components/menu/style/index.less
  components/space/style/index.less
  components/style/themes/default.less
  components/table/style/index.less
Labels: PR: unreviewed

#634 fix: subMenu of subMenu rendering is invalid
  components/menu/SubMenu.razor
  site/AntBlazor.Docs/Demos/Components/Menu/demo/Horizontal.razor
Labels: PR: reviewed-approved

#636 fix: the prerendering interop exception with some components
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/descriptions/Descriptions.razor.cs
  components/slider/Slider.razor.cs
Labels: PR: unreviewed

#638 docs: disable the linker for workaround the table page breaking
  site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
Labels: PR: unreviewed

#641 docs: workaround for the linker bug
  site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
Labels: PR: unreviewed

#642 fix(module: badge): incorrect status dot & disappeared scroll number
  components/badge/Badge.razor
  components/badge/Badge.razor.cs
  components/badge/style/entry.less
  site/AntBlazor.Docs/Demos/Components/Badge/demo/Dot.razor
  site/AntBlazor.Docs/Demos/Components/Badge/demo/Offset.razor
  site/AntBlazor.Docs/Demos/Components/Badge/demo/Size.razor
  site/AntBlazor.Docs/Demos/Components/Badge/demo/offset.md
  site/AntBlazor.Docs/Demos/Components/Badge/demo/size.md
  site/AntBlazor.Docs/Demos/Components/Badge/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Badge/doc/index.zh-CN.md
Labels: PR: unreviewed

#650 fix: textarea display bug
  components/input/TextArea.razor
Labels: PR: reviewed-approved

#647 fix(module: auto-complete): could not select value by chance
  components/auto-complete/AutoComplete.razor
  components/auto-complete/AutoComplete.razor.cs
Labels: PR: unreviewed

#648 chore: sync ant-design v4.6.6
  components/divider/style/index.less
  components/form/style/status.less
  components/steps/style/vertical.less
  components/typography/style/index.less
Labels: PR: unreviewed

#653 fix(module: slider): cannot slide
  components/core/JsInterop/DomEventService.cs
  components/core/JsInterop/DomEventSubscription.cs
  components/slider/Slider.razor.cs
Labels: PR: reviewed-approved

#654 fix(module: confirm): cannot config confirm width (#651)
  components/modal/ConfirmDialog.razor.cs
  components/modal/config/ConfirmOptions.cs
Labels: PR: reviewed-approved
