Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2020-06, with the labels that each got.

#171 refactor: remove the form item dependency
  components/core/Base/AntInputComponentBase.cs
  components/core/Forms/IControlValueAccessor.cs
  components/form/Form.razor.cs
  components/form/FormItem.razor.cs
  components/form/Internal/IForm.cs
  components/form/Internal/IFormItem.cs
Labels: PR: reviewed-approved

#173 refactor: tag and card demo
  components/input/Input.cs
  components/input/TextArea.razor
  components/input/TextArea.razor.cs
  components/tag/AntTag.razor
  components/tag/AntTag.razor.cs
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Demos/Badge/demo/Change.razor
  site/AntBlazor.Docs/Demos/Card/demo/Basic.md
  site/AntBlazor.Docs/Demos/Card/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Card/demo/Column.md
  site/AntBlazor.Docs/Demos/Card/demo/Column.razor
  site/AntBlazor.Docs/Demos/Card/demo/Customized.md
  site/AntBlazor.Docs/Demos/Card/demo/Customized.razor
  site/AntBlazor.Docs/Demos/Card/demo/Grid.md
  site/AntBlazor.Docs/Demos/Card/demo/Grid.razor
  site/AntBlazor.Docs/Demos/Card/demo/Inner.md
  site/AntBlazor.Docs/Demos/Card/demo/Inner.razor
  site/AntBlazor.Docs/Demos/Card/demo/Loading.md
  site/AntBlazor.Docs/Demos/Card/demo/Loading.razor
  site/AntBlazor.Docs/Demos/Card/demo/Noborder.md
  site/AntBlazor.Docs/Demos/Card/demo/Noborder.razor
  site/AntBlazor.Docs/Demos/Card/demo/Simple.md
  site/AntBlazor.Docs/Demos/Card/demo/Simple.razor
  site/AntBlazor.Docs/Demos/Card/demo/Support.md
  site/AntBlazor.Docs/Demos/Card/demo/Support.razor
  site/AntBlazor.Docs/Demos/Card/demo/Tabs.md
  site/AntBlazor.Docs/Demos/Card/demo/Tabs.razor
  site/AntBlazor.Docs/Demos/Card/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Card/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Input/demo/Addon.razor
  site/AntBlazor.Docs/Demos/Input/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Input/demo/Clear.md
  site/AntBlazor.Docs/Demos/Input/demo/Clear.razor
  site/AntBlazor.Docs/Demos/Input/demo/Password.md
  site/AntBlazor.Docs/Demos/Input/demo/Password.razor
  site/AntBlazor.Docs/Demos/Input/demo/Search_.razor
  site/AntBlazor.Docs/Demos/Input/demo/Size.razor
  site/AntBlazor.Docs/Demos/Menu/demo/SwitchMode.razor
  site/AntBlazor.Docs/Demos/Menu/demo/Theme.razor
  site/AntBlazor.Docs/Demos/Space/demo/Customize.razor
  site/AntBlazor.Docs/Demos/Spin/demo/DelayAndDebounce.razor
  site/AntBlazor.Docs/Demos/Spin/demo/Nested.razor
  site/AntBlazor.Docs/Demos/Tag/demo/Basic.md
  site/AntBlazor.Docs/Demos/Tag/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Tag/demo/Checkable.md
  site/AntBlazor.Docs/Demos/Tag/demo/Checkable.razor
  site/AntBlazor.Docs/Demos/Tag/demo/Colorful.md
  site/AntBlazor.Docs/Demos/Tag/demo/Colorful.razor
  site/AntBlazor.Docs/Demos/Tag/demo/Controlled.md
  site/AntBlazor.Docs/Demos/Tag/demo/Controlled.razor
  site/AntBlazor.Docs/Demos/Tag/demo/Dynamic.md
  site/AntBlazor.Docs/Demos/Tag/demo/Dynamic.razor
  site/AntBlazor.Docs/Demos/Tag/demo/Hot.md
  site/AntBlazor.Docs/Demos/Tag/demo/Hot.razor
  site/AntBlazor.Docs/Demos/Tag/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Tag/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Transfer/demo/Basic.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#172 add component cascader
  components/cascader/Cascader.razor
  components/cascader/Cascader.razor.cs
  components/cascader/CascaderNode.cs
  site/AntBlazor.Docs/Demos/Cascader/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Cascader/demo/Change.razor
  site/AntBlazor.Docs/Demos/Cascader/demo/Default.razor
  site/AntBlazor.Docs/Demos/Cascader/demo/Disabled.razor
  site/AntBlazor.Docs/Demos/Cascader/demo/Hover.razor
  site/AntBlazor.Docs/Demos/Cascader/demo/Size.razor
  site/AntBlazor.Docs/Demos/Cascader/demo/basic.md
  site/AntBlazor.Docs/Demos/Cascader/demo/change.md
  site/AntBlazor.Docs/Demos/Cascader/demo/default.md
  site/AntBlazor.Docs/Demos/Cascader/demo/disabled.md
  site/AntBlazor.Docs/Demos/Cascader/demo/hover.md
  site/AntBlazor.Docs/Demos/Cascader/demo/size.md
  site/AntBlazor.Docs/Demos/Cascader/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Cascader/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#174 chore: sync ant-design v4.3.1
  components/button/style/index.less
  components/button/style/mixin.less
  components/dropdown/style/index.less
  components/select/style/index.less
  components/table/style/index.less
  components/tabs/style/card.less
  components/tabs/style/dropdown.less
  components/tabs/style/index.less
  components/tabs/style/position.less
  components/tabs/style/rtl.less
  components/upload/style/index.less
Labels: PR: unreviewed

#161 feat(module: checkbox): support form
  components/checkbox/Checkbox.razor
  components/checkbox/Checkbox.razor.cs
  components/checkbox/CheckboxGroup.razor
  components/core/Base/AntInputComponentBase.cs
  components/form/Form.razor.cs
  components/transfer/Transfer.razor
  site/AntBlazor.Docs/Demos/Checkbox/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Form/demo/Basic.razor
Labels: PR: reviewed-approved

#178 fix: table pagination
  components/pagination/Pagination.razor
  components/pagination/Pagination.razor.cs
  components/pagination/PaginationEventArgs.cs
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
Labels: PR: unreviewed

#179 fix: input error without form
  components/checkbox/Checkbox.razor.cs
  components/core/Base/AntInputComponentBase.cs
  components/input/Input.cs
Labels: PR: reviewed-approved

#176 feat: add calendar
  components/calendar/Calendar.razor
  components/calendar/Calendar.razor.cs
  components/calendar/CalendarHeaderRenderCallback.cs
  components/calendar/internal/CalendarHeader.razor
  components/calendar/internal/CalendarPanelChooser.razor
  components/calendar/internal/CalendarPanelChooser.razor.cs
  components/core/Helpers/DateHelper.cs
  components/date-picker/IDatePicker.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerDatePanel.razor
  components/date-picker/internal/DatePickerDatetimePanel.razor
  components/date-picker/internal/DatePickerDatetimePanel.razor.cs
  components/date-picker/internal/DatePickerDecadePanel.razor
  components/date-picker/internal/DatePickerHeader.razor
  components/date-picker/internal/DatePickerMonthPanel.razor
  components/date-picker/internal/DatePickerPanelBase.cs
  components/date-picker/internal/DatePickerPanelChooser.razor
  components/date-picker/internal/DatePickerQuarterPanel.razor
  components/date-picker/internal/DatePickerTemplate.razor
  components/date-picker/internal/DatePickerYearPanel.razor
  site/AntBlazor.Docs/Demos/Calendar/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Calendar/demo/Card_.razor
  site/AntBlazor.Docs/Demos/Calendar/demo/CustomizeHeader.razor
  site/AntBlazor.Docs/Demos/Calendar/demo/NoticeCalendar.razor
  site/AntBlazor.Docs/Demos/Calendar/demo/Select_.razor
  site/AntBlazor.Docs/Demos/Calendar/demo/basic.md
  site/AntBlazor.Docs/Demos/Calendar/demo/card.md
  site/AntBlazor.Docs/Demos/Calendar/demo/customize-header.md
  site/AntBlazor.Docs/Demos/Calendar/demo/notice-calendar.md
  site/AntBlazor.Docs/Demos/Calendar/demo/select.md
  site/AntBlazor.Docs/Demos/Calendar/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Calendar/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#180 fix: fix input bug
  components/core/Base/AntInputComponentBase.cs
Labels: PR: reviewed-approved

#182 fix: input component bug
  components/checkbox/Checkbox.razor.cs
  components/core/Base/AntInputComponentBase.cs
  components/form/MyCustomValidator.cs
  components/input/Input.cs
  site/AntBlazor.Docs/Demos/Form/demo/ControlHooks.razor
Labels: PR: reviewed-approved

#184 refactor: layout and mock-browser
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/Window.cs
  components/core/JsInterop/interop.ts
  components/layout/BreakpointType.cs
  components/layout/Sider.razor
  components/layout/Sider.razor.cs
  components/layout/SiderTheme.cs
  components/menu/SubMenu.razor.cs
  site/AntBlazor.Docs/Demos/Layout/demo/CustomTrigger.razor
  site/AntBlazor.Docs/Demos/Layout/demo/Fixed.razor
  site/AntBlazor.Docs/Demos/Layout/demo/FixedSider.razor
  site/AntBlazor.Docs/Demos/Layout/demo/Responsive.razor
  site/AntBlazor.Docs/Demos/Layout/demo/Side.razor
  site/AntBlazor.Docs/Demos/Layout/demo/TopSide2.razor
  site/AntBlazor.Docs/Pages/Mock.razor
  site/AntBlazor.Docs/Shared/BlankLayout.razor
  site/AntBlazor.Docs/Shared/CodeBox.razor
  site/AntBlazor.Docs/Shared/MockBrowser.razor
  site/AntBlazor.Docs/Shared/MockBrowser.razor.cs
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
Labels: PR: unreviewed

#185 feat(module: input-number): support form
  components/input-number/InputNumber.razor
  components/input-number/InputNumber.razor.cs
  site/AntBlazor.Docs/Demos/Form/demo/Size.razor
  site/AntBlazor.Docs/Demos/Form/demo/size.md
Labels: PR: reviewed-approved

#186 fix: menu title padding and layout demo
  components/layout/Sider.razor
  components/layout/Sider.razor.cs
  components/menu/MenuItem.razor
  components/menu/MenuItem.razor.cs
  components/menu/SubMenu.razor
  components/menu/SubMenu.razor.cs
  site/AntBlazor.Docs/Demos/Layout/demo/CustomTrigger.razor
  site/AntBlazor.Docs/Demos/Menu/demo/Horizontal.razor
  site/AntBlazor.Docs/Demos/Menu/demo/Inline.razor
  site/AntBlazor.Docs/Demos/Menu/demo/InlineCollapsed.razor
  site/AntBlazor.Docs/Pages/Mock.razor
  site/AntBlazor.Docs/Shared/CodeBox.razor
Labels: PR: unreviewed

#177 fix: drawer and modal bug
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/drawer/Drawer.razor.cs
  components/modal/Dialog.razor.cs
Labels: PR: reviewed-approved

#183 Fix: Search component wait time
  components/input/Search.razor.cs
Labels: PR: partially-approved

#190 feat(module: table): add selection
  components/core/EnumerableExtensions.cs
  components/radio/Radio.razor
  components/radio/Radio.razor.cs
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/IRowSelection.cs
  components/table/ITable.cs
  components/table/ITableColumn.cs
  components/table/RowSelection.cs
  components/table/RowSelection.razor
  components/table/RowSelection.razor.cs
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  components/table/Table.razor.Section.cs
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Table/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
  site/AntBlazor.Docs/Demos/Table/demo/RowSelection_.razor
  site/AntBlazor.Docs/Demos/Table/demo/row-selection.md
Labels: PR: unreviewed

#189 Fix : Spin "Spinning" attribute is invalid
  components/spin/Spin.razor.cs
Labels: PR: reviewed-approved

#191 feat(module: input components): support set size by form
  components/button/Button.razor.cs
  components/cascader/Cascader.razor.cs
  components/core/Base/AntInputComponentBase.cs
  components/date-picker/internal/DatePickerBase.cs
  components/form/Form.razor
  components/form/Form.razor.cs
  components/form/FormItem.razor
  components/form/Internal/IForm.cs
  components/input-number/InputNumber.razor.cs
  components/input/Input.cs
  components/input/Search.razor.cs
  components/switch/Switch.razor
  components/switch/Switch.razor.cs
  site/AntBlazor.Docs/Demos/Form/demo/Size.razor
Labels: PR: reviewed-approved

#194 chore: sync ant-design v4.3.2
  components/dropdown/style/index.less
  components/input/style/IE11.less
  components/input/style/index.less
  components/modal/style/rtl.less
  components/style/themes/default.less
  components/table/style/index.less
  components/table/style/size.less
  components/tabs/style/rtl.less
Labels: PR: unreviewed

#198 fix(module: spin): loading delay
  components/spin/Spin.razor.cs
Labels: PR: unreviewed

#200 chore: sync ant-design v4.3.3
  components/menu/style/index.less
Labels: PR: unreviewed

#201 fix: drawer unresponsive In the WASM
  components/drawer/Drawer.razor.cs
Labels: PR: reviewed-approved

#204 fix: event not responding #203
  components/modal/Dialog.razor
  components/modal/Modal.razor.cs
Labels: PR: reviewed-approved

#205 feat: add-Statistic
  components/statistic/CountDown.razor
  components/statistic/CountDown.razor.cs
  components/statistic/Statistic.razor
  components/statistic/Statistic.razor.cs
  components/statistic/StatisticComponentBase.razor
  components/statistic/StatisticComponentBase.razor.cs
  site/AntBlazor.Docs/Demos/Statistic/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Statistic/demo/Card_.razor
  site/AntBlazor.Docs/Demos/Statistic/demo/Countdown.razor
  site/AntBlazor.Docs/Demos/Statistic/demo/Unit.razor
  site/AntBlazor.Docs/Demos/Statistic/demo/basic.md
  site/AntBlazor.Docs/Demos/Statistic/demo/card.md
  site/AntBlazor.Docs/Demos/Statistic/demo/countdown.md
  site/AntBlazor.Docs/Demos/Statistic/demo/unit.md
  site/AntBlazor.Docs/Demos/Statistic/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Statistic/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#207 feat: upgrade tabs component
  components/tabs/TabPane.razor.cs
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
  site/AntBlazor.Docs/Demos/Tabs/demo/Basic.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/Card.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Card.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/CardTop.md
  site/AntBlazor.Docs/Demos/Tabs/demo/CardTop.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/CustomAddTrigger.md
  site/AntBlazor.Docs/Demos/Tabs/demo/CustomAddTrigger.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/CustomTabBar.md
  site/AntBlazor.Docs/Demos/Tabs/demo/CustomTabBar.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/CustomTabBarNode.md
  site/AntBlazor.Docs/Demos/Tabs/demo/CustomTabBarNode.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/Disabled.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Disabled.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/EditableCard.md
  site/AntBlazor.Docs/Demos/Tabs/demo/EditableCard.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/Extra.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Extra.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/Icon.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Icon.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/Position.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Position.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/Size.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Size.razor
  site/AntBlazor.Docs/Demos/Tabs/demo/Slide.md
  site/AntBlazor.Docs/Demos/Tabs/demo/Slide.razor
  site/AntBlazor.Docs/Demos/Tabs/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Tabs/doc/index.zh-CN.md
  site/AntBlazor.Docs/Pages/Tabsdemo.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#202 feat: form supports loading state
  components/form/Form.razor
  components/form/Form.razor.cs
  site/AntBlazor.Docs/Demos/Form/demo/Loading.razor
  site/AntBlazor.Docs/Demos/Form/demo/loading.md
Labels: PR: reviewed-approved

#213 refactor: remove Markdig and YamlDotnet
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Localization/InAssemblyLanguageService.cs
  site/AntBlazor.Docs/Localization/Resources.cs
  site/AntBlazor.Docs/Pages/Docs.razor
  site/AntBlazor.Docs/Shared/Markdown.razor
  site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj
  site/AntDesign.Docs.Build.CLI/Command/GenerateDocsToHtmlCommand.cs
  site/AntDesign.Docs.Build.CLI/Program.cs
  site/AntDesign.Docs.Build.CLI/Properties/launchSettings.json
  site/AntDesign.Docs.Build.CLI/Utils/DocParser.cs
  site/Shared/DocsFile.cs
Labels: PR: unreviewed

#210 feat(module: overlay): add offset parameter
  components/core/Component/overlay/Overlay.razor.cs
Labels: PR: reviewed-approved

#217 feat(module: form): add validate method to form
  components/form/Form.razor.cs
  components/form/Internal/IForm.cs
Labels: PR: unreviewed

#218 fix(module: modal): close icon
  components/modal/config/DialogOptions.cs
Labels: PR: unreviewed

#216 feat(module: carousel): scroll vertically for Left/Right DotPosition
  components/carousel/Carousel.razor
  components/carousel/Carousel.razor.cs
  site/AntBlazor.Docs/Demos/Carousel/demo/Automatic.razor
  site/AntBlazor.Docs/Demos/Carousel/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Carousel/demo/Position.razor
Labels: PR: reviewed-approved

#220 refactor: improve document performance
  components/icon/Icon.razor.cs
  components/modal/Modal.razor.cs
  site/AntBlazor.Docs/App.razor
  site/AntBlazor.Docs/Localization/InAssemblyLanguageService.cs
  site/AntBlazor.Docs/Pages/Mock.razor
  site/AntBlazor.Docs/Routing/ConventionRouter.cs
  site/AntBlazor.Docs/Services/DemoService.cs
  site/AntBlazor.Docs/Shared/CodeBox.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
Labels: PR: unreviewed

#211 feat: add page-header components
  components/page-header/PageHeader.razor
  components/page-header/PageHeader.razor.cs
  components/statistic/Statistic.razor.cs
  site/AntBlazor.Docs/Demos/PageHeader/demo/Actions.razor
  site/AntBlazor.Docs/Demos/PageHeader/demo/Basic.razor
  site/AntBlazor.Docs/Demos/PageHeader/demo/Content.razor
  site/AntBlazor.Docs/Demos/PageHeader/demo/Ghost.razor
  site/AntBlazor.Docs/Demos/PageHeader/demo/PageHeaderBreadcrumb.razor
  site/AntBlazor.Docs/Demos/PageHeader/demo/Responsive.razor
  site/AntBlazor.Docs/Demos/PageHeader/demo/actions.md
  site/AntBlazor.Docs/Demos/PageHeader/demo/basic.md
  site/AntBlazor.Docs/Demos/PageHeader/demo/content.md
  site/AntBlazor.Docs/Demos/PageHeader/demo/ghost.md
  site/AntBlazor.Docs/Demos/PageHeader/demo/page-header-breadcrumb.md
  site/AntBlazor.Docs/Demos/PageHeader/demo/responsive.md
  site/AntBlazor.Docs/Demos/PageHeader/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/PageHeader/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#221 docs: fix pwa cache
  site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
Labels: PR: unreviewed

#222 feat: add select component
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/core/Point.cs
  components/select/LabeledValue.cs
  components/select/Properties.cs
  components/select/Select.razor
  components/select/Select.razor.cs
  components/select/SelectMode.cs
  components/select/SelectModeExtensions.cs
  components/select/SelectOptGroup.razor
  components/select/SelectOptGroup.razor.cs
  components/select/SelectOption.razor
  components/select/SelectOption.razor.cs
  site/AntBlazor.Docs/Demos/Select/demo/AutomaticTokenization.razor
  site/AntBlazor.Docs/Demos/Select/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Select/demo/BigData.razor
  site/AntBlazor.Docs/Demos/Select/demo/Bordered.razor
  site/AntBlazor.Docs/Demos/Select/demo/Coordinate.razor
  site/AntBlazor.Docs/Demos/Select/demo/CustomDropdownMenu.razor
  site/AntBlazor.Docs/Demos/Select/demo/CustomTagRender.razor
  site/AntBlazor.Docs/Demos/Select/demo/Debug.razor
  site/AntBlazor.Docs/Demos/Select/demo/HideSelected.razor
  site/AntBlazor.Docs/Demos/Select/demo/LabelInValue.razor
  site/AntBlazor.Docs/Demos/Select/demo/Multiple.razor
  site/AntBlazor.Docs/Demos/Select/demo/Optgroup.razor
  site/AntBlazor.Docs/Demos/Select/demo/OptionLabelProp.razor
  site/AntBlazor.Docs/Demos/Select/demo/Search.razor
  site/AntBlazor.Docs/Demos/Select/demo/SearchBox.razor
  site/AntBlazor.Docs/Demos/Select/demo/SelectUsers.razor
  site/AntBlazor.Docs/Demos/Select/demo/Size.razor
  site/AntBlazor.Docs/Demos/Select/demo/Suffix.razor
  site/AntBlazor.Docs/Demos/Select/demo/Tags.razor
  site/AntBlazor.Docs/Demos/Select/demo/automatic-tokenization.md
  site/AntBlazor.Docs/Demos/Select/demo/basic.md
  site/AntBlazor.Docs/Demos/Select/demo/big-data.md
  site/AntBlazor.Docs/Demos/Select/demo/bordered.md
  site/AntBlazor.Docs/Demos/Select/demo/coordinate.md
  site/AntBlazor.Docs/Demos/Select/demo/custom-dropdown-menu.md
  site/AntBlazor.Docs/Demos/Select/demo/custom-tag-render.md
  site/AntBlazor.Docs/Demos/Select/demo/debug.md
  site/AntBlazor.Docs/Demos/Select/demo/hide-selected.md
  site/AntBlazor.Docs/Demos/Select/demo/label-in-value.md
  site/AntBlazor.Docs/Demos/Select/demo/multiple.md
  site/AntBlazor.Docs/Demos/Select/demo/optgroup.md
  site/AntBlazor.Docs/Demos/Select/demo/option-label-prop.md
  site/AntBlazor.Docs/Demos/Select/demo/search-box.md
  site/AntBlazor.Docs/Demos/Select/demo/search.md
  site/AntBlazor.Docs/Demos/Select/demo/select-users.md
  site/AntBlazor.Docs/Demos/Select/demo/size.md
  site/AntBlazor.Docs/Demos/Select/demo/suffix.md
  site/AntBlazor.Docs/Demos/Select/demo/tags.md
  site/AntBlazor.Docs/Demos/Select/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Select/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
  site/AntDesign.Docs.Build.CLI/Command/GenerateDocsToHtmlCommand.cs
Labels: PR: reviewed-approved

#223 chore: sync ant-design v4.3.4
  components/comment/style/index.less
  components/comment/style/rtl.less
  components/divider/style/index.less
  components/divider/style/rtl.less
  components/input/style/rtl.less
  components/rate/style/index.less
  components/steps/style/nav.less
  components/style/themes/default.less
  components/tabs/style/dropdown.less
Labels: PR: unreviewed

#227 fix: workaround for PWA manifest version updating
  .github/workflows/gh-pages.yml
Labels: PR: unreviewed

#206 feat: add localization option to DatePicker
  components/calendar/Calendar.razor.cs
  components/date-picker/IDatePicker.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerDatePanel.razor
  components/date-picker/internal/DatePickerDatetimePanel.razor
  components/date-picker/internal/DatePickerFooter.razor
  components/date-picker/internal/DatePickerHeader.razor
  components/date-picker/internal/DatePickerLocaleHelper.cs
  components/date-picker/internal/DatePickerMonthPanel.razor
  components/date-picker/internal/DatePickerQuarterPanel.razor
  components/date-picker/internal/DatePickerYearPanel.razor
  components/date-picker/types/DatePickerPlaceholder.cs
  site/AntBlazor.Docs/Demos/DatePicker/demo/Basic.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Bordered.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/DateRender.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Disabled.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/DisabledDate.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/ExtraFooter.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Format.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Globalization.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/RangePickerDemo.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Size.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Time.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/globalization.md
  site/AntBlazor.Docs/Demos/DatePicker/doc/index.zh-CN.md
Labels: PR: partially-approved

#229 refactor(module:table): rename `ShowPagination` to `HidePagination`
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
Labels: PR: unreviewed

#230 fix(module: icon): base-address exception #228
  components/icon/Icon.razor.cs
  components/icon/IconFont.razor.cs
  components/icon/IconService.cs
  site/AntBlazor.Docs/Demos/Icon/demo/Iconfont.razor
  site/AntBlazor.Docs/Demos/Icon/demo/ScriptUrl.razor
  site/AntBlazor.Docs/Demos/Icon/demo/scriptUrl.md
Labels: PR: unreviewed

#226 feat: add Collapse component
  components/collapse/Collapse.razor
  components/collapse/Collapse.razor.cs
  components/collapse/CollapseExpandIconPosition.cs
  components/collapse/Panel.razor
  components/collapse/Panel.razor.cs
  components/descriptions/Descriptions.razor.cs
  site/AntBlazor.Docs/Demos/Collapse/demo/Accordion.razor
  site/AntBlazor.Docs/Demos/Collapse/demo/Basic.md
  site/AntBlazor.Docs/Demos/Collapse/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Collapse/demo/Borderless.razor
  site/AntBlazor.Docs/Demos/Collapse/demo/Custom.razor
  site/AntBlazor.Docs/Demos/Collapse/demo/Extra.razor
  site/AntBlazor.Docs/Demos/Collapse/demo/Mix.razor
  site/AntBlazor.Docs/Demos/Collapse/demo/Noarrow.razor
  site/AntBlazor.Docs/Demos/Collapse/demo/accordion.md
  site/AntBlazor.Docs/Demos/Collapse/demo/borderless.md
  site/AntBlazor.Docs/Demos/Collapse/demo/custom.md
  site/AntBlazor.Docs/Demos/Collapse/demo/extra.md
  site/AntBlazor.Docs/Demos/Collapse/demo/mix.md
  site/AntBlazor.Docs/Demos/Collapse/demo/noarrow.md
  site/AntBlazor.Docs/Demos/Collapse/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Collapse/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#231 feat(module: calendar): replace select component, support en-us
  components/calendar/internal/CalendarHeader.razor
  components/date-picker/internal/DatePickerLocaleHelper.cs
Labels: PR: unreviewed

#234 feat: add skeleton
  components/skeleton/Skeleton.razor
  components/skeleton/Skeleton.razor.cs
  components/skeleton/SkeletonElement.razor
  components/skeleton/SkeletonElement.razor.cs
  components/skeleton/SkeletonType.cs
  site/AntBlazor.Docs/Demos/Skeleton/demo/Active.razor
  site/AntBlazor.Docs/Demos/Skeleton/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Skeleton/demo/Children.razor
  site/AntBlazor.Docs/Demos/Skeleton/demo/Complex.razor
  site/AntBlazor.Docs/Demos/Skeleton/demo/Element.razor
  site/AntBlazor.Docs/Demos/Skeleton/demo/List.razor
  site/AntBlazor.Docs/Demos/Skeleton/demo/active.md
  site/AntBlazor.Docs/Demos/Skeleton/demo/basic.md
  site/AntBlazor.Docs/Demos/Skeleton/demo/children.md
  site/AntBlazor.Docs/Demos/Skeleton/demo/complex.md
  site/AntBlazor.Docs/Demos/Skeleton/demo/element.md
  site/AntBlazor.Docs/Demos/Skeleton/demo/list.md
  site/AntBlazor.Docs/Demos/Skeleton/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Skeleton/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#240 chore: sync ant-design v4.3.5
  components/anchor/style/rtl.less
  components/back-top/style/index.less
  components/button/style/index.less
  components/button/style/mixin.less
  components/checkbox/style/rtl.less
  components/date-picker/style/panel.less
  components/descriptions/style/index.less
  components/list/style/index.less
  components/menu/style/dark.less
  components/menu/style/rtl.less
  components/page-header/style/index.less
  components/radio/style/rtl.less
  components/style/color/colorPalette.less
  components/style/themes/compact.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/style/bordered.less
  components/table/style/index.less
  components/table/style/rtl.less
  components/tabs/style/index.less
Labels: PR: unreviewed

#241 feat: add DrawerService
  components/core/AntContainer.razor
  components/core/Base/TemplateComponentBase.cs
  components/core/ServiceCollectionExtensions.cs
  components/drawer/Drawer.razor.cs
  components/drawer/DrawerContainer.razor
  components/drawer/DrawerContainer.razor.cs
  components/drawer/DrawerRef.cs
  components/drawer/DrawerService.cs
  components/drawer/DrawerTemplate.razor.cs
  components/drawer/config/DrawerConfig.cs
  components/modal/Comfirm.razor
  components/modal/Comfirm.razor.cs
  components/modal/ConfirmDialog.razor.cs
  components/modal/Dialog.razor.cs
  components/modal/Modal.razor.cs
  components/modal/ModalFooter.razor.cs
  components/modal/ModalService.cs
  components/modal/config/ConfirmOptions.cs
  components/modal/config/DialogOptions.cs
  site/AntBlazor.Docs/Demos/Drawer/ComponentTemplate.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/Drawer_service.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/drawer_service.md
  site/AntBlazor.Docs/Demos/Modal/demo/Confirm.razor
  site/AntBlazor.Docs/Demos/Modal/demo/ConfirmPromise.razor
  site/AntBlazor.Docs/Demos/Modal/demo/ConfirmRouter.razor
  site/AntBlazor.Docs/Demos/Modal/demo/Info.razor
  site/AntBlazor.Docs/Demos/Modal/demo/Locale.razor
  site/AntBlazor.Docs/Demos/Modal/demo/Manual.razor
  site/AntBlazor.Docs/Demos/Modal/demo/confirm-promise.md
Labels: PR: reviewed-approved

#243 refactor: use httpclient factory
  components/AntDesign.csproj
  components/core/ServiceCollectionExtensions.cs
  components/icon/IconService.cs
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj
Labels: PR: unreviewed

#244 fix: fix invalid parameter "StrokeWidth"
  components/progress/Progress.razor.cs
Labels: PR: reviewed-approved

#245 fix: performance improvements for forms
  components/core/Base/AntInputComponentBase.cs
  components/form/FormItem.razor
  components/form/FormItem.razor.cs
  components/form/Validate/FormValidationMessage.cs
  components/form/Validate/FormValidationMessage.razor
  components/form/Validate/FormValidationMessage.razor.cs
  components/form/Validate/FormValidationMessageItem.razor
  components/form/Validate/FormValidationMessageItem.razor.cs
Labels: PR: reviewed-approved

#247 refactor(module: notification): change type object to OneOf
  components/notification/NotificationItem.razor
  components/notification/config/NotificationConfig.cs
Labels: PR: reviewed-approved

#252 fix(module: alert): icon and use ChildContent as description
  components/alert/Alert.razor
Labels: PR: unreviewed

#238 feat: input and inputNumber Supports generics
  components/core/Base/AntInputComponentBase.cs
  components/input-number/InputNumber.razor
  components/input-number/InputNumber.razor.cs
  components/input-number/InputNumberMath.cs
  components/input/Input.cs
  components/input/InputPassword.razor.cs
  components/input/Search.razor.cs
  components/input/TextArea.razor
  components/input/TextArea.razor.cs
  components/transfer/Transfer.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/Drawer_service.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/Formindrawer.razor
  site/AntBlazor.Docs/Demos/Form/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Input/demo/Addon.razor
  site/AntBlazor.Docs/Demos/Input/demo/Clear.razor
  site/AntBlazor.Docs/Demos/Input/demo/Generic.md
  site/AntBlazor.Docs/Demos/Input/demo/Generic.razor
  site/AntBlazor.Docs/Demos/Input/demo/Group.razor
  site/AntBlazor.Docs/Demos/Input/demo/Prefix.razor
  site/AntBlazor.Docs/Demos/InputNumber/demo/Basic.razor
  site/AntBlazor.Docs/Demos/InputNumber/demo/Decimal.razor
  site/AntBlazor.Docs/Demos/InputNumber/demo/Formatter.razor
  site/AntBlazor.Docs/Demos/InputNumber/demo/Generic.md
  site/AntBlazor.Docs/Demos/InputNumber/demo/Generic.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Vgroup.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Input.razor
  site/AntBlazor.Docs/Demos/Tag/demo/Dynamic.razor
Labels: PR: reviewed-approved

#253 Update docs path in debug build
  site/AntBlazor.Docs/AntDesign.Docs.csproj
Labels: PR: reviewed-approved

#251 feat: add autocomplete
  .gitignore
  components/auto-complete/AutoComplete.razor
  components/auto-complete/AutoComplete.razor.cs
  components/cascader/Cascader.razor
  components/cascader/Cascader.razor.cs
  components/input/Input.cs
  components/input/TextArea.razor
  components/input/TextArea.razor.cs
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Demos/AutoComplete/demo/Basic.razor
  site/AntBlazor.Docs/Demos/AutoComplete/demo/CertainCategory.razor
  site/AntBlazor.Docs/Demos/AutoComplete/demo/Custom.razor
  site/AntBlazor.Docs/Demos/AutoComplete/demo/NonCaseSensitive.razor
  site/AntBlazor.Docs/Demos/AutoComplete/demo/Options.razor
  site/AntBlazor.Docs/Demos/AutoComplete/demo/UncertainCategory.razor
  site/AntBlazor.Docs/Demos/AutoComplete/demo/basic.md
  site/AntBlazor.Docs/Demos/AutoComplete/demo/certain-category.md
  site/AntBlazor.Docs/Demos/AutoComplete/demo/custom.md
  site/AntBlazor.Docs/Demos/AutoComplete/demo/non-case-sensitive.md
  site/AntBlazor.Docs/Demos/AutoComplete/demo/options.md
  site/AntBlazor.Docs/Demos/AutoComplete/demo/uncertain-category.md
  site/AntBlazor.Docs/Demos/AutoComplete/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/AutoComplete/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Cascader/demo/Size.razor
  site/AntBlazor.Docs/Demos/Input/demo/Search_.razor
  site/AntBlazor.Docs/Demos/Select/demo/CustomDropdownMenu.razor
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#260 fix: icon issues
  components/avatar/Avatar.razor
  components/cascader/Cascader.razor
  components/drawer/Drawer.razor
  components/icon/Icon.razor
  components/input/Search.razor.cs
  components/typography/Text.cs
  site/AntBlazor.Docs/Demos/Input/demo/Addon.razor
  site/AntBlazor.Docs/Demos/Input/demo/Clear.razor
  site/AntBlazor.Docs/Demos/Layout/demo/FixedSider.razor
Labels: PR: unreviewed

#258 feat: add list resposive
  components/list/AntList.razor
  components/list/AntList.razor.cs
  components/list/AntListItem.razor
  components/list/AntListItem.razor.cs
  site/AntBlazor.Docs/Demos/List/demo/Grid.razor
  site/AntBlazor.Docs/Demos/List/demo/Loadmore.razor
  site/AntBlazor.Docs/Demos/List/demo/Resposive.razor
  site/AntBlazor.Docs/Demos/List/demo/Simple.razor
  site/AntBlazor.Docs/Demos/List/demo/Vertical.razor
Labels: PR: reviewed-approved

#259 feat: clearall method to clear all items in the list
  components/select/Select.razor.cs
  site/AntBlazor.Docs/Demos/Select/demo/ClearValues.razor
  site/AntBlazor.Docs/Demos/Select/demo/clear-values.md
Labels: PR: reviewed-approved

#267 chore: add release ci
  .github/workflows/release.yml
Labels: PR: unreviewed

#263 feat:add Popover
  components/popover/Popover.razor
  components/popover/Popover.razor.cs
  site/AntBlazor.Docs/Demos/Popover/demo/ArrowPointAtCenter.razor
  site/AntBlazor.Docs/Demos/Popover/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Popover/demo/Control.razor
  site/AntBlazor.Docs/Demos/Popover/demo/HoverWithClick.razor
  site/AntBlazor.Docs/Demos/Popover/demo/Placement.razor
  site/AntBlazor.Docs/Demos/Popover/demo/TriggerType.razor
  site/AntBlazor.Docs/Demos/Popover/demo/arrow-point-at-center.md
  site/AntBlazor.Docs/Demos/Popover/demo/basic.md
  site/AntBlazor.Docs/Demos/Popover/demo/control.md
  site/AntBlazor.Docs/Demos/Popover/demo/hover-with-click.md
  site/AntBlazor.Docs/Demos/Popover/demo/placement.md
  site/AntBlazor.Docs/Demos/Popover/demo/triggerType.md
  site/AntBlazor.Docs/Demos/Popover/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Popover/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#265 fix(module: tooltip): arrow does not appear
  components/tooltip/Tooltip.razor
Labels: PR: reviewed-approved

#262 docs: fix InputNumber demo
  components/input-number/InputNumber.razor.cs
  components/input/Input.cs
  site/AntBlazor.Docs/Demos/Input/demo/Clear.razor
Labels: PR: reviewed-approved

#272 chore: fix static file compile for release ci
  .github/workflows/release.yml
Labels: PR: unreviewed

#274 fix(module: icon): click issue caused by StopPropagation
  components/cascader/Cascader.razor
  components/icon/Icon.razor
  components/icon/Icon.razor.cs
  site/AntBlazor.Docs/Demos/Drawer/demo/Placement.razor
Labels: PR: unreviewed

#269 feat: add size, bordered option and footer/header to table component
  components/table/Table.razor
  components/table/Table.razor.cs
  components/table/TableSize.cs
  site/AntBlazor.Docs/Demos/Table/demo/Bordered.razor
  site/AntBlazor.Docs/Demos/Table/demo/Size.razor
  site/AntBlazor.Docs/Demos/Table/demo/bordered.md
  site/AntBlazor.Docs/Demos/Table/demo/size.md
Labels: PR: reviewed-approved

#246 feat: radio supports generics
  components/calendar/Calendar.razor.cs
  components/calendar/internal/CalendarHeader.razor
  components/radio/Radio.razor
  components/radio/Radio.razor.cs
  components/radio/RadioGroup.razor
  components/radio/RadioGroup.razor.cs
  components/radio/style/entry.less
  components/table/Selection.razor
  components/table/Selection.razor.cs
  site/AntBlazor.Docs/Demos/Button/demo/Size.razor
  site/AntBlazor.Docs/Demos/Calendar/demo/CustomizeHeader.razor
  site/AntBlazor.Docs/Demos/Descriptions/demo/CustomSize.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/Placement.razor
  site/AntBlazor.Docs/Demos/Form/demo/Size.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Button_.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Disable.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Generic.md
  site/AntBlazor.Docs/Demos/Radio/demo/Generic.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Group.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Name.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Optional.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Size.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Style.razor
  site/AntBlazor.Docs/Demos/Radio/demo/Vgroup.razor
  site/AntBlazor.Docs/Demos/Select/demo/Size.razor
  site/AntBlazor.Docs/Demos/Skeleton/demo/Element.razor
  site/AntBlazor.Docs/Demos/Space/demo/Size.razor
  site/AntBlazor.Docs/Demos/Table/demo/RowSelection_.razor
  site/AntBlazor.Docs/Demos/Timeline/demo/Label.razor
Labels: PR: reviewed-approved

#278 feat:Tree
  components/tree/Tree.razor
  components/tree/Tree.razor.cs
  components/tree/TreeNode.cs
  site/AntBlazor.Docs/Demos/Tree/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Tree/demo/Line.razor
Labels: PR: reviewed-approved

#279 feat: drawer support return value
  components/drawer/Drawer.razor
  components/drawer/Drawer.razor.cs
  components/drawer/DrawerContainer.razor
  components/drawer/DrawerContainer.razor.cs
  components/drawer/DrawerRef.cs
  components/drawer/DrawerService.cs
  components/drawer/DrawerTemplate.razor.cs
  components/drawer/config/DrawerConfig.cs
  site/AntBlazor.Docs/Demos/Drawer/ComponentTemplate.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/Drawer_service.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/drawer_service.md
  site/AntBlazor.Docs/Demos/Drawer/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Drawer/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#80 feat:add AntComment
  components/comment/Comment.razor
  components/comment/Comment.razor.cs
  components/core/Helpers/MomentHelper.cs
  site/AntBlazor.Docs/Demos/Comment/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Comment/demo/Editor.razor
  site/AntBlazor.Docs/Demos/Comment/demo/List.razor
  site/AntBlazor.Docs/Demos/Comment/demo/Nested.razor
  site/AntBlazor.Docs/Demos/Comment/demo/basic.md
  site/AntBlazor.Docs/Demos/Comment/demo/editor.md
  site/AntBlazor.Docs/Demos/Comment/demo/list.md
  site/AntBlazor.Docs/Demos/Comment/demo/nested.md
  site/AntBlazor.Docs/Demos/Comment/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Comment/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#281 Add component anchor
  components/anchor/Anchor.razor
  components/anchor/Anchor.razor.cs
  components/anchor/AnchorLink.razor
  components/anchor/AnchorLink.razor.cs
  components/anchor/IAnchor.cs
  site/AntBlazor.Docs/Demos/Anchor/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Anchor/demo/CustomizeHighlight.razor
  site/AntBlazor.Docs/Demos/Anchor/demo/OnChange.razor
  site/AntBlazor.Docs/Demos/Anchor/demo/OnClick.razor
  site/AntBlazor.Docs/Demos/Anchor/demo/Static.razor
  site/AntBlazor.Docs/Demos/Anchor/demo/TargetOffset.razor
  site/AntBlazor.Docs/Demos/Anchor/demo/basic.md
  site/AntBlazor.Docs/Demos/Anchor/demo/customizeHighlight.md
  site/AntBlazor.Docs/Demos/Anchor/demo/onChange.md
  site/AntBlazor.Docs/Demos/Anchor/demo/onClick.md
  site/AntBlazor.Docs/Demos/Anchor/demo/static.md
  site/AntBlazor.Docs/Demos/Anchor/demo/targetOffset.md
  site/AntBlazor.Docs/Demos/Anchor/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Anchor/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/Routing/ConventionRouter.cs
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#284 refactor(module: form): optimize performance
  components/form/Form.razor.cs
  components/form/FormItem.razor.cs
  components/form/Validate/FormValidationMessage.razor.cs
  components/input/Input.cs
  components/input/TextArea.razor.cs
Labels: PR: unreviewed

#285 refactor(module: col): optimize performance
  components/grid/Col.razor.cs
Labels: PR: reviewed-approved

#276 feat: add upload component
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/space/UploadInfo.cs
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
  components/upload/UploadFileItem.cs
  components/upload/UploadState.cs
  site/AntBlazor.Docs/Demos/Upload/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Upload/demo/DefaultFileList.razor
  site/AntBlazor.Docs/Demos/Upload/demo/basic.md
  site/AntBlazor.Docs/Demos/Upload/demo/defaultFileList.md
  site/AntBlazor.Docs/Demos/Upload/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Upload/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#288 feat: add popconfirm
  components/popconfirm/Popconfirm.razor
  components/popconfirm/Popconfirm.razor.cs
  site/AntBlazor.Docs/Demos/Popconfirm/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Popconfirm/demo/DynamicTrigger.razor
  site/AntBlazor.Docs/Demos/Popconfirm/demo/Icon.razor
  site/AntBlazor.Docs/Demos/Popconfirm/demo/Locale.razor
  site/AntBlazor.Docs/Demos/Popconfirm/demo/Placement.razor
  site/AntBlazor.Docs/Demos/Popconfirm/demo/basic.md
  site/AntBlazor.Docs/Demos/Popconfirm/demo/dynamic-trigger.md
  site/AntBlazor.Docs/Demos/Popconfirm/demo/icon.md
  site/AntBlazor.Docs/Demos/Popconfirm/demo/locale.md
  site/AntBlazor.Docs/Demos/Popconfirm/demo/placement.md
  site/AntBlazor.Docs/Demos/Popconfirm/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Popconfirm/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved
