Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2020-03, with the labels that each got.

#26 Add Alert Component
  components/AntBlazor.xml
  components/alert/AntAlert.razor
  components/alert/AntAlertBase.cs
  components/alert/AntAlertType.cs
  site/AntBlazor.Docs/Pages/Alert.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed

#28 Feature/drawer
  components/core/EnumerableExtensions.cs
  components/core/Helpers/StyleHelper.cs
  components/drawer/AntDrawer.razor
  components/drawer/AntDrawerBase.cs
  components/drawer/DrawerRef.cs
  site/AntBlazor.Docs/Pages/Drawer.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed

#27 [Finished] Add Badge
  components/AntBlazor.xml
  components/badge/AntBadge.razor
  components/badge/AntBadgeBase.cs
  components/badge/AntBadgeColor.cs
  components/badge/AntBadgeStatus.cs
  site/AntBlazor.Docs/Pages/Badge.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed

#33 add component input
  components/input/AntInput.cs
  components/input/AntInputGroup.razor
  components/input/AntInputGroup.razor.cs
  components/input/AntInputPassword.razor.cs
  components/input/AntInputSize.cs
  components/input/AntSearch.razor.cs
  components/input/AntTextArea.razor
  components/input/AntTextArea.razor.cs
  site/AntBlazor.Docs/Pages/Input.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#32 Add EditorConfig for naming conventions
  .editorconfig
  AntBlazor.sln
  components/AntBlazor.csproj
Labels: PR: reviewed-approved

#36 feat: add component radio
  components/AntBlazor.csproj
  components/core/Base/AntComponentBase.cs
  components/core/Base/AntDomComponentBase.cs
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/radio/AntRadio.razor
  components/radio/AntRadioBase.cs
  components/radio/AntRadioGroup.razor
  site/AntBlazor.Docs/Pages/Radio.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed

#25 Translate README.md to English
  README.md
  docs/introduce.md
Labels: PR: reviewed-approved

#40 docs: remove httpclient extension methods
  components/core/HttpClientExtensions.cs
  site/AntBlazor.Docs.ClientApp/AntBlazor.Docs.ClientApp.csproj
  site/AntBlazor.Docs/AntBlazor.Docs.csproj
  site/AntBlazor.Docs/Shared/MainLayout.razor
Labels: PR: unreviewed

#41 doc: Update English README, add Chinese readme back
  README-zh_CN.md
  README.md
Labels: PR: reviewed-approved

#44 Packaging License within the nupkg
  components/AntBlazor.csproj
Labels: PR: reviewed-approved

#45 feat: add component inputnumber
  components/input-number/AntInputNumber.razor
  components/input-number/AntInputNumber.razor.cs
  components/input/AntInput.cs
  components/input/AntInputPassword.razor.cs
  site/AntBlazor.Docs/Pages/Input.razor
  site/AntBlazor.Docs/Pages/InputNumber.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#50 Fix nuget icon
  components/AntBlazor.csproj
  components/logo.png
Labels: PR: reviewed-approved

#48 chore: add pr preveiw script
  .github/workflows/pr-checks.yml
Labels: PR: unreviewed

#46 feat: Add Step and Steps
  components/AntBlazor.xml
  components/steps/AntStep.razor
  components/steps/AntStepBase.cs
  components/steps/AntSteps.razor
  components/steps/AntStepsBase.cs
  site/AntBlazor.Docs/Pages/Step.razor
  site/AntBlazor.Docs/style/index.less
  site/AntBlazor.Docs/style/navigation.less
  site/AntBlazor.Docs/styles.less
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: reviewed-approved

#49 fix: disable key issue of inputnumber attributes
  components/input-number/AntInputNumber.razor.cs
Labels: PR: reviewed-approved

#51 Fix compile csproj
  components/AntBlazor.csproj
Labels: PR: unreviewed

#54 refactor: update to preview 3
  .github/workflows/gh-pages.yml
  .github/workflows/pr-checks.yml
  .github/workflows/pr-preview.yml
  .gitignore
  AntBlazor.sln
  README-zh_CN.md
  README.md
  components/AntBlazor.csproj
  components/AntBlazor.xml
  package.json
  site/AntBlazor.Docs.ClientApp/Properties/launchSettings.json
  site/AntBlazor.Docs.Server/AntBlazor.Docs.Server.csproj
  site/AntBlazor.Docs.Server/Pages/_Host.cshtml
  site/AntBlazor.Docs.Server/Program.cs
  site/AntBlazor.Docs.Server/Properties/launchSettings.json
  site/AntBlazor.Docs.Server/Startup.cs
  site/AntBlazor.Docs.Server/_Imports.razor
  site/AntBlazor.Docs.Server/appsettings.Development.json
  site/AntBlazor.Docs.Server/appsettings.json
  site/AntBlazor.Docs.Server/wwwroot/logo.png
  site/AntBlazor.Docs.Wasm/AntBlazor.Docs.Wasm.csproj
  site/AntBlazor.Docs.Wasm/Program.cs
  site/AntBlazor.Docs.Wasm/Properties/launchSettings.json
  site/AntBlazor.Docs.Wasm/_Imports.razor
  site/AntBlazor.Docs.Wasm/wwwroot/index.html
  site/AntBlazor.Docs.Wasm/wwwroot/logo.png
  site/AntBlazor.Docs.Wasm/wwwroot/manifest.json
  site/AntBlazor.Docs.Wasm/wwwroot/service-worker.js
  site/AntBlazor.Docs.Wasm/wwwroot/service-worker.published.js
  site/AntBlazor.Docs.WasmHost/AntBlazor.Docs.WasmHost.csproj
  site/AntBlazor.Docs.WasmHost/Program.cs
  site/AntBlazor.Docs.WasmHost/Properties/launchSettings.json
  site/AntBlazor.Docs.WasmHost/Startup.cs
  site/AntBlazor.Docs.WasmHost/appsettings.Development.json
  site/AntBlazor.Docs.WasmHost/appsettings.json
  site/AntBlazor.Docs/AntBlazor.Docs.csproj
  site/AntBlazor.Docs/App.razor
  site/AntBlazor.Docs/Routing/ConventionRouter.cs
  site/AntBlazor.Docs/Routing/RouteManager.cs
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/_Imports.razor
Labels: PR: unreviewed

#55 chore: add vscode debug setting for wasm
  .vscode/launch.json
  .vscode/tasks.json
Labels: PR: unreviewed

#56 docs: fix dingtalk badge
  README-zh_CN.md
  README.md
Labels: PR: unreviewed

#58 chore: sync ant-design v4.1.0
  components/alert/style/index.less
  components/auto-complete/style/index.less
  components/badge/style/rtl.less
  components/button/style/index.less
  components/button/style/mixin.less
  components/button/style/rtl.less
  components/calendar/style/index.less
  components/card/style/index.less
  components/card/style/size.less
  components/checkbox/style/mixin.less
  components/comment/style/index.less
  components/date-picker/style/index.less
  components/date-picker/style/panel.less
  components/descriptions/style/index.less
  components/drawer/style/drawer.less
  components/form/style/index.less
  components/input/style/affix.less
  components/input/style/allow-clear.less
  components/input/style/rtl.less
  components/list/style/bordered.less
  components/list/style/index.less
  components/menu/style/index.less
  components/modal/style/confirm.less
  components/modal/style/modal.less
  components/page-header/style/index.less
  components/pagination/style/index.less
  components/popover/style/index.less
  components/progress/style/rtl.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/select/style/rtl.less
  components/select/style/single.less
  components/skeleton/style/index.less
  components/space/style/index.less
  components/statistic/style/index.less
  components/steps/style/custom-icon.less
  components/steps/style/index.less
  components/steps/style/progress-dot.less
  components/steps/style/rtl.less
  components/steps/style/small.less
  components/steps/style/vertical.less
  components/style/compact.less
  components/style/core/base.less
  components/style/themes/compact.less
  components/style/themes/default.less
  components/table/style/index.less
  components/table/style/rtl.less
  components/table/style/size.less
  components/tabs/style/card-style.less
  components/tabs/style/index.less
  components/tabs/style/rtl.less
  components/tag/style/index.less
  components/timeline/style/index.less
  components/timeline/style/rtl.less
  components/transfer/style/index.less
  components/upload/style/index.less
  components/upload/style/rtl.less
Labels: PR: unreviewed

#59 docs: 🎉add support for i18n
  site/AntBlazor.Docs/AntBlazor.Docs.csproj
  site/AntBlazor.Docs/Localization/ILanguageService.cs
  site/AntBlazor.Docs/Localization/InAssemblyLanguageService.cs
  site/AntBlazor.Docs/Localization/Resources.cs
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/ServiceCollectionExtensions.cs
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/NavMenu.razor
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed, documentation, enhancement

#61 fix AntTextArea autosize not working correctly
  components/input/AntTextArea.razor
  components/input/AntTextArea.razor.cs
  site/AntBlazor.Docs/Pages/Input.razor
Labels: PR: unreviewed
