Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2020-11, with the labels that each got.

#750 fix(module: confirm): cannot remove Dialog from the dom tree when confim is hidden (#749)
  components/modal/ConfirmDialog.razor
  components/modal/ConfirmDialog.razor.cs
Labels: PR: reviewed-approved

#751 fix(module: input): value wouldn't change while input blur in composi…
  components/form/Validate/FormValidationMessageItem.razor
  components/input/Input.cs
Labels: PR: unreviewed

#743 fix(module: overlay) don't close overlay if is controlled via visable param fixes #742
  components/core/Component/overlay/OverlayTrigger.razor.cs
Labels: PR: partially-approved

#752 fix(module: input): doesn't show the loading icon on search was press…
  components/input/Input.cs
  components/input/Search.razor.cs
  site/AntBlazor.Docs/Demos/Components/Input/demo/Search_.razor
Labels: PR: unreviewed

#741 refactor autocomplate
  components/auto-complete/AutoComplete.razor
  components/auto-complete/AutoComplete.razor.cs
  components/auto-complete/AutoCompleteOption.razor.cs
  components/auto-complete/IAutoCompleteRef.cs
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/CertainCategory.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Custom.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/CustomFilter.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Format.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/NonCaseSensitive.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/ObjectValue.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Options.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Performance.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/PopupContainer.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/Property.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/UncertainCategory.razor
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/custom-filter.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/format.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/non-case-sensitive.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/options.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/demo/uncertain-category.md
Labels: PR: unreviewed, don't merge

#756 docs: update links
  README-zh_CN.md
  README.md
  docs/getting-started.en-US.md
  docs/getting-started.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: unreviewed

#689 fix(module: table): header col mistake
  .github/workflows/pull-request.yml
  components/table/ActionColumn.razor
  components/table/Column.razor
  components/table/Selection.razor
  tests/$Recorded/AntDesign.Tests.Table.TableTestsSet_colspan_and_rowspan.html
Labels: PR: unreviewed

#760 fix(module: steps) - Visual fix for issue #759
  components/steps/Step.razor
Labels: PR: reviewed-approved

#767 fix(module: table): pagination didn't change while pageindex was changed
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Blazor.razor
  site/AntDesign.Docs.Server/Pages/_Host.cshtml
Labels: PR: reviewed-approved

#768 feat(module: table): support for expand row
  components/AntDesign.csproj
  components/table/Table.razor
  components/table/Table.razor.cs
  components/table/TableModels/RowData.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Expand.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/expand.md
Labels: PR: unreviewed

#771 feat(module: table): support for tree data
  components/core/CssSizeLength.cs
  components/table/ActionColumn.razor
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/ColumnBase.cs
  components/table/IColumn.cs
  components/table/ITable.cs
  components/table/Selection.razor
  components/table/Selection.razor.cs
  components/table/Table.razor
  components/table/Table.razor.RowData.cs
  components/table/Table.razor.Selection.cs
  components/table/Table.razor.cs
  components/table/TableModels/RowData.cs
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Demos/Components/Table/demo/Expand.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/TreeData.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/tree-data.md
  tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsSet_colspan_and_rowspan.html
Labels: PR: unreviewed

#776 fix(module: progress): single stroke color
  components/progress/Progress.razor
  components/progress/Progress.razor.cs
  site/AntBlazor.Docs/Demos/Components/Progress/demo/GradientLine.razor
Labels: PR: unreviewed

#779 fix(module: menu): mark state has changed after menu items were deselect
  components/menu/Menu.razor.cs
  components/menu/MenuLink.cs
Labels: PR: unreviewed

#766 fix: the issue #762 switch loading icon has a little shift
  components/icon/Icon.razor.cs
  components/icon/IconFont.razor.cs
  components/icon/IconService.cs
  tests/$Recorded/AntDesign.Tests.Table.TableTestsCan_render_after_changes_to_the_dataSource.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_a_table_with_two_rows.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsRenders_an_empty_table.html
  tests/$Recorded/AntDesign.Tests.Table.TableTestsSet_colspan_and_rowspan.html
  tests/table/TableTests.cs
Labels: PR: reviewed-approved

#744 Fix-Absolute positioning before doesn't take the scroll position into acc…
  components/core/JsInterop/interop.ts
Labels: PR: partially-approved

#784 fix(module: menu): menulink active incorrectly
  components/menu/MenuLink.cs
Labels: PR: unreviewed

#783 fix(module: AutoComplete): overlay couldn't close
  components/auto-complete/AutoComplete.razor
  components/auto-complete/AutoComplete.razor.cs
Labels: PR: partially-approved

#758 chore: add .NET 5 target framework to all projects
  .github/workflows/gh-pages.yml
  .github/workflows/pr-preview.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  README-zh_CN.md
  README.md
  components/AntDesign.csproj
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Pages/Components.razor
  site/AntBlazor.Docs/Pages/Docs.razor
  site/AntBlazor.Docs/Pages/Overview.razor
  site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
  site/AntDesign.Docs.Build.CLI/Properties/launchSettings.json
  site/AntDesign.Docs.Server/AntDesign.Docs.Server.csproj
  site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
  site/AntDesign.Docs.WasmHost/AntDesign.Docs.WasmHost.csproj
  tests/AntDesign.Tests.csproj
Labels: PR: reviewed-approved

#770 chore: sync ant-design v4.8.2
  components/anchor/style/rtl.less
  components/avatar/style/group.less
  components/avatar/style/rtl.less
  components/badge/style/index.less
  components/badge/style/rtl.less
  components/breadcrumb/style/rtl.less
  components/collapse/style/index.less
  components/date-picker/style/panel.less
  components/descriptions/style/index.less
  components/form/style/status.less
  components/grid/style/index.less
  components/menu/style/index.less
  components/pagination/style/index.less
  components/pagination/style/rtl.less
  components/rate/style/index.less
  components/rate/style/rtl.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/select/style/single.less
  components/spin/style/rtl.less
  components/statistic/style/rtl.less
  components/steps/style/custom-icon.less
  components/steps/style/index.less
  components/steps/style/progress-dot.less
  components/steps/style/progress.less
  components/steps/style/vertical.less
  components/style/core/motion.less
  components/tabs/style/index.less
  components/tabs/style/position.less
  components/tree/style/mixin.less
  components/tree/style/rtl.less
  components/typography/style/index.less
Labels: PR: unreviewed

#789 chore: sync ant-design v4.8.3
  components/alert/style/rtl.less
  components/avatar/style/index.less
  components/button/style/rtl.less
  components/calendar/style/rtl.less
  components/card/style/size.less
  components/date-picker/style/index.less
  components/date-picker/style/panel.less
  components/date-picker/style/rtl.less
  components/dropdown/style/index.less
  components/dropdown/style/rtl.less
  components/menu/style/index.less
  components/menu/style/rtl.less
  components/radio/style/index.less
  components/select/style/multiple.less
  components/select/style/rtl.less
  components/style/themes/default.less
  components/typography/style/index.less
Labels: PR: unreviewed

#787 feat(modul: menu) - MenuItem Title
  components/menu/Menu.razor.cs
  components/menu/MenuItem.razor
  components/menu/MenuItem.razor.cs
  components/menu/SubMenu.razor.cs
  site/AntBlazor.Docs/Demos/Components/Menu/demo/SiderCurrent2.razor
  site/AntBlazor.Docs/Demos/Components/Menu/demo/sider-current2.md
  site/AntBlazor.Docs/Demos/Components/Menu/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Menu/doc/index.zh-CN.md
Labels: PR: unreviewed

#792 chore: sync ant-design v4.8.4
  components/button/style/index.less
  components/form/style/status.less
Labels: PR: unreviewed

#791 fix : badgeribbon with preset color
  components/badge/BadgeRibbon.razor
  site/AntBlazor.Docs/Demos/Components/Badge/demo/Ribbon.razor
  tests/badge/RibbonTests.cs
Labels: PR: reviewed-approved

#798 fix(module: datepicker): bind-value is useless without form
  components/date-picker/DatePicker.Razor.cs
Labels: PR: reviewed-approved

#799 fix(module: modal): dom cannot be destroyed when the page changed on DestroyOnClose is false
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/modal/Modal.razor.cs
  components/modal/ModalServiceForModal.cs
Labels: PR: reviewed-approved

#785 Add OnRowClick to Table component
  components/table/Table.razor
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Basic.razor
Labels: PR: reviewed-approved

#805 fix(modul: affix) code cleaning, doc update
  components/affix/Affix.razor
  components/affix/Affix.razor.cs
  site/AntBlazor.Docs/Demos/Components/Affix/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Affix/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#804 Chart doc
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Axis.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/ChangeDataAtRuntime.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/ChangeDataAtRuntime.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/DarkMode.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Guideline.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Interop.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Label.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Legend.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/SetPadding.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/SetState.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/TitleAndDescription.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/Tooltip_.razor
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/axis.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/dark-mode.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/guideline.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/interop.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/label.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/legend.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/set-padding.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/set-state.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/title-and-description.md
  site/AntBlazor.Docs/Demos/Charts/GeneralConfiguration/demo/tooltip.md
  site/AntBlazor.Docs/Demos/Charts/Pie/demo/Donut_.razor
  site/AntBlazor.Docs/Demos/Charts/Pie/demo/Pie_.razor
  site/AntBlazor.Docs/Demos/Charts/Pie/demo/donut.md
  site/AntBlazor.Docs/Demos/Charts/Pie/demo/pie.md
Labels: PR: reviewed-approved

#796 Origin/doc/api
  site/AntBlazor.Docs/Demos/Components/Affix/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Affix/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Components/Alert/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Alert/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Components/Anchor/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Anchor/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/AutoComplete/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Components/Avatar/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Avatar/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#806 fix(module: alert): code cleaning, doc update
  components/alert/Alert.razor.cs
  site/AntBlazor.Docs/Demos/Components/Alert/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Alert/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#808 fix(module: avatar): code cleaning, doc update
  components/avatar/Avatar.razor.cs
  site/AntBlazor.Docs/Demos/Components/Avatar/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Avatar/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#708 PR for issue #704: Error: Cannot provide a value for property 'NotificationService' on type 'AntDesign.Notification'
  README.md
Labels: PR: reviewed-approved

#811 docs: add template badges
  README-zh_CN.md
  README.md
Labels: PR: unreviewed

#809 fix(module: modal): throw error when using ModalService if not set ModalOptions.AfterClose (#807)
  components/modal/ModalContainer.razor
  components/modal/config/ModalOptions.cs
Labels: PR: reviewed-approved

#815 feat(module: dropdown): ContextMenu support offsetX/offsetY in net5
  components/core/Component/overlay/OverlayTrigger.razor.cs
  site/AntBlazor.Docs/Demos/Components/Dropdown/demo/ContextMenu.razor
  site/AntBlazor.Docs/Demos/Components/Dropdown/demo/context-menu.md
Labels: PR: reviewed-approved

#821 fix(module: calendar): method or operation is not implemented
  components/calendar/Calendar.razor.cs
Labels: PR: reviewed-approved

#820 fix: datepicker's ExtraFooter bug in month mode
  components/date-picker/internal/DatePickerMonthPanel.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/ExtraFooter.razor
Labels: PR: reviewed-approved

#819 docs(module: drawer): add dropdown in drawer demo
  site/AntBlazor.Docs/Demos/Components/Drawer/demo/DropdownInDrawer.razor
  site/AntBlazor.Docs/Demos/Components/Drawer/demo/dropdown-in-drawer.md
Labels: PR: merged

#822 fix(module: tabs): stops tabs buttons from flickering when icons are …
  components/tabs/TabPane.cs
  components/tabs/TabPane.razor
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
  site/AntBlazor.Docs/Demos/Components/Tabs/demo/Slide.razor
  tests/tabs/TabsTests.cs
Labels: PR: reviewed-approved

#803 feat (module:datepicker) Add FirstDayOfWeek option and german localization
  components/calendar/Calendar.razor.cs
  components/calendar/internal/CalendarHeader.razor
  components/calendar/internal/CalendarPanelChooser.razor
  components/date-picker/DatePicker.Razor.cs
  components/date-picker/IDatePicker.cs
  components/date-picker/RangePicker.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerDatePanel.razor
  components/date-picker/internal/DatePickerDatetimePanel.razor
  components/date-picker/internal/DatePickerFooter.razor
  components/date-picker/internal/DatePickerHeader.razor
  components/date-picker/internal/DatePickerLocaleHelper.cs
  components/date-picker/internal/DatePickerMonthPanel.razor
  components/date-picker/internal/DatePickerPanelBase.cs
  components/date-picker/internal/DatePickerPanelChooser.razor
  components/date-picker/internal/DatePickerQuarterPanel.razor
  components/date-picker/internal/DatePickerTemplate.razor.cs
  components/date-picker/internal/DatePickerYearPanel.razor
  components/date-picker/internal/DayOfWeekHelper.cs
  components/date-picker/locale/DatePickerLocale.cs
  components/date-picker/locale/IDateLocale.cs
  components/date-picker/types/DatePickerPlaceholder.cs
  components/locale-provider/Locale.cs
  components/locale-provider/LocaleProvider.cs
  components/locales/de-DE.json
  components/locales/en-GB.json
  components/locales/en-US.json
  components/locales/zh-CN.json
  components/locales/zh-TW.json
  components/time-picker/TimePickerLocale.cs
  site/AntBlazor.Docs/Demos/Components/Calendar/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Format.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Globalization.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/globalization.md
  site/AntBlazor.Docs/Demos/Components/DatePicker/doc/index.en-US.md
  site/AntBlazor.Docs/Localization/InAssemblyLanguageService.cs
Labels: PR: reviewed-approved

#830 feat: simplify ColLayout
  components/form/Form.razor.cs
  components/form/FormItem.razor.cs
  site/AntBlazor.Docs/Demos/Components/Form/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/ColLayout.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/ComplexFormControl.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/ControlHooks.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/CustomizedFormControls.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/FormContext.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/IsModified.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/Loading.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/Size.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/colLayout.md
Labels: PR: reviewed-approved

#836 feat(module: select): add a simple select with string value
  components/select/Select.razor.cs
  components/select/SelectOption.razor.cs
  components/select/SimpleSelect.cs
  components/select/internal/SelectContent.razor
  components/select/internal/SelectContent.razor.cs
  site/AntBlazor.Docs/Demos/Components/Select/demo/SimpleSelectDemo.razor
  site/AntBlazor.Docs/Demos/Components/Select/demo/simple-select.md
Labels: PR: unreviewed

#837 docs: cname to antblazor.com
  .github/workflows/gh-pages.yml
Labels: PR: unreviewed

#838 fix(module: locale-provider): change SetLocale to public method
  components/locale-provider/LocaleProvider.cs
Labels: PR: reviewed-approved

#839 refactor(module: tabs): separate the TabPane component
  components/tabs/TabPane.cs
  components/tabs/TabPane.razor
  components/tabs/TabPane.razor.cs
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
  site/AntBlazor.Docs/Demos/Components/Tabs/demo/CustomAddTrigger.razor
  site/AntBlazor.Docs/Demos/Components/Tabs/demo/EditableCard.razor
  site/AntBlazor.Docs/Shared/CodeBox.razor
  site/AntBlazor.Docs/Utils/IsExternalInit.cs
  tests/tabs/TabsTests.cs
Labels: PR: unreviewed
