Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2020-12, with the labels that each got.

#842 chore: sync ant-design v4.9.0
  components/alert/style/index.less
  components/carousel/style/index.less
  components/collapse/style/index.less
  components/date-picker/style/index.less
  components/date-picker/style/panel.less
  components/date-picker/style/rtl.less
  components/descriptions/style/rtl.less
  components/image/style/index.less
  components/input/style/search-input.less
  components/menu/style/dark.less
  components/menu/style/index.less
  components/menu/style/rtl.less
  components/modal/style/confirm.less
  components/modal/style/modal.less
  components/skeleton/style/index.less
  components/steps/style/rtl.less
  components/style/mixins/modal-mask.less
  components/style/themes/compact.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/switch/style/index.less
  components/table/style/index.less
  components/table/style/rtl.less
  components/tree/style/mixin.less
  components/tree/style/rtl.less
  components/upload/style/index.less
Labels: PR: unreviewed

#841 feat(module: form): make the form validator customizable
  components/form/Form.razor
  components/form/Form.razor.cs
  site/AntBlazor.Docs/Demos/Components/Form/demo/CustomizedFormValidator.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/customized-form-validator.md
  site/AntBlazor.Docs/Demos/Components/Form/objects/CustomValidator.cs
Labels: PR: reviewed-approved

#847 Fix the behavior when Overlay is disabled. Remove clear icon when Select is disabled
  components/core/Component/overlay/Overlay.razor.cs
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/select/internal/SelectContent.razor
Labels: PR: reviewed-approved

#848 fix(module: tabs): ink malposition and card tabs didn't active
  components/tabs/TabPane.razor
  components/tabs/TabPane.razor.cs
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
Labels: PR: unreviewed

#852 fix: submenu couldn't auto close
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/menu/SubMenu.razor
Labels: PR: reviewed-approved

#857 feat(module: table): add TitleTemplate for column title
  components/table/ActionColumn.razor
  components/table/Column.razor
  components/table/ColumnBase.cs
  components/table/Table.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/Basic.razor
Labels: PR: reviewed-approved

#850 refactor(module: input-number): support all numeric types
  components/input-number/InputNumber.razor.cs
  components/input-number/InputNumberMath.cs
  site/AntBlazor.Docs/Demos/Components/InputNumber/demo/Generic.razor
  site/AntBlazor.Docs/Demos/Components/InputNumber/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/InputNumber/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#866 fix: Slider edge lock, range initial values, both range value change
  components/slider/Slider.razor
  components/slider/Slider.razor.cs
Labels: PR: reviewed-approved

#879 Expose sider togglecollapse
  components/layout/Sider.razor.cs
Labels: PR: reviewed-approved

#880 修改Input控件添加MaxLength属性报错问题
  components/input/Input.cs
Labels: PR: unreviewed

#881 Make description element visible if passed in ChildContent
  components/alert/Alert.razor.cs
  site/AntBlazor.Docs/Demos/Components/Alert/demo/Description.razor
Labels: PR: reviewed-approved

#887 fix(module: modal): the Title property is default to `string.Empty` in …
  components/modal/config/ModalOptions.cs
Labels: PR: unreviewed

#892 fix(module: collapse): missing style and can not collapse
  components/collapse/Panel.razor
  components/collapse/Panel.razor.cs
Labels: PR: unreviewed

#893 docs: update the link for BootstrapBlazor
  site/AntBlazor.Docs/Shared/MainFooter.razor
Labels: PR: reviewed-approved

#896 fix(module: statistic): remove the redundant 0
  components/statistic/Statistic.razor.cs
Labels: PR: unreviewed

#900 fix(module: tabs): style change dynamically
  components/tabs/Tabs.razor.cs
Labels: PR: unreviewed

#901 docs: make the site menu responsive
  components/grid/Row.razor.cs
  components/grid/RowCol.cs
  site/AntBlazor.Docs/Pages/Index.razor
  site/AntBlazor.Docs/Pages/Index.razor.cs
  site/AntBlazor.Docs/Shared/HeaderMenu.razor
  site/AntBlazor.Docs/Shared/HeaderMenu.razor.cs
  site/AntBlazor.Docs/Shared/MainHeader.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
  site/AntBlazor.Docs/Shared/NavMenu.razor
  site/AntBlazor.Docs/style/drawer.less
  site/AntBlazor.Docs/style/index.less
Labels: PR: unreviewed

#905 'Upload' component change to use responseCode not a "error" string when upload failed
  components/upload/Upload.razor.cs
Labels: PR: reviewed-approved

#899 Implement optional key debouncing
  components/input/Input.cs
Labels: PR: reviewed-approved

#908 Fix actualBreakpoint NRE in Row
  components/grid/Row.razor.cs
Labels: PR: reviewed-approved

#903 fix(module:slider): drag, select, focus and rapid reposition fix
  components/slider/Slider.razor
  components/slider/Slider.razor.cs
Labels: PR: reviewed-approved

#911 fix(module:descriptions) Colspan calculates error fix
  components/descriptions/Descriptions.razor
Labels: PR: reviewed-approved

#909 增加Table的TitleStyle，拆分开标题和内容的Style，并调整扩展列的折叠按钮居中。
  components/table/ActionColumn.razor
  components/table/Column.razor
  components/table/ColumnBase.cs
  components/table/Selection.razor
  components/table/Table.razor
  components/table/TableSize.cs
Labels: PR: reviewed-approved

#897 fix(module:OverlayTrigger): overlay will reposition on window resize
  components/core/Component/overlay/OverlayTrigger.razor.cs
Labels: PR: reviewed-approved

#913 fix(module: antlistitem) column width is overwritten by flex style
  components/list/ListItem.razor
Labels: PR: reviewed-approved

#884 fix: using ConfimRef to close Confirm dialog but not reset body's scroll bar (#883)
  components/modal/ComfirmContainer.razor.cs
Labels: PR: reviewed-approved

#920 feat: autoValidate
  components/core/Base/AntInputComponentBase.cs
  components/form/Form.razor.cs
  components/form/Internal/IForm.cs
  site/AntBlazor.Docs/Demos/Components/Form/demo/ValidateOnChange.razor
  site/AntBlazor.Docs/Demos/Components/Form/demo/validate-onchange.md
Labels: PR: reviewed-approved

#921 Expose SubMenu's Placement
  components/core/Component/overlay/Overlay.razor.cs
  components/menu/SubMenu.razor
  components/menu/SubMenu.razor.cs
Labels: PR: reviewed-approved

#925 Overlay can be aligned to right when trigger is not button.
  components/core/Component/overlay/Overlay.razor.cs
Labels: PR: merged

#914 refactor(module: modal): refactor the code of Modal, Confirm
  components/core/Extensions/EnumerableExtensions.cs
  components/core/JsInterop/modules/dragHelper.ts
  components/modal/ComfirmContainer.razor
  components/modal/ComfirmContainer.razor.cs
  components/modal/ConfirmRef.cs
  components/modal/Modal.razor
  components/modal/Modal.razor.cs
  components/modal/ModalContainer.razor
  components/modal/ModalService.cs
  components/modal/config/ConfirmOptions.cs
  components/modal/config/DialogOptions.cs
  components/modal/config/DialogOptionsBase.cs
  components/modal/config/ModalOptions.cs
  components/modal/confirmDialog/ComfirmContainer.razor
  components/modal/confirmDialog/ComfirmContainer.razor.cs
  components/modal/confirmDialog/Confirm.razor
  components/modal/confirmDialog/Confirm.razor.cs
  components/modal/confirmDialog/ConfirmRef.cs
  components/modal/confirmDialog/ConfirmService.cs
  components/modal/confirmDialog/ConfirmTemplate.razor.cs
  components/modal/confirmDialog/ModalServiceForConfirm.cs
  components/modal/core/Dialog.razor
  components/modal/core/Dialog.razor.cs
  components/modal/core/DialogWrapper.razor
  components/modal/core/DialogWrapper.razor.cs
  components/modal/modalDialog/Modal.razor
  components/modal/modalDialog/Modal.razor.cs
  components/modal/modalDialog/ModalContainer.razor
  components/modal/modalDialog/ModalContainer.razor.cs
  components/modal/modalDialog/ModalFooter.razor
  components/modal/modalDialog/ModalFooter.razor.cs
  components/modal/modalDialog/ModalLocale.cs
  components/modal/modalDialog/ModalRef.cs
  components/modal/modalDialog/ModalServiceForModal.cs
  components/modal/modalDialog/ModalTemplate.cs
  components/modal/type/ConfirmButtons.cs
  components/modal/type/ModalAnimation.cs
  site/AntBlazor.Docs/Demos/Components/Modal/demo/Async.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/ConfirmPromise.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/ConfirmRouter.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/Manual.razor
  site/AntBlazor.Docs/Demos/Components/Modal/demo/Modal_service_for_confirm.razor
  site/AntBlazor.Docs/Demos/Components/Modal/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Modal/doc/index.zh-CN.md
Labels: PR: partially-approved

#918 Issue#915,and fix the issue that can not render correctly when change…
  components/carousel/Carousel.razor
  components/carousel/Carousel.razor.cs
  components/carousel/CarouselSlick.cs
  components/carousel/CarouselSlick.razor
  components/carousel/CarouselSlick.razor.cs
Labels: PR: reviewed-approved

#929 fix(module: table): tree data doesn't work in asynchrony
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/TreeData.razor
Labels: PR: unreviewed

#930 fix: remove non auto destroyed Modal DOM created by ModalService (#926)
  components/modal/modalDialog/Modal.razor.cs
  components/modal/modalDialog/ModalServiceForModal.cs
Labels: PR: reviewed-approved

#931 fix(module: timeline): add/remove item dynamically
  components/timeline/Timeline.razor.cs
  components/timeline/TimelineItem.cs
Labels: PR: unreviewed

#938 docs: fix header & breakpoint
  components/core/JsInterop/DomEventService.cs
  site/AntBlazor.Docs/Pages/Index.razor
  site/AntBlazor.Docs/Pages/Index.razor.cs
  site/AntBlazor.Docs/Shared/MainHeader.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
Labels: PR: unreviewed

#939 fix(module: mainHeader): overlayStyle should not change menu's width
  site/AntBlazor.Docs/Shared/MainHeader.razor
Labels: PR: reviewed-approved

#777 feat: tree update
  components/tree/Tree.razor
  components/tree/Tree.razor.cs
  components/tree/TreeEventArgs.cs
  components/tree/TreeIndent.razor
  components/tree/TreeIndent.razor.cs
  components/tree/TreeNode.razor
  components/tree/TreeNode.razor.cs
  components/tree/TreeNodeCheckbox.razor
  components/tree/TreeNodeCheckbox.razor.cs
  components/tree/TreeNodeSwitcher.razor
  components/tree/TreeNodeSwitcher.razor.cs
  components/tree/TreeNodeTitle.razor
  components/tree/TreeNodeTitle.razor.cs
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/BasicControlled.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Bind.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Dynamic.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Event.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Line.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Modify.md
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Modify.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Property.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Searchdemo.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Template.razor
  site/AntBlazor.Docs/IsExternalInit.cs
Labels: PR: reviewed-approved
