Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2020-07, with the labels that each got.

#289 chore: update versions for release 0.1.0 and development of 0.2.0
  .github/workflows/gh-pages.yml
  README-zh_CN.md
  README.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: unreviewed

#277 chore: sync ant-design v4.4.0
  components/collapse/style/index.less
  components/dropdown/style/index.less
  components/form/style/index.less
  components/input-number/style/rtl.less
  components/menu/style/dark.less
  components/modal/style/modal.less
  components/notification/style/index.less
  components/page-header/style/index.less
  components/pagination/style/index.less
  components/select/style/index.less
  components/skeleton/style/index.less
  components/steps/style/progress-dot.less
  components/style/themes/compact.less
  components/style/themes/default.less
  components/switch/style/index.less
  components/table/style/index.less
  components/table/style/rtl.less
  components/tabs/style/index.less
  components/tag/style/index.less
  components/tag/style/rtl.less
  components/tree/style/mixin.less
  components/typography/style/index.less
  components/typography/style/rtl.less
Labels: PR: unreviewed

#293 fix: bugs for issues #292
  components/dropdown/Dropdown.razor
Labels: PR: reviewed-approved

#296 fix(module: upload) : firefox upload
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
Labels: PR: reviewed-approved

#295 fix: drawer OnOpen bull
  components/drawer/DrawerTemplate.razor.cs
Labels: PR: reviewed-approved

#298 fix(module: table): refresh when datasource is changed
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  components/table/Table.razor.cs
Labels: PR: unreviewed

#300 fix: bugs in button, it dimension will be chaned when click on it
  components/button/Button.razor.cs
  site/AntBlazor.Docs/Demos/Button/demo/Ghost.razor
  site/AntBlazor.Docs/Demos/Button/demo/Icon.razor
  site/AntBlazor.Docs/Demos/Button/demo/Icon_.razor
  site/AntBlazor.Docs/Demos/Button/demo/Multiple.razor
Labels: PR: reviewed-approved

#301 refactor: reduce dependence
  components/AntDesign.csproj
  components/core/Component/overlay/type/PlacementType.cs
  components/core/Component/overlay/type/TriggerType.cs
  components/core/EnumValue.cs
  components/form/types/FormLayout.cs
  components/layout/BreakpointType.cs
  components/layout/SiderTheme.cs
  components/menu/AntMenuMode.cs
  components/menu/AntMenuTheme.cs
  components/menu/MenuMode.cs
  components/menu/MenuTheme.cs
  components/progress/ProgressEnum.cs
  components/transfer/TransferDirection.cs
Labels: PR: unreviewed

#306 feat: improve range picker
  components/calendar/Calendar.razor.cs
  components/core/Helpers/DateHelper.cs
  components/core/Internal/EventHandlers.cs
  components/date-picker/DatePicker.razor
  components/date-picker/IDatePicker.cs
  components/date-picker/RangePicker.razor
  components/date-picker/RangePicker.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerLocaleHelper.cs
  components/date-picker/internal/DatePickerMonthPanel.razor
  components/date-picker/internal/DatePickerTemplate.razor
  components/date-picker/internal/DatePickerTemplate.razor.cs
  components/date-picker/internal/DatePickerYearPanel.razor
  components/date-picker/types/DatePickerPlaceholder.cs
Labels: PR: reviewed-approved

#309 refactor(module: statistic): simplify format string for countdown
  components/statistic/CountDown.razor
  components/statistic/CountDown.razor.cs
  site/AntBlazor.Docs/Demos/Statistic/demo/Countdown.razor
Labels: PR: unreviewed

#311 feat(module: table): support string formatting for field columns
  components/core/Extensions/DataAnnotationsExtensions.cs
  components/core/Extensions/EnumerableExtensions.cs
  components/core/Extensions/FieldIdentifierExtensions.cs
  components/core/Extensions/ServiceCollectionExtensions.cs
  components/core/Helpers/Formatter.cs
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/IFieldColumn.cs
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
Labels: PR: unreviewed

#314 chore: sync ant-design v4.4.1
  components/drawer/style/drawer.less
  components/form/style/mixin.less
  components/menu/style/index.less
  components/page-header/style/index.less
  components/radio/style/index.less
  components/skeleton/style/index.less
  components/table/style/bordered.less
Labels: PR: unreviewed

#308 fix: input and textarea bug
  components/input/Input.cs
  components/input/TextArea.razor.cs
Labels: PR: reviewed-approved

#313 feat: allow clearing datepicker view
  components/date-picker/DatePicker.Razor.cs
  components/date-picker/DatePicker.razor
  components/date-picker/RangePicker.razor
  components/date-picker/RangePicker.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerInput.razor
Labels: PR: reviewed-approved

#316 fix(module: Table): when no rows were selected, page turning is abnormal
  components/table/Table.razor.cs
Labels: PR: partially-approved

#317 refactor: improve input and textarea
  components/core/EventCallbackArgs/OnResizeEventArgs.cs
  components/input/Input.cs
  components/input/TextArea.razor
  components/input/TextArea.razor.cs
  site/AntBlazor.Docs/Demos/Input/demo/Area.razor
Labels: PR: partially-approved

#324 fix: fix the form binding value bug
  components/cascader/Cascader.razor.cs
  components/date-picker/DatePicker.Razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/input-number/InputNumber.razor.cs
  components/switch/Switch.razor.cs
  site/AntBlazor.Docs/Demos/Form/demo/Size.razor
Labels: PR: reviewed-approved

#303 fix(module: slider): event OnAfterChange fires incorrectly
  components/slider/Slider.razor.cs
Labels: PR: reviewed-approved

#310 feat: add animating for button component when mouseup event fired
  components/button/Button.razor
  components/button/Button.razor.cs
  site/AntBlazor.Docs/Demos/Button/demo/Loading.razor
Labels: PR: reviewed-approved

#319 feat(module: table): sortable
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/IFieldColumn.cs
  components/table/ITable.cs
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  components/table/Table.razor.Selection.cs
  components/table/Table.razor.cs
  components/table/TableModels/ITableSortModel.cs
  components/table/TableModels/QueryModel.cs
  components/table/TableModels/SortModel.cs
  components/table/TableModels/SortType.cs
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
Labels: PR: unreviewed

#332 fixed issue 330# [Tabs] Set activeKey failed in programming way.
  components/tabs/Tabs.razor.cs
  site/AntBlazor.Docs/Demos/Tabs/demo/Basic.razor
Labels: PR: reviewed-approved

#328 DocScrape action
  .github/workflows/algolia-config.json
  .github/workflows/docsearch.yml
Labels: PR: reviewed-approved

#271 feat: add algolia search
  scripts/gh-pages/index.html
  site/AntBlazor.Docs/Pages/Components.razor.cs
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
  site/AntBlazor.Docs/wwwroot/js/docsearch.js
  site/AntDesign.Docs.Server/Pages/_Host.cshtml
  site/AntDesign.Docs.Wasm/wwwroot/index.html
Labels: PR: reviewed-approved, documentation

#338 docs: replace algolia config items
  .github/workflows/algolia-config.json
  site/AntBlazor.Docs/Pages/Components.razor.cs
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
  site/AntBlazor.Docs/wwwroot/js/docsearch.js
Labels: PR: unreviewed

#343 fix(module: grid): fixed using size (xs, sm, etc) span with offset
  components/grid/Col.razor.cs
Labels: PR: reviewed-approved

#341 feat(module: table): support paging selection
  components/core/Extensions/EnumerableExtensions.cs
  components/table/ISelectionColumn.cs
  components/table/ITable.cs
  components/table/Selection.razor.cs
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  components/table/Table.razor.RowData.cs
  components/table/Table.razor.Selection.cs
  components/table/Table.razor.cs
  components/table/TableModels/RowData.cs
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
Labels: PR: unreviewed

#342 add templateRef to step component
  components/steps/Step.razor
  components/steps/Step.razor.cs
  site/AntBlazor.Docs/Demos/Steps/demo/Clickable.razor
  site/AntBlazor.Docs/Demos/Steps/demo/CustomizedProgressDot.razor
  site/AntBlazor.Docs/Demos/Steps/demo/Error.razor
  site/AntBlazor.Docs/Demos/Steps/demo/Icon_.razor
  site/AntBlazor.Docs/Demos/Steps/demo/Nav.razor
  site/AntBlazor.Docs/Demos/Steps/demo/ProgressDot.razor
  site/AntBlazor.Docs/Demos/Steps/demo/Simple.razor
  site/AntBlazor.Docs/Demos/Steps/demo/SmallSize.razor
  site/AntBlazor.Docs/Demos/Steps/demo/Vertical.razor
  site/AntBlazor.Docs/Demos/Steps/demo/VerticalSmall.razor
Labels: PR: reviewed-approved

#286 feat: new mentions components
  components/components.less
  components/core/Base/AntComponentBase.cs
  components/core/JsInterop/Caret.ts
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/mention/style/entry.less
  components/mention/style/index.less
  components/mentions/Mentions.razor
  components/mentions/Mentions.razor.cs
  components/mentions/MentionsOption.razor
  components/mentions/MentionsOption.razor.cs
  site/AntBlazor.Docs/Demos/Mentions/demo/Async.razor
  site/AntBlazor.Docs/Demos/Mentions/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Mentions/demo/Form.razor
  site/AntBlazor.Docs/Demos/Mentions/demo/Placement.razor
  site/AntBlazor.Docs/Demos/Mentions/demo/Prefix.razor
  site/AntBlazor.Docs/Demos/Mentions/demo/Readonly.razor
  site/AntBlazor.Docs/Demos/Mentions/demo/async.md
  site/AntBlazor.Docs/Demos/Mentions/demo/basic.md
  site/AntBlazor.Docs/Demos/Mentions/demo/form.md
  site/AntBlazor.Docs/Demos/Mentions/demo/placement.md
  site/AntBlazor.Docs/Demos/Mentions/demo/prefix.md
  site/AntBlazor.Docs/Demos/Mentions/demo/readonly.md
  site/AntBlazor.Docs/Demos/Mentions/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Mentions/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed

#346 chore: sync ant-design v4.4.2
  components/alert/style/index.less
  components/card/style/index.less
  components/date-picker/style/index.less
  components/radio/style/index.less
  components/select/style/index.less
  components/select/style/single.less
  components/style/themes/default.less
  components/table/style/index.less
  components/typography/style/index.less
Labels: PR: unreviewed

#333 fix(module: form): value not change when model change
  components/cascader/Cascader.razor.cs
  components/core/Base/AntInputComponentBase.cs
  components/date-picker/DatePicker.Razor.cs
  components/date-picker/DatePicker.razor
  components/date-picker/MonthPicker.cs
  components/date-picker/QuarterPicker.cs
  components/date-picker/RangePicker.razor
  components/date-picker/RangePicker.razor.cs
  components/date-picker/WeekPicker.cs
  components/date-picker/YearPicker.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerFooter.razor
  components/date-picker/internal/DatePickerInput.razor
  components/form/Form.razor.cs
  components/time-picker/TimePicker.cs
  site/AntBlazor.Docs/Demos/DatePicker/demo/Basic.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Bordered.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/DateRender.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Disabled.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/DisabledDate.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/ExtraFooter.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Format.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Globalization.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/RangePickerDemo.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Size.razor
  site/AntBlazor.Docs/Demos/DatePicker/demo/Time.razor
  site/AntBlazor.Docs/Demos/Form/demo/Size.razor
  site/AntBlazor.Docs/Demos/Input/demo/Group.razor
  site/AntBlazor.Docs/Demos/TimePicker/demo/Addon.razor
  site/AntBlazor.Docs/Demos/TimePicker/demo/Basic.razor
  site/AntBlazor.Docs/Demos/TimePicker/demo/Disabled.razor
  site/AntBlazor.Docs/Demos/TimePicker/demo/HideColumn.razor
  site/AntBlazor.Docs/Demos/TimePicker/demo/Size.razor
  site/AntBlazor.Docs/Demos/TimePicker/demo/Value.razor
Labels: PR: unreviewed

#339 fix: enable scroll breaking custom style (#337)
  components/core/JsInterop/interop.ts
Labels: PR: reviewed-approved

#327 Form context, IsModified property
  components/form/Form.razor.cs
  components/form/Internal/IForm.cs
  site/AntBlazor.Docs/Demos/Form/demo/FormContext.md
  site/AntBlazor.Docs/Demos/Form/demo/FormContext.razor
Labels: PR: reviewed-approved

#340 try to fix #334
  components/input/Input.cs
  components/input/TextArea.razor
Labels: PR: unreviewed

#345 Feat: modal update
  components/core/AntContainer.razor
  components/drawer/DrawerRef.cs
  components/drawer/DrawerService.cs
  components/drawer/config/DrawerClosingEventArgs.cs
  components/drawer/config/DrawerOptions.cs
  components/modal/Comfirm.razor
  components/modal/Comfirm.razor.cs
  components/modal/ComfirmContainer.razor
  components/modal/ComfirmContainer.razor.cs
  components/modal/ConfirmDialog.razor
  components/modal/ConfirmDialog.razor.cs
  components/modal/ModalRef.cs
  components/modal/ModalService.cs
  components/modal/ModalTemplate.razor.cs
  components/modal/config/ConfirmOptions.cs
  components/modal/config/IModalTemplate.cs
  components/modal/config/ModalClosingEventArgs.cs
  site/AntBlazor.Docs/Demos/Drawer/DrawerTemplateDemo.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/Drawer_service.razor
  site/AntBlazor.Docs/Demos/Drawer/demo/drawer_service.md
  site/AntBlazor.Docs/Demos/Modal/ModalTemplateDemo.razor
  site/AntBlazor.Docs/Demos/Modal/demo/Confirm.razor
  site/AntBlazor.Docs/Demos/Modal/demo/ConfirmPromise.razor
  site/AntBlazor.Docs/Demos/Modal/demo/Manual.razor
  site/AntBlazor.Docs/Demos/Modal/demo/Modal_service.razor
  site/AntBlazor.Docs/Demos/Modal/demo/confirm-promise.md
  site/AntBlazor.Docs/Demos/Modal/demo/modal_service.md
Labels: PR: reviewed-approved

#351 fix(module: upload) : Determine success based on status==200
  components/core/JsInterop/interop.ts
Labels: PR: reviewed-approved

#349 feat(module: form): add complex-form-control demo
  components/AntDesign.csproj
  components/form/Form.razor
  components/form/FormItem.razor.cs
  site/AntBlazor.Docs/Demos/Form/demo/ComplexFormControl.razor
  site/AntBlazor.Docs/Demos/Form/demo/complex-form-control.md
Labels: PR: reviewed-approved, PR: unreviewed

#353 feat(module: form): add Required paramater
  components/form/FormItem.razor
  components/form/FormItem.razor.cs
Labels: PR: reviewed-approved

#352 fix(module: avatar): string content centered
  components/avatar/Avatar.razor.cs
  site/AntBlazor.Docs/Demos/Avatar/demo/Badge_.razor
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
Labels: PR: reviewed-approved

#354 feat(module: form): add customized-form-controls demo
  site/AntBlazor.Docs/Demos/Form/demo/ComplexFormControl.razor
  site/AntBlazor.Docs/Demos/Form/demo/CustomizedFormControls.razor
  site/AntBlazor.Docs/Demos/Form/demo/FormContext.md
  site/AntBlazor.Docs/Demos/Form/demo/complex-form-control.md
  site/AntBlazor.Docs/Demos/Form/demo/customized-form-controls.md
  site/AntBlazor.Docs/Demos/Form/objects/Price.cs
  site/AntBlazor.Docs/Demos/Form/objects/PriceInput.razor
Labels: PR: unreviewed

#355 docs: fix model and drawer documentation errors
  components/icon/Icon.razor.cs
  components/wwwroot/icons/outline/compress.svg
  components/wwwroot/icons/outline/expand.svg
  site/AntBlazor.Docs/Demos/Drawer/demo/drawer_service.md
  site/AntBlazor.Docs/Demos/Drawer/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Modal/demo/modal_service.md
  site/AntBlazor.Docs/Demos/Modal/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Modal/doc/index.zh-CN.md
  site/AntBlazor.Docs/Pages/Components.razor
  site/AntBlazor.Docs/Pages/Components.razor.cs
Labels: PR: reviewed-approved

#358 fix(module: switch): two-way binding and loading
  components/switch/Switch.razor
  components/switch/Switch.razor.cs
  site/AntBlazor.Docs/Demos/Switch/demo/Disable.razor
  site/AntBlazor.Docs/Demos/Switch/demo/Loading.razor
  site/AntBlazor.Docs/Demos/Table/demo/Blazor.razor
  site/AntBlazor.Docs/Pages/Components.razor.cs
Labels: PR: unreviewed

#359 feat(module: menu): add internal router link
  components/menu/MenuItem.razor
  components/menu/MenuItem.razor.cs
  components/menu/MenuLink.cs
  site/AntBlazor.Docs/Demos/Menu/demo/Router.razor
  site/AntBlazor.Docs/Demos/Menu/demo/router.md
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/NavMenu.razor
Labels: PR: unreviewed

#361 fix(module: menu): submenu can't open after collapsed recover
  components/menu/Menu.razor.cs
  components/menu/MenuLink.cs
  components/menu/SubMenu.razor.cs
  site/AntBlazor.Docs/Demos/Menu/demo/Horizontal.razor
  site/AntBlazor.Docs/Demos/Menu/demo/Router.razor
Labels: PR: unreviewed

#363 fix(module: layout): missing OnCollapse event
  components/layout/Sider.razor.cs
  site/AntBlazor.Docs/Demos/Layout/demo/CustomTrigger.razor
Labels: PR: unreviewed

#329 feat(module: slider): implement two-way binding
  components/core/Base/AntInputComponentBase.cs
  components/core/Extensions/DataConvertionExtensions.cs
  components/slider/Slider.razor
  components/slider/Slider.razor.cs
  site/AntBlazor.Docs/Demos/Slider/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Customer.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Event.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Graduated.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Icon1.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Input.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Reversed.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Tooltip.razor
  site/AntBlazor.Docs/Demos/Slider/demo/Vslider.razor
  site/AntBlazor.Docs/Demos/Space/demo/Customize.razor
Labels: PR: reviewed-approved

#362 feat(module: form): add form-context demo, support FormProvider
  components/form/EventCallbackArgs/FormProviderFinishEventArgs.cs
  components/form/Form.razor
  components/form/Form.razor.cs
  components/form/FormProvider.razor
  components/form/FormProvider.razor.cs
  components/form/Internal/IForm.cs
  components/form/Internal/IFormProvider.cs
  site/AntBlazor.Docs/Demos/Form/demo/FormContext.razor
  site/AntBlazor.Docs/Demos/Form/demo/IsModified.razor
  site/AntBlazor.Docs/Demos/Form/demo/form-context.md
  site/AntBlazor.Docs/Demos/Form/demo/is-modified.md
Labels: PR: reviewed-approved

#369 fix: AutoComplete Bug
  components/auto-complete/AutoComplete.razor
  components/auto-complete/AutoComplete.razor.cs
Labels: PR: unreviewed

#366 feat: add affixed demo list
  components/affix/Affix.razor.cs
  components/anchor/Anchor.razor.cs
  components/anchor/AnchorLink.razor.cs
  components/anchor/AnchorLinkEqualityComparer.cs
  components/anchor/IAnchor.cs
  site/AntBlazor.Docs/Pages/Components.razor
Labels: PR: unreviewed

#370 fix: descriptions responsive
  components/descriptions/Descriptions.razor
  components/descriptions/Descriptions.razor.cs
  site/AntBlazor.Docs/Demos/Descriptions/demo/Responsive.razor
Labels: PR: reviewed-approved

#373 fix(module: modal): crashes when DestroyOnClose is set to true (#371)
  components/modal/Modal.razor.cs
Labels: PR: reviewed-approved

#372 fix(module: icon): put spin class on outside
  components/icon/Icon.razor
  components/icon/Icon.razor.cs
  components/icon/IconFont.razor.cs
  components/icon/IconService.cs
Labels: PR: unreviewed

#378 fix(module: avatar): dead-loop rendering
  components/avatar/Avatar.razor
  components/avatar/Avatar.razor.cs
Labels: PR: reviewed-approved

#381 fix: 菜单重复的问题
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/Demos/BackTop/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/BackTop/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Divider/doc/index.zh-CN.md
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed

#64 [WIP] docs: refactor layout
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntBlazor.Docs/App.razor
  site/AntBlazor.Docs/Demos/BackTop/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/BackTop/doc/index.zh-CN.md
  site/AntBlazor.Docs/Demos/Divider/doc/index.zh-CN.md
  site/AntBlazor.Docs/Pages/Components.razor
  site/AntBlazor.Docs/Pages/Components.razor.cs
  site/AntBlazor.Docs/Pages/Docs.razor
  site/AntBlazor.Docs/Pages/Docs.razor.cs
  site/AntBlazor.Docs/Pages/Overview.razor
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Services/DemoService.cs
  site/AntBlazor.Docs/Shared/MainFooter.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
  site/AntBlazor.Docs/Shared/NavMenu.razor
  site/AntBlazor.Docs/Shared/PrevNextNav.razor
  site/AntBlazor.Docs/wwwroot/menu.json
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
  site/AntDesign.Docs.Build.CLI/Command/GenerateMenuJsonCommand.cs
  site/AntDesign.Docs.Build.CLI/Properties/launchSettings.json
Labels: documentation

#391 feat (module: upload): FileList, PictureStyle, Avatar
  components/core/JsInterop/interop.ts
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
  site/AntBlazor.Docs/Demos/Upload/demo/Avatar.razor
  site/AntBlazor.Docs/Demos/Upload/demo/FileList.razor
  site/AntBlazor.Docs/Demos/Upload/demo/PictureStyle.razor
  site/AntBlazor.Docs/Demos/Upload/demo/avatar.md
  site/AntBlazor.Docs/Demos/Upload/demo/fileList.md
  site/AntBlazor.Docs/Demos/Upload/demo/pictureStyle.md
  site/AntBlazor.Docs/Services/DemoService.cs
  site/AntBlazor.Docs/Shared/CodeBox.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
Labels: PR: reviewed-approved

#392 chore: sync ant-design v4.4.3
  components/popconfirm/style/index.less
  components/style/themes/default.less
  components/table/style/index.less
Labels: PR: unreviewed

#397 chore: add id to api header
  site/AntBlazor.Docs/Pages/Components.razor
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
Labels: PR: reviewed-approved

#398 fix(module: upload): Upload with other form parameters
  components/core/JsInterop/interop.ts
  components/upload/Upload.razor.cs
Labels: PR: reviewed-approved

#401 fix: drawer, modal and confirm multi level open scroll bar bug (#393)
  components/core/JsInterop/interop.ts
Labels: PR: reviewed-approved

#399 fix: children components dispose
  components/anchor/Anchor.razor.cs
  components/anchor/AnchorLink.razor.cs
  components/anchor/IAnchor.cs
  components/carousel/Carousel.razor.cs
  components/carousel/CarouselSlick.cs
  components/checkbox/Checkbox.razor.cs
  components/descriptions/DescriptionsItem.razor.cs
  components/icon/Icon.razor.cs
  components/mentions/Mentions.razor.cs
  components/mentions/MentionsOption.razor.cs
  components/menu/MenuItem.razor.cs
  components/radio/Radio.razor.cs
  components/radio/RadioGroup.razor.cs
  components/select/Select.razor.cs
  components/select/SelectOptGroup.razor.cs
  components/select/SelectOption.razor.cs
  components/table/ColumnBase.cs
  components/tabs/TabPane.razor.cs
  components/timeline/Timeline.razor.cs
  components/timeline/TimelineItem.cs
Labels: PR: unreviewed

#402 feat(module: tabs): two-way binding for ActiveKey
  components/tabs/Tabs.razor.cs
  site/AntBlazor.Docs/Demos/Tabs/demo/Basic.razor
Labels: PR: unreviewed

#407 fix: form.onFinishEvent is null bug
  components/form/Form.razor.cs
Labels: PR: unreviewed

#408 fix(module:modal): the width will be added when there is no scroll bar
  components/core/JsInterop/interop.ts
Labels: PR: reviewed-approved

#410 docs: fix menu order and demo rendering
  site/AntBlazor.Docs/Services/DemoService.cs
  site/AntBlazor.Docs/Shared/CodeBox.razor
  site/AntDesign.Docs.Build.CLI/Command/GenerateMenuJsonCommand.cs
  site/AntDesign.Docs.Build.CLI/Utils/MenuComparer.cs
Labels: PR: unreviewed

#411 docs: fix typo on table sizes demo
  site/AntBlazor.Docs/Demos/Table/demo/Size.razor
Labels: PR: reviewed-approved

#414 docs: add guides
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/contributing.en-US.md
  docs/contributing.zh-CN.md
  docs/getting-started.en-US.md
  docs/getting-started.zh-CN.md
Labels: PR: unreviewed

#415 fix(module: slider): not working under wasm
  components/core/Helpers/Formatter.cs
  components/slider/Slider.razor.cs
Labels: PR: unreviewed

#394 fix(module: dropdown): couldn't auto close menu
  components/core/Component/overlay/Overlay.razor
  components/core/Component/overlay/Overlay.razor.cs
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/core/JsInterop/interop.ts
  components/dropdown/DropdownButton.cs
  components/menu/Menu.razor.cs
  components/popconfirm/Popconfirm.razor.cs
  components/popover/Popover.razor.cs
  components/tooltip/Tooltip.razor.cs
  site/AntBlazor.Docs/Demos/Dropdown/demo/ContextMenu.razor
  site/AntBlazor.Docs/Demos/Dropdown/demo/OverlayVisible.razor
Labels: PR: reviewed-approved

#422 fix(module: upload): Directory upload demo
  site/AntBlazor.Docs/Demos/Upload/demo/Directory.razor
  site/AntBlazor.Docs/Demos/Upload/demo/directory.md
Labels: PR: unreviewed

#424 fix(module: timeline): missing default constructor
  components/timeline/Timeline.razor
  components/timeline/Timeline.razor.cs
  components/timeline/TimelineItem.cs
Labels: PR: unreviewed

#412 refactor : replace system.tuple with value tuples
  components/descriptions/Descriptions.razor.cs
Labels: PR: unreviewed

#420 Issue 406
  components/tooltip/Tooltip.razor
  components/tooltip/Tooltip.razor.cs
  site/AntBlazor.Docs/Demos/Tooltip/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Tooltip/doc/index.zh-CN.md
Labels: PR: unreviewed

#426 fix(module: AntInputComponentBase ): always triggers statehaschanged
  components/core/Base/AntInputComponentBase.cs
Labels: PR: reviewed-approved

#427 docs: add home page
  README.md
  components/menu/MenuLink.cs
  docs/assets/logo.svg
  site/AntBlazor.Docs/Localization/Resources.cs
  site/AntBlazor.Docs/Pages/Index.razor
  site/AntBlazor.Docs/Pages/Index.razor.cs
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
  site/AntBlazor.Docs/Services/DemoService.cs
  site/AntBlazor.Docs/Services/MoreProps.cs
  site/AntBlazor.Docs/Services/Product.cs
  site/AntBlazor.Docs/Services/Recommend.cs
  site/AntBlazor.Docs/Shared/HeaderMenu.razor
  site/AntBlazor.Docs/Shared/HeaderMenu.razor.cs
  site/AntBlazor.Docs/Shared/MainFooter.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor.cs
  site/AntBlazor.Docs/Shared/NavMenu.razor
  site/AntBlazor.Docs/Shared/NavMenu.razor.cs
  site/AntBlazor.Docs/Shared/Recommend.razor
  site/AntBlazor.Docs/style/index.less
  site/AntBlazor.Docs/style/template/Home/Banner/Background.less
  site/AntBlazor.Docs/style/template/Home/Banner/Logo.less
  site/AntBlazor.Docs/style/template/Home/Banner/index.less
  site/AntBlazor.Docs/style/template/Home/DesignPage/index.less
  site/AntBlazor.Docs/style/template/Home/MorePage.less
  site/AntBlazor.Docs/style/template/Home/RecommendPage.less
  site/AntBlazor.Docs/style/template/Home/index.less
  site/AntBlazor.Docs/wwwroot/data/more-list.en-US.json
  site/AntBlazor.Docs/wwwroot/data/more-list.zh-CN.json
  site/AntBlazor.Docs/wwwroot/data/products.json
  site/AntBlazor.Docs/wwwroot/data/recommend.en-US.json
  site/AntBlazor.Docs/wwwroot/data/recommend.zh-CN.json
  site/AntBlazor.Docs/wwwroot/menu.json
Labels: PR: unreviewed

#432 fix: missing language resources for 'Examples'
  site/AntBlazor.Docs/Resources/en-US.yml
  site/AntBlazor.Docs/Resources/zh-CN.yml
Labels: PR: reviewed-approved

#434 fix(module: upload): add OnRemove delegate
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
  site/AntBlazor.Docs/Demos/Upload/demo/PictureStyle.razor
Labels: PR: unreviewed

#320 fix: Select component bug #305
  components/select/Select.razor
  components/select/Select.razor.cs
  components/select/SelectOption.razor
  components/select/SelectOption.razor.cs
  site/AntBlazor.Docs/Demos/Select/demo/ClearValues.razor
  site/AntBlazor.Docs/Demos/Select/demo/Multiple.razor
  site/AntBlazor.Docs/Demos/Select/demo/Search.razor
Labels: PR: reviewed-approved

#436 Docs: Update the demo code for Loading Button
  site/AntBlazor.Docs/Demos/Button/demo/Loading.razor
Labels: PR: reviewed-approved

#435 fix(module: input): incorrect OnPressEnter
  components/input/Input.cs
  components/input/Search.razor.cs
  components/input/TextArea.razor
  site/AntBlazor.Docs/Demos/Input/demo/Search_.razor
Labels: PR: unreviewed

#437 fix(module: checkbox): default value binding
  components/checkbox/Checkbox.razor.cs
  components/checkbox/CheckboxGroup.razor
  components/checkbox/CheckboxGroup.razor.cs
  components/core/Extensions/EnumerableExtensions.cs
  components/form/FormItem.razor.cs
  site/AntBlazor.Docs/Demos/Checkbox/demo/Group.razor
  site/AntBlazor.Docs/Demos/Select/demo/Basic.razor
Labels: PR: unreviewed

#438 feat(module: upload): Picture card demo
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
  components/upload/UploadFileItem.cs
  site/AntBlazor.Docs/Demos/Upload/demo/PictureCard.razor
  site/AntBlazor.Docs/Demos/Upload/demo/pictureCard.md
Labels: PR: reviewed-approved

#439 Use Task.Delay to replace Thread.Sleep in order to remove UI freezes.
  components/button/Button.razor.cs
  components/carousel/Carousel.razor.cs
Labels: PR: unreviewed

#440 fix: autoComplete bind-value bug
  components/auto-complete/AutoComplete.razor.cs
  site/AntBlazor.Docs/Demos/AutoComplete/demo/Basic.razor
  site/AntBlazor.Docs/Demos/AutoComplete/demo/Custom.razor
Labels: PR: unreviewed
