Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2021-04, with the labels that each got.

#1285 (fix) Table ExpandableRow not working with ActionColumn #1284
  components/table/ActionColumn.razor
  components/table/Column.razor.cs
  components/table/ColumnBase.cs
  components/table/Table.razor.cs
Labels: PR: reviewed-approved

#1303 fix(module:rate): Value has priority over DefaultValue
  components/rate/Rate.razor.cs
Labels: PR: reviewed-approved

#1293 #1287 Added LabelTemplate in FormItem
  components/form/FormItem.razor
  components/form/FormItem.razor.cs
  site/AntDesign.Docs/Demos/Components/Form/demo/CustomizedLabel.razor
  site/AntDesign.Docs/Demos/Components/Form/demo/complex-form-control.md
  site/AntDesign.Docs/Demos/Components/Form/demo/customized-label.md
Labels: PR: reviewed-approved

#1292 feat: Form lable supports left alignment
  components/core/Direction.cs
  components/form/ColLayoutParam.cs
  components/form/Form.razor.cs
  components/form/FormItem.razor
  components/form/FormItem.razor.cs
  components/form/Internal/IForm.cs
Labels: PR: reviewed-approved

#1295 fix(module: table): fix DataIndex Column
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/Internal/ColumnDataIndexHelper.cs
  components/table/Internal/ColumnExpressionHelper.cs
  components/table/Table.razor
  components/table/TableModels/DataIndexSortModel.cs
  components/table/TableModels/FilterModel.cs
  components/table/TableModels/SortModel.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Blazor.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/DataIndex.razor
Labels: PR: unreviewed

#1298 fix(module: datepicker): DatePicker DisabledDate works incorect
  components/core/Helpers/DateHelper.cs
  components/date-picker/internal/DatePickerTemplate.razor.cs
  tests/Core/Helpers/DateHelperTests.cs
Labels: PR: unreviewed

#1301 fix(module:upload): Upload list update fix
  components/core/JsInterop/interop.ts
  components/upload/Upload.razor
  components/upload/UploadButton.razor.cs
Labels: PR: unreviewed

#1302 feat(module:upload): missing and new event
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
  components/upload/UploadButton.razor.cs
  site/AntDesign.Docs/Demos/Components/Upload/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Upload/doc/index.zh-CN.md
Labels: PR: unreviewed

#1305 fix(module:textarea): default to empty string
  components/core/JsInterop/interop.ts
  components/input/TextArea.razor.cs
  site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md
Labels: PR: reviewed-approved

#1296 fix(module: grid): missing flex and wrap style
  components/grid/Col.razor
  components/grid/Col.razor.cs
  components/grid/Row.razor.cs
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
  site/AntDesign.Docs/Demos/Components/Grid/demo/Alignment.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Breakpoint.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/Breakpoint.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Flex.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/FlexAlign.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/FlexOrder.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/FlexStretch.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Gutter.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/More.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/More.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Offset.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/Order.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/Order.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Playground.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Playround.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/Responsive.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/Responsive.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/ResponsiveMore.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Setting.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/Setting.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Sort.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/Stretch.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/Stretch.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/UseBreakpoint.razor
  site/AntDesign.Docs/Demos/Components/Grid/demo/basic.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/flex-align.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/flex-order.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/flex-stretch.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/flex.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/gutter.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/offset.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/playground.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/responsive-more.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/responsive.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/sort.md
  site/AntDesign.Docs/Demos/Components/Grid/demo/useBreakpoint.md
  site/AntDesign.Docs/Services/DemoService.cs
Labels: PR: unreviewed

#1306 docs: add changelog in document
  site/AntDesign.Docs.Server/AntDesign.Docs.Server.csproj
  site/AntDesign.Docs.Server/Pages/_Host.cshtml
  site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
  site/AntDesign.Docs/AntDesign.Docs.csproj
  tests/grid/ColTests.cs
Labels: PR: unreviewed

#1307 fix(module:select): load icon for multiple mode & value reload on delay
  components/select/Select.razor
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor
Labels: PR: reviewed-approved

#1304 fix(module:table): perf optimization & data source change issue
  components/table/Table.razor
  components/table/Table.razor.cs
Labels: PR: unreviewed

#1308 fix(module:select): propagation on item remove
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor
Labels: PR: reviewed-approved

#1263 refactor: unified use of FeedbackComponent for modal comfirm and drawer
  components/core/Base/TemplateComponentBase.cs
  components/core/EventUtil.cs
  components/core/Feedback/FeedbackComponent.cs
  components/core/Feedback/FeedbackRefBase.cs
  components/core/Feedback/IFeedbackRef.cs
  components/core/Feedback/IOkCancelRef.cs
  components/drawer/DrawerContainer.razor
  components/drawer/DrawerContainer.razor.cs
  components/drawer/DrawerRef.cs
  components/drawer/DrawerService.cs
  components/drawer/DrawerTemplate.razor.cs
  components/drawer/IDrawerRef.cs
  components/modal/config/ConfirmOptions.cs
  components/modal/config/IModalTemplate.cs
  components/modal/config/ModalClosingEventArgs.cs
  components/modal/config/ModalOptions.cs
  components/modal/confirmDialog/Confirm.razor.cs
  components/modal/confirmDialog/ConfirmRef.cs
  components/modal/confirmDialog/ConfirmTemplate.razor.cs
  components/modal/confirmDialog/ModalServiceForConfirm.cs
  components/modal/core/Dialog.razor
  components/modal/core/Dialog.razor.cs
  components/modal/modalDialog/Modal.razor
  components/modal/modalDialog/Modal.razor.cs
  components/modal/modalDialog/ModalContainer.razor
  components/modal/modalDialog/ModalContainer.razor.cs
  components/modal/modalDialog/ModalFooter.razor
  components/modal/modalDialog/ModalFooter.razor.cs
  components/modal/modalDialog/ModalRef.cs
  components/modal/modalDialog/ModalServiceForModal.cs
  components/modal/modalDialog/ModalTemplate.cs
  site/AntDesign.Docs/Demos/Components/Drawer/DrawerTemplateDemo.razor
  site/AntDesign.Docs/Demos/Components/Drawer/demo/Drawer_service.razor
  site/AntDesign.Docs/Demos/Components/Modal/ConfirmTemplateDemo.razor
  site/AntDesign.Docs/Demos/Components/Modal/ModalTemplateDemo.razor
  site/AntDesign.Docs/Demos/Components/Modal/demo/Modal_service_for_confirm.razor
  site/AntDesign.Docs/Demos/Components/Modal/demo/Modal_service_for_modal.razor
  site/AntDesign.Docs/Demos/Components/Modal/demo/modal_service_for_confirm.md
Labels: PR: unreviewed

#1250 feat(Alert): added alert loop component
  components/alert/Alert.razor
  components/alert/Alert.razor.cs
  site/AntDesign.Docs/Demos/Components/Alert/demo/Banner.razor
  site/AntDesign.Docs/Demos/Components/Alert/demo/Icon_.razor
  site/AntDesign.Docs/Demos/Components/Alert/demo/LoopBanner.razor
  site/AntDesign.Docs/Demos/Components/Alert/demo/banner.md
  site/AntDesign.Docs/Demos/Components/Alert/demo/loop-banner.md
  site/AntDesign.Docs/Demos/Components/Alert/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Alert/doc/index.zh-CN.md
Labels: PR: unreviewed

#1310 feat(module:table): add support for column names from Display attribute
  components/core/Reflection/PropertyReflector.cs
Labels: PR: reviewed-approved

#1311 fix(module: table): fix table re-render when ScrollX is set
  components/table/Table.razor.cs
Labels: PR: reviewed-approved

#1313 docs(module: table): fix RouterPagging demo
  site/AntDesign.Docs/Demos/Components/Table/demo/RouterPagging.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/router-pagging.md
Labels: PR: reviewed-approved

#1314 feat(module: space): add wrap,split and size array
  components/core/Direction.cs
  components/core/DirectionVHType.cs
  components/divider/Divider.razor.cs
  components/space/Space.razor
  components/space/Space.razor.cs
  components/space/SpaceItem.razor
  components/space/SpaceItem.razor.cs
  components/typography/Link.cs
  site/AntDesign.Docs/Demos/Components/Divider/demo/Vertical.razor
  site/AntDesign.Docs/Demos/Components/Image/demo/Placeholder.razor
  site/AntDesign.Docs/Demos/Components/Space/demo/Align.razor
  site/AntDesign.Docs/Demos/Components/Space/demo/Customize.razor
  site/AntDesign.Docs/Demos/Components/Space/demo/Split.razor
  site/AntDesign.Docs/Demos/Components/Space/demo/Vertical.razor
  site/AntDesign.Docs/Demos/Components/Space/demo/Wrap.razor
  site/AntDesign.Docs/Demos/Components/Space/demo/align.md
  site/AntDesign.Docs/Demos/Components/Space/demo/split.md
  site/AntDesign.Docs/Demos/Components/Space/demo/wrap.md
  site/AntDesign.Docs/Demos/Components/Space/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Space/doc/index.zh-CN.md
  site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/Size.razor
Labels: PR: unreviewed

#1300 fix: some components are incorrect in RTL mode
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/date-picker/DatePicker.razor
  components/date-picker/RangePicker.razor
  components/date-picker/internal/DatePickerBase.cs
Labels: PR: reviewed-approved

#1318 docs: fix default css link
  scripts/gh-pages/index.html
  site/AntDesign.Docs.Wasm/wwwroot/index.html
  site/AntDesign.Docs.WasmHost/Pages/_Host.cshtml
Labels: PR: unreviewed

#1321 chagnelog 0.7.4
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#1309 fix(module:select): Select overlay resize & allow growing
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor
  components/select/internal/SelectContent.razor.cs
  site/AntDesign.Docs/Demos/Components/Select/doc/index.en-US.md
Labels: PR: reviewed-approved

#1322 fix(module:overlaytrigger): correct method disposal
  components/core/Component/overlay/OverlayTrigger.razor.cs
Labels: PR: unreviewed

#1326 feat(module:table): bring PR1208 to PR1303 merge master into feature
  components/table/Column.razor.cs
  components/table/ColumnBase.cs
Labels: PR: reviewed-approved

#1325 feat(module: pagination): add TotalBoundaryShowSizeChanger parameter
  components/pagination/Pagination.razor
  components/pagination/Pagination.razor.cs
  site/AntDesign.Docs/Demos/Components/Pagination/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Pagination/doc/index.zh-CN.md
Labels: PR: unreviewed

#1330 docs: fix dingtalk's broken links
  README-zh_CN.md
  README.md
  docs/assets/dingtalk.jpg
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: unreviewed

#1332 docs: dynamic primary color changing
  components/AntDesign.csproj
  package.json
  scripts/gh-pages/index.html
  site/AntDesign.Docs.Wasm/wwwroot/index.html
  site/AntDesign.Docs/Shared/MainFooter.razor
  site/AntDesign.Docs/Shared/MainFooter.razor.cs
  site/AntDesign.Docs/gulpfile.js
  site/AntDesign.Docs/wwwroot/color.less
Labels: PR: unreviewed

#1267 feat(module:table ) add more options on table filter
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/core/Helpers/THelper.cs
  components/locales/ar-EG.json
  components/locales/en-US.json
  components/locales/zh-CN.json
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/FilterExpression/DateFilterExpression.cs
  components/table/FilterExpression/FilterExpressionResolver.cs
  components/table/FilterExpression/IFilterExpression.cs
  components/table/FilterExpression/NumberFilterExpression.cs
  components/table/FilterExpression/StringFilterExpression.cs
  components/table/TableFilter.cs
  components/table/TableLocale.cs
  components/table/TableModels/FilterModel.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Filter.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/filter.md
Labels: PR: unreviewed

#1336 fix(module:result): modify status unsuccessfully after initialization(#1328)
  components/result/Result.razor.cs
  site/AntDesign.Docs/Demos/Components/Result/demo/ChangeTheResult.razor
  site/AntDesign.Docs/Demos/Components/Result/demo/changeTheResult.md
Labels: PR: reviewed-approved

#1338 feat(module:select): Select responsive max tag count
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/select/ResponsiveTag.cs
  components/select/Select.razor
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor
  components/select/internal/SelectContent.razor.cs
  components/select/internal/SelectOptionItem.cs
  site/AntDesign.Docs/Demos/Components/Select/demo/Responsive.razor
  site/AntDesign.Docs/Demos/Components/Select/demo/responsive.md
  site/AntDesign.Docs/Demos/Components/Select/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Select/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#1345 fix(module:table): Table tree children limit remove
  components/table/Table.razor
Labels: PR: reviewed-approved

#1344 docs(module:form): IsModified sample fix
  site/AntDesign.Docs/Demos/Components/Form/demo/IsModified.razor
Labels: PR: partially-approved

#1347 fix(module:datepicker): OnChange invoke after typing
  components/date-picker/DatePicker.Razor.cs
  components/date-picker/RangePicker.razor.cs
Labels: PR: partially-approved

#1335 fix(module: affix): affix to the viewport (#1327)
  components/affix/Affix.razor.cs
  site/AntDesign.Docs/Demos/Components/Affix/demo/Scroll.md
  site/AntDesign.Docs/Demos/Components/Affix/demo/Scroll.razor
  site/AntDesign.Docs/Demos/Components/Affix/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Affix/doc/index.zh-CN.md
Labels: PR: unreviewed

#1348 fix(module: tooltip): wrong popup direction
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/core/Component/overlay/type/PlacementType.cs
Labels: PR: unreviewed

#1342 fix: multiple bugs originating from js
  components/core/Base/AntComponentBase.cs
  components/core/Extensions/JSRuntimeExtensions.cs
  components/core/JsInterop/interop.ts
  components/date-picker/RangePicker.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/input-number/InputNumber.razor.cs
  components/input/Input.cs
  components/mentions/Mentions.razor.cs
  components/radio/Radio.razor.cs
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor
  components/select/internal/SelectContent.razor.cs
  components/slider/Slider.razor.cs
Labels: PR: reviewed-approved

#1351 fix(module:input): add WrapperStyle
  components/input/Input.cs
  site/AntDesign.Docs/Demos/Components/Input/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Input/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#1352 fix(module:avatar): text size calc regional independent
  components/avatar/Avatar.razor.cs
Labels: PR: reviewed-approved

#1356 fix(module:table): locale fix
  components/locales/en-GB.json
  components/locales/pl-PL.json
  components/table/TableLocale.cs
Labels: PR: reviewed-approved

#1361 fix(module: table): incorrect bool filter
  components/table/Column.razor.cs
Labels: PR: reviewed-approved

#1364 fix(module:avatar): size calculation & CssSizeLength functionality expansion
  components/avatar/Avatar.razor
  components/avatar/Avatar.razor.cs
  components/core/CssSizeLength.cs
  tests/AntDesign.Tests/Core/CssSizeLengthTests.cs
Labels: PR: unreviewed

#1362 fix(module:drawer): z-index has effect
  components/drawer/Drawer.razor
  components/drawer/Drawer.razor.cs
Labels: PR: unreviewed

#1359 changelog 0.8.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#1368 fix(module:select): enum default value protection
  components/select/Select.razor.cs
Labels: PR: reviewed-approved

#1373 fix(module: affix): can't affix while OffsetTop is zero
  components/affix/Affix.razor
  components/affix/Affix.razor.cs
  site/AntDesign.Docs/Demos/Components/Affix/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Affix/demo/Scroll.razor
Labels: PR: unreviewed

#1375 fix(module: input): binding data when the Enter key is pressed
  components/input/Input.cs
  components/input/TextArea.razor.cs
Labels: PR: unreviewed

#1376 fix(module: table): ellipsis can't work
  components/table/Table.razor.cs
Labels: PR: unreviewed

#1378 feat: add element component
  components/affix/Affix.razor.cs
  components/alert/Alert.razor.cs
  components/anchor/Anchor.razor.cs
  components/auto-complete/AutoComplete.razor.cs
  components/avatar/Avatar.razor.cs
  components/carousel/Carousel.razor.cs
  components/core/Component/Element/Element.cs
  components/core/Component/Overlay/Overlay.razor
  components/core/Component/Overlay/Overlay.razor.cs
  components/core/Component/Overlay/OverlayTrigger.razor
  components/core/Component/Overlay/OverlayTrigger.razor.cs
  components/core/Component/Overlay/type/PlacementDirection.cs
  components/core/Component/Overlay/type/PlacementType.cs
  components/core/Component/Overlay/type/TriggerBoundaryAdjustMode.cs
  components/core/Component/Overlay/type/TriggerType.cs
  components/core/JsInterop/DomRect.cs
  components/core/JsInterop/Element.cs
  components/core/JsInterop/HtmlElement.cs
  components/date-picker/internal/DatePickerBase.cs
  components/descriptions/Descriptions.razor.cs
  components/menu/SubMenu.razor.cs
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor.cs
  components/slider/Slider.razor.cs
  components/table/Table.razor.cs
  components/tabs/Tabs.razor.cs
  tests/AntDesign.Tests/tabs/TabsTests.cs
Labels: PR: unreviewed

#1372 fix(module: table): Unify FieldName, add DisplayAttribute for DiplayName, fix Filter for DataIndex
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/TableModels/FilterModel.cs
  components/table/TableModels/SortModel.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/DataIndex.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/Filter.razor
Labels: PR: reviewed-approved

#1379 fix: add Dispose lifecycle function to Dialog
  components/modal/core/Dialog.razor.cs
  components/modal/core/DialogWrapper.razor.cs
  components/modal/modalDialog/ModalFooter.razor.cs
Labels: PR: unreviewed

#1377 PassowrdInput - preserve focus and caret position when visibility is toggled
  components/core/Extensions/JSRuntimeExtensions.cs
  components/core/JsInterop/HtmlElement.cs
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/input/InputPassword.razor.cs
Labels: PR: reviewed-approved

#1382 fix(module:table): can not use DataIndex nullable mode with not nullable property
  components/table/Internal/ColumnExpressionHelper.cs
Labels: PR: reviewed-approved

#1385 fix(module:table): column header sorter not refresh after ClearSorter is called
  components/table/Column.razor.cs
Labels: PR: reviewed-approved

#1391 fix(module: form): duplicate validation message
  components/form/FormItem.razor.cs
Labels: PR: unreviewed

#1393 fix(module: tag): closable typo and delete mode
  components/tag/Tag.razor
  components/tag/Tag.razor.cs
  site/AntDesign.Docs/Demos/Components/Tag/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Tag/demo/Checkable.razor
  site/AntDesign.Docs/Demos/Components/Tag/demo/Controlled.razor
  site/AntDesign.Docs/Demos/Components/Tag/demo/Dynamic.razor
  site/AntDesign.Docs/Demos/Components/Tag/demo/Event.razor
  site/AntDesign.Docs/Demos/Components/Tag/demo/Hot.razor
  site/AntDesign.Docs/Demos/Components/Tag/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Tag/doc/index.zh-CN.md
Labels: PR: unreviewed

#1397 test(module:divider): divider tests
  tests/AntDesign.TestKit/AntDesignTestBase.cs
  tests/AntDesign.Tests/AntDesign.Tests.csproj
  tests/AntDesign.Tests/Divider/DividerTests.razor
  tests/AntDesign.Tests/_Imports.razor
Labels: PR: unreviewed

#1400 feat: support define modal's style in ModalOptions
  components/modal/config/ModalOptions.cs
  components/modal/modalDialog/ModalContainer.razor
  site/AntDesign.Docs/Demos/Components/Modal/demo/Modal_service_for_modal.razor
Labels: PR: reviewed-approved

#1386 refactor: replace PropertyAccessHelper to PathHelper
  components/core/Helpers/MemberPath/GetItemExpressionReplacer.cs
  components/core/Helpers/MemberPath/InvalidPathException.cs
  components/core/Helpers/MemberPath/PathCharState.cs
  components/core/Helpers/MemberPath/PathExtensions.cs
  components/core/Helpers/MemberPath/PathHelper.Generic.cs
  components/core/Helpers/MemberPath/PathHelper.cs
  components/core/Helpers/MemberPath/PathNode.cs
  components/core/Helpers/MemberPath/PathNodeType.cs
  components/core/Helpers/PropertyAccessHelper.cs
  components/select/Select.razor.cs
  components/select/internal/SelectItemPropertyHelper.cs
  components/table/Column.razor.cs
  components/table/Internal/ColumnDataIndexHelper.cs
  components/table/Internal/ColumnExpressionHelper.cs
  docs/member-path-helper.en-US.md
  docs/member-path-helper.zh-CN.md
  docs/path-based-property-access.en-US.md
  docs/path-based-property-access.zh-CN.md
  site/AntDesign.Docs/Demos/Components/Table/demo/DataIndex.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/data-index.md
  tests/AntDesign.Tests/Core/MemberPathTest.cs
  tests/AntDesign.Tests/Core/PropertyAccessHelperTest.cs
Labels: PR: reviewed-approved

#1394 fix(module: checkbox & switch) Checked parameter binding
  components/checkbox/Checkbox.razor
  components/checkbox/Checkbox.razor.cs
  components/checkbox/CheckboxGroup.razor
  components/checkbox/CheckboxGroup.razor.cs
  components/checkbox/CheckboxGroupMixedMode.cs
  components/core/Base/AntInputBoolComponentBase.cs
  components/switch/Switch.razor
  components/switch/Switch.razor.cs
  site/AntDesign.Docs/Demos/Components/Checkbox/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Checkbox/demo/Layout.razor
  site/AntDesign.Docs/Demos/Components/Checkbox/demo/MixedMode.md
  site/AntDesign.Docs/Demos/Components/Checkbox/demo/MixedMode.razor
  site/AntDesign.Docs/Demos/Components/Checkbox/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Checkbox/doc/index.zh-CN.md
  site/AntDesign.Docs/Demos/Components/Switch/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Switch/demo/Control.md
  site/AntDesign.Docs/Demos/Components/Switch/demo/Control.razor
  site/AntDesign.Docs/Demos/Components/Switch/demo/Disable.razor
  site/AntDesign.Docs/Demos/Components/Switch/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Switch/doc/index.zh-CN.md
  tests/AntDesign.Tests/AntDesign.Tests.csproj
  tests/AntDesign.Tests/Checkbox/CheckboxGroupTests.razor
  tests/AntDesign.Tests/Checkbox/CheckboxTests.razor
  tests/AntDesign.Tests/Divider/DividerTests.razor
  tests/AntDesign.Tests/Switch/SwitchTests.razor
  tests/AntDesign.Tests/_Imports.razor
Labels: PR: reviewed-approved

#1409 #1366 Allow custom pagination template
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/CustomPagination.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/custom-pagination.md
Labels: PR: reviewed-approved

#1410 #1346 Columns Show/Hide functionality
  components/table/Column.razor
  components/table/ColumnBase.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/ToggleColumn.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/toggle-column.md
Labels: PR: reviewed-approved

#1419 fix(module:select): OnDataSourceChange called when expected
  components/select/Select.razor.cs
  tests/AntDesign.Tests/Select/Actions/Select.OnDataSourceChangeTests.razor
  tests/AntDesign.Tests/_Imports.razor
Labels: PR: reviewed-approved

#1421 fix(module:overlay): Table filter pop up
  components/core/Component/Overlay/Overlay.razor.cs
  components/core/Component/Overlay/OverlayTrigger.razor.cs
Labels: PR: unreviewed

#1392 feat: use ResizeObserver Api instead of window.resize
  components/core/Extensions/JSRuntimeExtensions.cs
  components/core/JsInterop/DomEventService.cs
  components/core/JsInterop/DomEventSubscription.cs
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/ObservableApi/BoxSize.cs
  components/core/JsInterop/ObservableApi/ResizeObserverEntry.cs
  components/core/JsInterop/ObservableApi/observableApi.ts
  components/core/JsInterop/ObservableApi/resizeObserver.ts
  components/core/JsInterop/interop.ts
  components/select/internal/SelectContent.razor.cs
  package.json
Labels: PR: unreviewed

#1423 fix(module: table): check null in set sorter method
  components/table/Column.razor.cs
Labels: PR: unreviewed

#1389 fix(module:datepicker): validate manually entered date against format
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/date-picker/DatePicker.Razor.cs
  components/date-picker/DatePicker.razor
  components/date-picker/RangePicker.razor
  components/date-picker/RangePicker.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerInput.razor
  components/date-picker/locale/DatePickerLocale.cs
  components/date-picker/locale/FormatAnalyzer.cs
  tests/AntDesign.Tests/DatePicker/locale/FormatAnalyzerTests.cs
Labels: PR: reviewed-approved

#1420 fix(module: overlay): issues in boundaryAdjustMode
  components/core/Component/Overlay/Overlay.razor.cs
  components/menu/SubMenu.razor
Labels: PR: unreviewed

#1432 fix(module: cascader): incorrect size
  components/cascader/Cascader.razor.cs
  tests/AntDesign.Tests/Cascader/CascaderTests.razor
Labels: PR: unreviewed

#1434 fix(module: table): fix wrong spell for TableFilterCompareOperator.EndsWith
  components/table/Column.razor
  components/table/FilterExpression/StringFilterExpression.cs
  components/table/TableFilter.cs
Labels: PR: unreviewed

#1437 fix(module: cascader): add SelectedNodesChanged and invoke it after clear selected
  components/cascader/Cascader.razor.cs
  components/core/Base/AntInputComponentBase.cs
  site/AntDesign.Docs/Demos/Components/Cascader/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Cascader/demo/Change.razor
  site/AntDesign.Docs/Demos/Components/Cascader/demo/Default.razor
  site/AntDesign.Docs/Demos/Components/Cascader/demo/Disabled.razor
  site/AntDesign.Docs/Demos/Components/Cascader/demo/Hover.razor
  site/AntDesign.Docs/_Imports.razor
Labels: PR: unreviewed
