Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2021-11, with the labels that each got.

#2068 fix(module: calendar): DateFullCellRender throws an exception (#2067)
  components/calendar/internal/CalendarPanelChooser.razor
Labels: PR: reviewed-approved

#2075 feat(module: tabs): add context menu and page config for reusetabs
  components/core/Component/Overlay/OverlayTrigger.razor.cs
  components/locale-provider/Locale.cs
  components/locales/en-US.json
  components/locales/zh-CN.json
  components/tabs/Reuse/ReuseTabs.razor
  components/tabs/Reuse/ReuseTabs.razor.cs
  components/tabs/Reuse/ReuseTabsLocale.cs
  components/tabs/Reuse/ReuseTabsPageAttribute.cs
  components/tabs/Reuse/ReuseTabsPageItem.cs
  components/tabs/Reuse/ReuseTabsRouteView.cs
  components/tabs/TabPane.razor
  components/tabs/TabPane.razor.cs
  components/tabs/Tabs.razor.cs
  site/AntDesign.Docs/Demos/Components/Tabs/demo/ContextMenu.razor
  site/AntDesign.Docs/Demos/Components/Tabs/demo/contextmenu.md
  site/AntDesign.Docs/Demos/Components/Tabs/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Tabs/doc/index.zh-CN.md
  tests/AntDesign.TestApp/Client/Pages/Authentication.razor
  tests/AntDesign.TestApp/Client/Pages/Counter.razor
  tests/AntDesign.TestApp/Client/Pages/FetchData.razor
  tests/AntDesign.TestApp/Client/Pages/Index.razor
  tests/AntDesign.TestApp/Client/Shared/MainLayout.razor
Labels: PR: unreviewed

#2078 fix(module: descriptions): header styles
  components/descriptions/Descriptions.razor
Labels: PR: unreviewed

#2081 changelog 0.10.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#2086 Improved project readme and details
  README.md
Labels: PR: reviewed-approved

#2094 fix(module:locale-provider): fix culture not found
  components/locale-provider/LocaleProvider.cs
Labels: PR: reviewed-approved

#2098 fix(module: typography): Fix `OnCopy` not invoked when `Text` is null or empty
  components/typography/TypographyBase.cs
Labels: PR: unreviewed

#2105 fix(module: cascader): crashes when options is null (#563)
  components/cascader/Cascader.razor.cs
Labels: PR: reviewed-approved

#2108 feat(module: cascader): display indicator when options is null or empty
  components/cascader/Cascader.razor
  components/cascader/Cascader.razor.cs
Labels: PR: reviewed-approved

#2118 fix(module:typography): fix copy
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/modules/dom/manipulationHelper.ts
  components/icon/IconService.cs
  components/typography/TypographyBase.cs
  tests/AntDesign.Tests/Card/Card.Render.Tests.razor
  tests/AntDesign.Tests/Menu/Menu.Inline.Tests.razor
  tests/AntDesign.Tests/Tag/TagTests.razor
  tests/AntDesign.Tests/button/ButtonTests.razor
Labels: PR: unreviewed

#2142 fix(module: radio): `Radio` in a group should always keep `Disabled` …
  components/radio/Radio.razor.cs
  components/radio/RadioGroup.razor.cs
Labels: PR: reviewed-approved

#2133 fix(module: tree)：Update check status when set [CheckedKeys] property
  components/tree/Tree.razor.cs
Labels: PR: reviewed-approved

#2121 fix(module:select): it's incorrect to detect type this way, it throws when class inheritance is used
  components/select/Select.razor.cs
Labels: PR: partially-approved
