Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2021-01, with the labels that each got.

#941 Tree Bug fix and New feature
  components/tree/IRendered.cs
  components/tree/Tree.razor
  components/tree/Tree.razor.cs
  components/tree/TreeNode.razor
  components/tree/TreeNode.razor.cs
  components/tree/TreeNodeCheckbox.razor
  components/tree/TreeNodeCheckbox.razor.cs
  components/tree/TreeNodeSwitcher.razor
  components/tree/TreeNodeSwitcher.razor.cs
  components/tree/TreeNodeTitle.razor
  components/tree/TreeNodeTitle.razor.cs
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/BasicControlled.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Event.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Line.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Modify.md
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Modify.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Property.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/Template.razor
  site/AntBlazor.Docs/Demos/Components/Tree/demo/line.md
  site/AntBlazor.Docs/Demos/Components/Tree/demo/property.md
  site/AntBlazor.Docs/Demos/Components/Tree/demo/template.md
  site/AntBlazor.Docs/Utils/IsExternalInit.cs
Labels: PR: unreviewed

#948 ci: create issue labeled reply
  .github/workflows/issue-labeled.yml
Labels: PR: reviewed-approved

#950 fix(module: cascader): duplicated highlighting for the same label
  components/cascader/Cascader.razor
Labels: PR: reviewed-approved

#933 fix(module:DatePicker&RangePicker): OneOf to TValue, default value for picker, optimizations
  components/date-picker/DatePicker.Razor.cs
  components/date-picker/DatePicker.razor
  components/date-picker/RangePicker.razor.cs
  components/date-picker/RangePickerDefaults.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerPanelBase.cs
  components/date-picker/internal/DatePickerPanelChooser.razor
  components/date-picker/internal/DatePickerTemplate.razor.cs
  components/date-picker/internal/DatePickerYearPanel.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Disabled.razor
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Format.razor
  tests/DatePicker/RangePickerDefaultsTests.cs
Labels: PR: unreviewed

#955 chore: sync ant-design v4.10.1
  components/notification/style/index.less
Labels: PR: unreviewed

#956 fix(module: tree): add missing ComponentBase
  components/tree/TreeIndent.razor
  components/tree/TreeIndent.razor.cs
  components/tree/TreeNode.razor
  components/tree/TreeNode.razor.cs
  components/tree/TreeNodeCheckbox.razor
  components/tree/TreeNodeCheckbox.razor.cs
  components/tree/TreeNodeSwitcher.razor
  components/tree/TreeNodeSwitcher.razor.cs
  components/tree/TreeNodeTitle.razor
  components/tree/TreeNodeTitle.razor.cs
Labels: PR: unreviewed

#957 feat(module: table): add ellipsis column
  components/table/Column.razor
  components/table/ColumnBase.cs
  components/table/ITable.cs
  components/table/Table.razor
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Ellipsis.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/FixedColumnsHeader.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/ellipsis.md
Labels: PR: unreviewed

#959 ListItemMeta component should support a ReactNode format
  components/list/ListItemMeta.razor
  components/list/ListItemMeta.razor.cs
Labels: PR: reviewed-approved

#962 fix(module: table): sorter works incorrectly
  components/table/ColumnBase.cs
  components/table/ColumnContext.cs
  components/table/Table.razor
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Head_.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/head.md
Labels: PR: unreviewed

#965 fix(module: table): exception if field is null
  components/table/Column.razor
  components/table/ColumnContext.cs
Labels: PR: unreviewed

#960 add StopPropagation of OnClick to Button Component
  components/button/Button.razor
  components/button/Button.razor.cs
Labels: PR: reviewed-approved

#969 feat(module: table): add custom comparer
  components/table/Column.razor.cs
  components/table/TableModels/SortModel.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Blazor.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/CustomSort.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/custom-sort.md
Labels: PR: reviewed-approved

#972 fix(module: range-picker): throw exception when has default value
  components/date-picker/RangePicker.razor.cs
Labels: PR: unreviewed

#985 Fix table with ExpandedTemplate with no data showing No Data with 1 c…
  components/table/Table.razor
Labels: PR: reviewed-approved

#973 fix(module: date-picker): prevent the year out of range
  components/core/Helpers/DateHelper.cs
  components/date-picker/internal/DatePickerDatePanel.razor
  components/date-picker/internal/DatePickerDatetimePanel.razor
  components/date-picker/internal/DatePickerDecadePanel.razor
  components/date-picker/internal/DatePickerHeader.razor
  components/date-picker/internal/DatePickerMonthPanel.razor
  components/date-picker/internal/DatePickerPanelBase.cs
  components/date-picker/internal/DatePickerQuarterPanel.razor
  components/date-picker/internal/DatePickerTemplate.razor
  components/date-picker/internal/DatePickerTemplate.razor.cs
  components/date-picker/internal/DatePickerYearPanel.razor
  components/locales/zh-CN.json
  site/AntBlazor.Docs/Demos/Components/DatePicker/demo/Basic.razor
Labels: PR: unreviewed

#980 fix(module: cascader): re-initialize options after options is changed
  components/cascader/Cascader.razor.cs
Labels: PR: reviewed-approved

#990 fix(module:alert): Change span to div when applicable for better responsive experience
  components/alert/Alert.razor
Labels: PR: reviewed-approved

#989 fix(module:overlay): getFirstChildDomInfo will return passed dom instead of body when no child element exists
  components/core/JsInterop/interop.ts
Labels: PR: reviewed-approved

#993 fix(module:calendar): critical exception for ChangePickerValue
  components/calendar/internal/CalendarPanelChooser.razor
Labels: PR: merged

#1001 fix(module: upload): file list style
  components/upload/Upload.razor
  components/upload/Upload.razor.cs
  components/upload/UploadButton.razor
  components/upload/UploadButton.razor.cs
  components/upload/UploadFileItem.cs
  site/AntBlazor.Docs/Demos/Components/Upload/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/Upload/demo/Directory.razor
  site/AntBlazor.Docs/Demos/Components/Upload/demo/PictureCard.razor
Labels: PR: unreviewed

#1005 fix(module: back-top): fix visible styles
  components/back-top/BackTop.razor
  components/back-top/BackTop.razor.cs
Labels: PR: unreviewed

#1006 docs: scroll to hash anchor after pages are rendered
  components/core/Extensions/JSRuntimeExtensions.cs
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  site/AntBlazor.Docs/Routing/ConventionRouter.cs
Labels: PR: unreviewed

#1007 fix(module: layout): missing trigger when sider open from zero-width mode
  components/layout/Sider.razor
  components/layout/Sider.razor.cs
Labels: PR: unreviewed

#1008 fix(module:overlay): Interop delElementFrom() exception on page refresh
  components/core/Component/overlay/Overlay.razor.cs
  components/core/Component/overlay/OverlayTrigger.razor.cs
Labels: PR: reviewed-approved

#1009 chore: bUnit update to 1.0.0-preview-01
  tests/AntDesign.Tests.csproj
  tests/table/TableTests.cs
  tests/tabs/TabsTests.cs
Labels: PR: reviewed-approved

#999 feat(module: table): add DataIndex parameter
  components/core/Helpers/PropertyAccessHelper.cs
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/ColumnBase.cs
  components/table/Internal/ColumnDataIndexHelper.cs
  components/table/Table.razor
  components/table/TableModels/DataIndexSortModel.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/DataIndex.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/custom-sort.md
  site/AntBlazor.Docs/Demos/Components/Table/demo/data-index.md
Labels: PR: unreviewed

#1002 Table增加属性ExpandIconColumnIndex
  components/table/Column.razor
  components/table/ColumnBase.cs
  components/table/ITable.cs
  components/table/Table.razor
  components/table/Table.razor.cs
Labels: PR: reviewed-approved

#1012 fix: select issue with multiple modals
  components/modal/core/Dialog.razor
  components/modal/core/Dialog.razor.cs
  components/modal/core/DialogWrapper.razor
  components/modal/modalDialog/Modal.razor
Labels: PR: reviewed-approved

#1019 feat(module: table): support multiple sorter
  components/table/Column.razor.cs
  components/table/Internal/ColumnDataIndexHelper.cs
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/MultipleSorter.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/multiple-sorter.md
Labels: PR: unreviewed

#1017 feat(module:menudivider): Add Menu divider
  components/menu/MenuDivider.razor
  site/AntBlazor.Docs/Demos/Components/Dropdown/demo/DropdownButtonDemo.razor
  site/AntBlazor.Docs/Demos/Components/Dropdown/demo/Item.razor
  site/AntBlazor.Docs/Demos/Components/Menu/demo/Horizontal.razor
Labels: PR: reviewed-approved

#1020 fix(module: table): selection was broken with scroll y
  components/table/Selection.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/FixedHeader.razor
Labels: PR: unreviewed

#1027 fix(module:menu): fix loop on same route & performance & duplicate highlight
  components/menu/Menu.razor
  components/menu/Menu.razor.cs
  components/menu/MenuItem.razor
  components/menu/MenuItem.razor.cs
  components/menu/MenuLink.cs
Labels: PR: reviewed-approved

#987 Added Static class IconType for intellisense
  components/icon/IconType.cs
  site/AntDesign.Docs.Build.CLI/Utils/StaticClassGenerator.cs
Labels: PR: unreviewed

#1011 build: standalone document generation
  Directory.Build.props
  components/AntDesign.csproj
  package.json
  site/AntBlazor.Docs/AntDesign.Docs.csproj
  site/AntDesign.Docs.Server/AntDesign.Docs.Server.csproj
  site/AntDesign.Docs.Wasm/AntDesign.Docs.Wasm.csproj
Labels: PR: reviewed-approved

#1030 feat(module: card): add a separate action component
  components/card/Card.razor
  components/card/Card.razor.cs
  components/card/CardAction.razor
  components/card/CardAction.razor.cs
  components/grid/GridCol.cs
  site/AntBlazor.Docs/Demos/Components/Card/demo/Inner.razor
  site/AntBlazor.Docs/Demos/Components/Card/demo/Support.razor
  site/AntBlazor.Docs/Demos/Components/Card/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Card/doc/index.zh-CN.md
  site/AntBlazor.Docs/Shared/MainHeader.razor
  site/AntBlazor.Docs/Shared/MainLayout.razor
Labels: PR: unreviewed

#778 table add sortway to support column sort with single or multiple way
  components/calendar/internal/CalendarHeader.razor
  components/core/SortDirection.cs
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/IFieldColumn.cs
  components/table/ITable.cs
  components/table/Internal/ColumnDataIndexHelper.cs
  components/table/Table.razor.cs
  components/table/TableModels/DataIndexSortModel.cs
  components/table/TableModels/ITableSortModel.cs
  components/table/TableModels/SortModel.cs
  components/table/TableModels/SortType.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/Head_.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/MultipleSorter.razor
Labels: PR: unreviewed

#1031 Feat/row class name
  components/table/Table.razor
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/CustomRowStyle.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/custom-row-style.md
Labels: PR: reviewed-approved

#1037 fix(module: tabs): ink delay change
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
Labels: PR: unreviewed

#1035 fix(module:form): form.reset() will make new editContext
  components/form/Form.razor.cs
Labels: PR: reviewed-approved

#1038 feat(module: image): add image component
  components/AntDesign.csproj
  components/components.less
  components/core/AntContainer.razor
  components/core/Extensions/ServiceCollectionExtensions.cs
  components/image/Image.razor
  components/image/Image.razor.cs
  components/image/ImageLocale.cs
  components/image/ImagePreview.razor
  components/image/ImagePreview.razor.cs
  components/image/ImagePreviewContainer.razor
  components/image/ImagePreviewContainer.razor.cs
  components/image/ImageService.cs
  components/image/style/entry.less
  components/locale-provider/Locale.cs
  components/locales/en-US.json
  components/locales/zh-CN.json
  components/space/SpaceItem.razor.cs
  site/AntBlazor.Docs/Demos/Components/Image/demo/Basic.razor
  site/AntBlazor.Docs/Demos/Components/Image/demo/Fallback.razor
  site/AntBlazor.Docs/Demos/Components/Image/demo/Placeholder.razor
  site/AntBlazor.Docs/Demos/Components/Image/demo/basic.md
  site/AntBlazor.Docs/Demos/Components/Image/demo/fallback.md
  site/AntBlazor.Docs/Demos/Components/Image/demo/placeholder.md
  site/AntBlazor.Docs/Demos/Components/Image/doc/index.en-US.md
  site/AntBlazor.Docs/Demos/Components/Image/doc/index.zh-CN.md
Labels: PR: unreviewed

#1039 chore: sync ant-design v4.11.1
  components/badge/style/index.less
  components/button/style/index.less
  components/card/style/index.less
  components/drawer/style/drawer.less
  components/dropdown/style/rtl.less
  components/empty/style/index.less
  components/image/style/index.less
  components/menu/style/dark.less
  components/menu/style/index.less
  components/result/style/index.less
  components/select/style/multiple.less
  components/style/themes/compact.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/style/bordered.less
  components/table/style/index.less
  components/tree/style/mixin.less
Labels: PR: unreviewed

#1040 fix(module:table) Table exception on refresh
  components/core/Component/overlay/Overlay.razor.cs
  components/table/Table.razor.cs
  site/AntBlazor.Docs/Demos/Components/Slider/demo/Basic.razor
Labels: PR: reviewed-approved

#1042 feat(module image): add animation for image preview
  components/image/ImagePreview.razor
  components/image/ImagePreview.razor.cs
  components/modal/config/DialogOptionsBase.cs
  components/modal/core/Dialog.razor
Labels: PR: reviewed-approved

#1048 fix: Input, InputNumber, TextArea disabled attribute fix
  components/input-number/InputNumber.razor
  components/input/Input.cs
  components/input/TextArea.razor
Labels: PR: reviewed-approved

#1058 fix(module: table): mistaken sortable
  components/table/Column.razor.cs
  site/AntBlazor.Docs/Demos/Components/Table/demo/head.md
Labels: PR: unreviewed

#1059 feat(module: image): add preview group
  components/image/Image.razor
  components/image/Image.razor.cs
  components/image/ImagePreview.razor
  components/image/ImagePreview.razor.cs
  components/image/ImagePreviewContainer.razor
  components/image/ImagePreviewContainer.razor.cs
  components/image/ImagePreviewGroup.razor
  components/image/ImagePreviewGroup.razor.cs
  components/image/ImageRef.cs
  components/image/ImageService.cs
  site/AntBlazor.Docs/Demos/Components/Image/demo/PreviewGroup.razor
  site/AntBlazor.Docs/Demos/Components/Image/demo/PreviewSrc.razor
  site/AntBlazor.Docs/Demos/Components/Image/demo/previewGroup.md
  site/AntBlazor.Docs/Demos/Components/Image/demo/previewSrc.md
Labels: PR: unreviewed

#1060 fix(module: image): disables previewing error images and hides buttons when there is only one image
  components/image/Image.razor.cs
  components/image/ImagePreview.razor
  components/image/ImagePreview.razor.cs
  components/image/ImagePreviewGroup.razor.cs
Labels: PR: unreviewed

#1056 feat: access object's property by path-based string
  components/core/Helpers/PropertyAccessHelper.cs
  components/table/Internal/ColumnDataIndexHelper.cs
  docs/path-based-property-access.en-US.md
  docs/path-based-property-access.zh-CN.md
  site/AntBlazor.Docs/Demos/Components/Table/demo/DataIndex.razor
  site/AntBlazor.Docs/Demos/Components/Table/demo/custom-row-style.md
  site/AntBlazor.Docs/Demos/Components/Table/demo/data-index.md
  tests/Core/PropertyAccessHelperTest.cs
Labels: PR: unreviewed
