Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2021-03, with the labels that each got.

#1155 fix(module:TextArea): sizing bug for components outside viewport
  .github/workflows/nightly-build.yml
  components/core/EventCallbackArgs/OnResizeEventArgs.cs
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/input/TextArea.razor
  components/input/TextArea.razor.cs
Labels: PR: unreviewed

#1186 fix: animation classs name change of Modal, Message and Notification componments
  components/message/type/MessageAnimationType.cs
  components/modal/type/ModalAnimation.cs
  components/notification/type/AnimationType.cs
Labels: PR: reviewed-approved

#1175 Feat/table on row and cell
  components/table/Column.razor
  components/table/Column.razor.cs
  components/table/Table.razor
  components/table/Table.razor.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/CustomRowStyle.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/OnRowAndOnCell.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/on-row-and-on-cell.md
  site/AntDesign.Docs/Demos/Components/Table/doc/index.en-US.md
Labels: PR: reviewed-approved

#1188 fix(module: table): tree data error
  components/table/Table.razor.cs
Labels: PR: unreviewed

#1191 fix(module: Select) bind value change lock, tags and labels fix, overlay reposition
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor
Labels: PR: reviewed-approved

#1190 docs: changelog for 0.7.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#1195 fix(module:select): Loading animation toggling properly
  components/input/Search.razor.cs
Labels: PR: reviewed-approved

#1199 fix(module: table): doesn't refresh when expand row
  components/table/Column.razor
Labels: PR: unreviewed

#1200 fix(module: table): bring OnRowClick back
  components/table/Table.razor
  components/table/Table.razor.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Basic.razor
Labels: PR: unreviewed

#1202 feat(module: table): add a method to get query model
  components/table/ITable.cs
  components/table/Table.razor.cs
  components/table/TableModels/QueryModel.cs
Labels: PR: unreviewed

#1196 Select enter on form
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/interop.ts
  components/select/Select.razor.cs
  components/select/internal/SelectContent.razor.cs
Labels: PR: reviewed-approved

#1203 changelog: 0.7.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#1205 chore: add github actions for auto preview
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/preview-start.yml
Labels: PR: unreviewed

#1209 Select reset value
  components/select/Select.razor.cs
Labels: PR: reviewed-approved

#1211 fix(module: table): invoke OnChange twice on pagination was changed
  .github/workflows/preview-build.yml
  .github/workflows/pull-request.yml
  components/table/Table.razor.Pagination.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Blazor.razor
Labels: PR: unreviewed

#1214 fix(module:select): Compiled method .ToString() was throwing AmbigiousMethod
  components/select/internal/SelectItemPropertyHelper.cs
Labels: PR: reviewed-approved

#1215 fix(module: divider): style was default to plain
  components/divider/Divider.razor
  components/divider/Divider.razor.cs
  site/AntDesign.Docs/Demos/Components/Divider/demo/Without.razor
Labels: PR: unreviewed

#1216 fix(module: badge): color behaviour
  components/badge/Badge.razor
  components/badge/Badge.razor.cs
  site/AntDesign.Docs/Demos/Components/Badge/demo/Change.razor
  site/AntDesign.Docs/Demos/Components/Badge/demo/Colorful.razor
  site/AntDesign.Docs/Demos/Components/Badge/demo/NoWrapper.razor
  site/AntDesign.Docs/Demos/Components/Badge/demo/no-wrapper.md
Labels: PR: unreviewed

#1217 docs: add contributors list
  .github/workflows/preview-build.yml
  site/AntDesign.Docs/Pages/Components.razor
  site/AntDesign.Docs/Pages/Components.razor.cs
  site/AntDesign.Docs/Pages/Docs.razor
  site/AntDesign.Docs/Pages/Docs.razor.cs
  site/AntDesign.Docs/Shared/CodeBox.razor
  site/AntDesign.Docs/Shared/ContributorsList.razor
  site/AntDesign.Docs/Shared/ContributorsList.razor.cs
Labels: PR: unreviewed

#1218 feat(module: table): add summary
  components/table/ColumnBase.cs
  components/table/ITable.cs
  components/table/SummaryCell.razor
  components/table/SummaryRow.razor
  components/table/Table.razor
  components/table/Table.razor.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Summary.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/summary.md
Labels: PR: unreviewed

#1219 fix(module:upload): Disable and delete button fix
  components/upload/Upload.razor
  components/upload/UploadButton.razor.cs
Labels: PR: reviewed-approved

#1224 docs: fix some demo issues
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/DynamicTrigger.razor
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/Icon.razor
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/Locale.razor
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/basic.md
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/dynamic-trigger.md
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/icon.md
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/locale.md
  site/AntDesign.Docs/Demos/Components/Popconfirm/demo/placement.md
  site/AntDesign.Docs/Demos/Components/Tag/demo/Dynamic.razor
Labels: PR: unreviewed

#1227 Add ability to use OverlayTrigger in tests
  components/core/JsInterop/DomEventService.cs
  tests/AntDesign.Tests.csproj
  tests/AntDesignTestBase.cs
  tests/TestDomEventService.cs
  tests/overlay/OverlayTriggerTests.cs
Labels: PR: reviewed-approved

#1232 fix(module: column): clicking on a blank space couldn't close filter panel
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/table/Column.razor
Labels: PR: reviewed-approved

#1235 feat(module: InputNumber): Add long click and keyboard event
  components/input-number/InputNumber.razor
  components/input-number/InputNumber.razor.cs
Labels: PR: reviewed-approved

#1220 refactor(module: pagination): port from react version
  components/pagination/Pagination.razor
  components/pagination/Pagination.razor.cs
  components/pagination/PaginationDefault.razor
  components/pagination/PaginationDefault.razor.cs
  components/pagination/PaginationEventArgs.cs
  components/pagination/PaginationItem.razor
  components/pagination/PaginationItem.razor.cs
  components/pagination/PaginationItemRenderContext.cs
  components/pagination/PaginationItemType.cs
  components/pagination/PaginationOptions.razor
  components/pagination/PaginationOptions.razor.cs
  components/pagination/PaginationPager.razor
  components/pagination/PaginationSimple.razor
  components/pagination/PaginationSimple.razor.cs
  components/pagination/PaginationTotalContext.cs
  components/table/Table.razor
  components/table/Table.razor.Pagination.cs
  site/AntDesign.Docs/Demos/Components/Pagination/demo/All.razor
  site/AntDesign.Docs/Demos/Components/Pagination/demo/Changer.razor
  site/AntDesign.Docs/Demos/Components/Pagination/demo/Controlled.razor
  site/AntDesign.Docs/Demos/Components/Pagination/demo/CustomIcon.razor
  site/AntDesign.Docs/Demos/Components/Pagination/demo/ItemRender.razor
  site/AntDesign.Docs/Demos/Components/Pagination/demo/Jump.razor
  site/AntDesign.Docs/Demos/Components/Pagination/demo/Mini.razor
  site/AntDesign.Docs/Demos/Components/Pagination/demo/all.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/basic.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/changer.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/controlled.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/customIcon.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/itemRender.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/jump.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/mini.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/more.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/simple.md
  site/AntDesign.Docs/Demos/Components/Pagination/demo/total.md
  site/AntDesign.Docs/Demos/Components/Pagination/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Pagination/doc/index.zh-CN.md
  site/AntDesign.Docs/Demos/Components/Table/demo/RouterPagging.razor
Labels: PR: reviewed-approved

#1243 Fix animation
  components/auto-complete/AutoComplete.razor
  components/back-top/BackTop.razor.cs
  components/cascader/Cascader.razor
  components/core/Component/overlay/OverlayTrigger.razor.cs
  components/date-picker/DatePicker.razor
  components/date-picker/RangePicker.razor
  components/menu/SubMenu.razor.cs
  components/popconfirm/Popconfirm.razor.cs
  components/popover/Popover.razor.cs
  components/select/Select.razor
  components/tooltip/Tooltip.razor.cs
  site/AntDesign.Docs/Demos/Components/Popover/demo/Placement.razor
Labels: PR: reviewed-approved

#1241 Apply trailing color
  components/progress/Progress.razor
  components/progress/Progress.razor.cs
  site/AntDesign.Docs/Demos/Components/Progress/demo/TrailColor.md
  site/AntDesign.Docs/Demos/Components/Progress/demo/TrailColor.razor
  site/AntDesign.Docs/Demos/Components/Progress/doc/index.en-US.md
Labels: PR: reviewed-approved

#1245 add bulmarazor link
  site/AntDesign.Docs/Shared/MainFooter.razor
Labels: PR: reviewed-approved

#1247 changelog: 0.7.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#1249 chore: sync ant-design v4.14.0
  components/carousel/style/index.less
  components/form/style/index.less
  components/input/style/affix.less
  components/modal/style/confirm.less
  components/modal/style/modal.less
  components/modal/style/rtl.less
  components/select/style/multiple.less
  components/select/style/rtl.less
  components/style/themes/default.less
  components/table/style/index.less
  components/tabs/style/card.less
  components/tabs/style/index.less
  components/tabs/style/position.less
  components/tabs/style/rtl.less
Labels: PR: unreviewed

#1260 fix(module: rangepicker): [selected date on end picker]、[quarter panel's ranges] are incorrect
  components/date-picker/internal/DatePickerPanelBase.cs
  components/date-picker/internal/DatePickerTemplate.razor.cs
Labels: PR: partially-approved

#1269 fix(module: cascader): style and class properties
  components/cascader/Cascader.razor
  components/cascader/Cascader.razor.cs
Labels: PR: unreviewed

#1272 add the copyright of .NET Foundation
  LICENSE
  README-zh_CN.md
  README.md
  components/AntDesign.csproj
  site/AntDesign.Docs/Shared/MainFooter.razor
Labels: PR: unreviewed

#1275 bug: The correction tree does not expand correctly
  components/tree/TreeNode.razor
Labels: PR: unreviewed

#1274 fix(module: dropdown): Animations for down and up are inverse
  components/core/Component/overlay/type/PlacementType.cs
Labels: PR: unreviewed

#1268 Feat/tag
  components/core/CloseEventArgs.cs
  components/tag/Tag.razor.cs
  site/AntDesign.Docs/Demos/Components/Tag/demo/Event.md
  site/AntDesign.Docs/Demos/Components/Tag/demo/Event.razor
Labels: PR: reviewed-approved

#1280 changelog 0.7.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#1281 chore: sync ant-design v4.15.0
  components/checkbox/style/mixin.less
  components/pagination/style/index.less
  components/radio/style/index.less
  components/steps/style/progress.less
  components/style/themes/compact.less
  components/style/themes/default.less
  components/tabs/style/index.less
  components/tabs/style/position.less
  components/tag/style/index.less
  components/transfer/style/index.less
Labels: PR: unreviewed
