Repository ant-design-blazor/ant-design-blazor, pull requests merged in 2021-07, with the labels that each got.

#1699 fix(module: checkbox): fix the test following up PR #1689
  tests/AntDesign.TestKit/AntDesign.TestKit.csproj
  tests/AntDesign.Tests/Checkbox/CheckboxGroupTests.razor
  tests/AntDesign.Tests/Checkbox/CheckboxTests.razor
Labels: PR: unreviewed

#1695 feat(module: table): support expanding all items in table
  components/table/Table.razor
  components/table/Table.razor.cs
Labels: PR: reviewed-approved

#1704 feat(module: tabs): add reuse tabs routeview
  components/tabs/Reuse/IReuseTabsPage.cs
  components/tabs/Reuse/ReuseTabs.razor
  components/tabs/Reuse/ReuseTabs.razor.cs
  components/tabs/Reuse/ReuseTabsPageItem.cs
  components/tabs/Reuse/ReuseTabsPageTitleAttribute.cs
  components/tabs/Reuse/ReuseTabsRouteView.cs
Labels: PR: unreviewed

#1705 fix(module: upload): treat 2xx response codes success
  components/core/JsInterop/interop.ts
Labels: PR: reviewed-approved

#1692 fix(module:overlay): better judge whether mouse is inside the overlay when click
  components/core/Component/Overlay/Overlay.razor
  components/core/Component/Overlay/Overlay.razor.cs
  components/core/Component/Overlay/OverlayTrigger.razor
  components/core/Component/Overlay/OverlayTrigger.razor.cs
  components/dropdown/Dropdown.razor
  components/menu/internal/SubMenuTrigger.razor
  components/popconfirm/Popconfirm.razor
  components/popover/Popover.razor
  components/tooltip/Tooltip.razor
Labels: PR: reviewed-approved

#1708 fix(module: tabs): Exception caused by cascade assignment to TabTemplate
  components/tabs/Reuse/ReuseTabs.razor
Labels: PR: unreviewed

#1710 fix(module:locale-provider): add missing nodes default values
  components/empty/EmptyLocale.cs
  components/form/FormLocale.cs
  components/icon/IconLocale.cs
  components/image/ImageLocale.cs
  components/locale-provider/GlobalLocale.cs
  components/locale-provider/Locale.cs
  components/modal/confirmDialog/ConfirmLocale.cs
  components/modal/modalDialog/ModalLocale.cs
  components/page-header/PageHeaderLocale.cs
  components/popconfirm/PopconfirmLocale.cs
  components/table/TableLocale.cs
  components/time-picker/TimePickerLocale.cs
  components/transfer/TransferLocale.cs
  components/typography/TextLocale.cs
  components/upload/UploadLocale.cs
Labels: PR: reviewed-approved

#1709 Russian locale resources additions
  components/locales/ru-RU.json
Labels: PR: reviewed-approved

#1714 fix(module:CountDown): fix CountDown OnFinish callback exception(#1712)
  components/statistic/CountDown.razor.cs
Labels: PR: reviewed-approved

#1717 UploadFileItem Provide default configuration: ignore case
  components/upload/UploadFileItem.cs
Labels: PR: reviewed-approved

#1581 feat(module: tabs): scroll over tab pane
  components/tabs/Tabs.razor
  components/tabs/Tabs.razor.cs
Labels: PR: reviewed-approved

#1722 feat(module: tree): support check all from code
  components/tree/Tree.razor.cs
Labels: PR: reviewed-approved

#1720 fix(module:select): allow change both data source and value in one render period
  components/select/Select.razor.cs
Labels: PR: partially-approved

#1517 refactor(module: tree): port from react
  components/transfer/Transfer.razor
  components/tree/DirectoryTree.cs
  components/tree/IRendered.cs
  components/tree/Tree.razor
  components/tree/Tree.razor.cs
  components/tree/TreeEventArgs.cs
  components/tree/TreeIndent.razor
  components/tree/TreeIndent.razor.cs
  components/tree/TreeNode.razor
  components/tree/TreeNode.razor.cs
  components/tree/TreeNodeCheckbox.razor.cs
  components/tree/TreeNodeSwitcher.razor
  components/tree/TreeNodeSwitcher.razor.cs
  components/tree/TreeNodeTitle.razor
  components/tree/TreeNodeTitle.razor.cs
  site/AntDesign.Docs.Build.CLI/Command/GenerateDemoJsonCommand.cs
  site/AntDesign.Docs/Demos/Components/Tree/demo/Basic.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/BasicControlled.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/BigData.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Bind.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/CustomizedIcon.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Directory.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Draggable.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Dynamic.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Event.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Line.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Modify.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/Modify.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Property.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Search_.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/SwitcherIcon.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Template.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/VirtualScroll.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/basic-controlled.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/basic.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/basicControlled.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/big-data.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/bind.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/customized-icon.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/directory.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/draggable.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/dynamic.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/event.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/line.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/property.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/search.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/searchdemo.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/switcher-icon.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/template.md
  site/AntDesign.Docs/Demos/Components/Tree/demo/virtual-scroll.md
  site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md
Labels: PR: unreviewed

#1701 Modal and Drawer render reducing and update document and demo
  components/core/Feedback/FeedbackComponent.cs
  components/core/Feedback/IFeedbackRef.cs
  components/core/Feedback/IOkCancelRef.cs
  components/drawer/DrawerContainer.razor.cs
  components/modal/config/IModalTemplate.cs
  components/modal/confirmDialog/ComfirmContainer.razor.cs
  components/modal/confirmDialog/ConfirmRef.cs
  components/modal/modalDialog/ModalContainer.razor.cs
  components/modal/modalDialog/ModalRef.cs
  site/AntDesign.Docs/Demos/Components/Drawer/DrawerTemplateDemo.razor
  site/AntDesign.Docs/Demos/Components/Modal/ConfirmTemplateDemo.razor
  site/AntDesign.Docs/Demos/Components/Modal/demo/Modal_service_for_confirm.razor
  site/AntDesign.Docs/Demos/Components/Modal/demo/Modal_service_for_modal.razor
  site/AntDesign.Docs/Demos/Components/Modal/demo/modal_service_for_confirm.md
  site/AntDesign.Docs/Demos/Components/Modal/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Modal/doc/index.zh-CN.md
Labels: PR: unreviewed

#1729 chore: refactor the build process
  AntDesign.sln
  components/AntDesign.csproj
  site/AntDesign.Docs.Build.CLI/AntDesign.Docs.Build.CLI.csproj
  site/AntDesign.Docs.Build/AntDesign.Docs.Build.csproj
  site/AntDesign.Docs/AntDesign.Docs.csproj
Labels: PR: unreviewed

#1727 fix: click dialog cause the mask click event triggered
  components/modal/core/Dialog.razor
  components/modal/core/Dialog.razor.cs
Labels: PR: partially-approved

#1730 changelog 0.8.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#1742 fix: wrong setter in ModalOptions.ConfirmLoading
  components/modal/config/ModalOptions.cs
Labels: PR: reviewed-approved

#1738 fix(module: form): DisplayName for FormItem will be not default to property name
  components/core/Reflection/PropertyReflector.cs
  site/AntDesign.Docs/Demos/Components/Form/demo/Basic.razor
Labels: PR: unreviewed

#1745 fix(module: table): edit row demo can't recovery the editing on cancel
  site/AntDesign.Docs/Demos/Components/Table/demo/EditRow.razor
Labels: PR: unreviewed

#1743 fix(module: select): can not set initial value for non-datasource approach
  components/select/Select.razor.cs
Labels: PR: unreviewed

#1755 docs: update recommend
  docs/assets/news/reuse-tabs-demo.gif
  site/AntDesign.Docs/wwwroot/data/recommend.en-US.json
  site/AntDesign.Docs/wwwroot/data/recommend.zh-CN.json
  tests/AntDesign.Tests/DatePicker/DatePickerKeyboardInputTests.razor
Labels: PR: unreviewed

#1754 refactor(module:table): remove the breaking change for pagination mode
  components/table/Table.razor.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/ajax.md
Labels: PR: unreviewed

#1760 Fix network error when requesting contributor list in local development environment
  site/AntDesign.Docs/Demos/Components/Tree/demo/Dynamic.razor
  site/AntDesign.Docs/Shared/ContributorsList.razor.cs
Labels: PR: reviewed-approved

#1766 fix(module:select): duplicated tags
  components/select/Select.razor.cs
  components/select/SelectOption.razor.cs
  components/select/internal/SelectContent.razor
  components/select/internal/SelectContent.razor.cs
  tests/AntDesign.Tests/Select/Form/Select.MultipleTests.razor
  tests/AntDesign.Tests/Select/Select.Tags.Tests.razor
Labels: PR: reviewed-approved

#1771 fix: unexpected behavior of Drawer(#1749)
  components/core/ComponentStatus.cs
  components/drawer/Drawer.razor.cs
  components/drawer/DrawerContainer.razor
  components/drawer/DrawerContainer.razor.cs
  components/drawer/DrawerService.cs
  components/drawer/config/DrawerOptions.cs
Labels: PR: reviewed-approved

#1759 feat(module: select): add EnumSelect for select componet with enum
  components/core/Helpers/EnumHelper.cs
  components/select/EnumSelect.cs
  components/select/Select.razor.cs
  site/AntDesign.Docs/Demos/Components/Select/demo/EnumSelectDemo.razor
  site/AntDesign.Docs/Demos/Components/Select/demo/enum-select.md
  tests/AntDesign.Tests/Select/Renders/Select.RenderTests.razor
Labels: PR: unreviewed

#1774 feat(module: button): color
  components/button/Button.razor.cs
  components/core/Color.cs
  components/core/Helpers/ColorHelper.cs
  tests/AntDesign.Tests/button/ButtonTests.cs
  tests/AntDesign.Tests/button/ButtonTests.razor
Labels: PR: unreviewed

#1756 feat(module:table): add guid built-in filter
  components/table/Column.razor
  components/table/FilterExpression/FilterExpressionResolver.cs
  components/table/FilterExpression/GuidFilterExpression.cs
  site/AntDesign.Docs/Demos/Components/Table/demo/Filter.razor
  site/AntDesign.Docs/Demos/Components/Table/demo/filter.md
Labels: PR: reviewed-approved

#1778 Add Change logs for 0.9.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#1777 refactor(module:table): use enum select for table filter
  components/core/Helpers/EnumHelper.cs
  components/select/EnumSelect.cs
  components/table/Column.razor
Labels: PR: reviewed-approved

#1781 fix(module:tree) Fix parent checkbox state calculation (ant-design-blazor#1770)
  components/tree/TreeNode.razor.cs
Labels: PR: reviewed-approved

#1782 chore: sync ant-design v4.16.9
  components/badge/style/index.less
  components/cascader/style/index.less
  components/collapse/style/index.less
  components/date-picker/style/index.less
  components/date-picker/style/panel.less
  components/descriptions/style/index.less
  components/dropdown/style/index.less
  components/form/style/index.less
  components/form/style/mixin.less
  components/input-number/style/index.less
  components/input/style/affix.less
  components/input/style/allow-clear.less
  components/input/style/index.less
  components/input/style/mixin.less
  components/menu/style/dark.less
  components/menu/style/index.less
  components/menu/style/light.less
  components/message/style/index.less
  components/pagination/style/index.less
  components/popover/style/index.less
  components/progress/style/index.less
  components/radio/style/index.less
  components/rate/style/index.less
  components/select/style/index.less
  components/style/core/base.less
  components/style/mixins/modal-mask.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/style/bordered.less
  components/table/style/index.less
  components/tabs/style/index.less
  components/tabs/style/rtl.less
  components/tooltip/style/index.less
  components/typography/style/index.less
Labels: PR: unreviewed

#1785 fix(module: select): remove ValueName null check for non-datasource approach
  components/select/Select.razor.cs
Labels: PR: reviewed-approved

#1786 fix(module: select): fix null value
  components/select/Select.razor.cs
Labels: PR: unreviewed

#1776 fix(module:select) MaxTagCount behaves properly for non-responsive scenarios
  components/select/Select.razor
  components/select/Select.razor.cs
  components/select/SelectOption.razor.cs
  components/select/internal/SelectContent.razor
  components/select/internal/SelectContent.razor.cs
  site/AntDesign.Docs/Demos/Components/Select/demo/MaxTagChange.razor
  site/AntDesign.Docs/Demos/Components/Select/demo/enum-select.md
  site/AntDesign.Docs/Demos/Components/Select/demo/maxTagChange.md
  site/AntDesign.Docs/Demos/Components/Select/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Select/doc/index.zh-CN.md
  tests/AntDesign.Tests/Select/Select.Tags.Tests.razor
Labels: PR: unreviewed

#1791 fix(module:interop): reorganization into classes and typescript tests
  .github/workflows/pull-request.yml
  .gitignore
  AntDesign.sln
  components/core/Extensions/JSRuntimeExtensions.cs
  components/core/JsInterop/JSInteropConstants.cs
  components/core/JsInterop/ObservableApi/observableApi.ts
  components/core/JsInterop/ObservableApi/resizeObserver.ts
  components/core/JsInterop/interop.ts
  components/core/JsInterop/modules/Caret.ts
  components/core/JsInterop/modules/components/backtopHelper.ts
  components/core/JsInterop/modules/components/export.ts
  components/core/JsInterop/modules/components/iconHelper.ts
  components/core/JsInterop/modules/components/inputHelper.ts
  components/core/JsInterop/modules/components/mentionsHelper.ts
  components/core/JsInterop/modules/components/modalHelper.ts
  components/core/JsInterop/modules/components/overlayHelper.ts
  components/core/JsInterop/modules/components/tableHelper.ts
  components/core/JsInterop/modules/components/uploadHelper.ts
  components/core/JsInterop/modules/dom/dragHelper.ts
  components/core/JsInterop/modules/dom/eventHelper.ts
  components/core/JsInterop/modules/dom/exports.ts
  components/core/JsInterop/modules/dom/infoHelper.ts
  components/core/JsInterop/modules/dom/manipulationHelper.ts
  components/core/JsInterop/modules/dom/types.ts
  components/core/JsInterop/modules/enums.ts
  components/core/JsInterop/modules/stateProvider.ts
  components/core/JsInterop/modules/styleHelper.ts
  components/gulpfile.js
  components/select/Select.razor.cs
  package.json
  tests/AntDesign.TestKit/AntDesign.TestKit.csproj
  tests/AntDesign.Tests.Js/AntDesign.Tests.Js.csproj
  tests/AntDesign.Tests.Js/Program.cs
  tests/AntDesign.Tests.Js/package.json
  tests/AntDesign.Tests.Js/tests/domInit.ts
  tests/AntDesign.Tests.Js/tests/mochaConfig.js
  tests/AntDesign.Tests.Js/tests/modules/dom/infoHelper.test.ts
  tests/AntDesign.Tests.Js/tests/modules/stateProvider.test.ts
  tests/AntDesign.Tests.Js/tsconfig.json
  tests/AntDesign.Tests/AntDesign.Tests.csproj
  tests/AntDesign.Tests/tabs/TabsTests.razor
Labels: PR: unreviewed

#1794 fix(module: tree): one more fix to parent checkbox state calculation
  components/tree/TreeNode.razor.cs
Labels: PR: reviewed-approved

#1795 fix: error when confirm TaskCompletionSource SetResult repeat
  components/modal/confirmDialog/Confirm.razor.cs
Labels: PR: unreviewed

#1732 fix(module: table): fix cascading tables
  components/table/Column.razor
Labels: PR: unreviewed

#1792 refactor(module:tree): rename Checked/Dechecked methods to Check/Uncheck
  components/tree/Tree.razor.cs
  site/AntDesign.Docs/Demos/Components/Tree/demo/BasicControlled.razor
Labels: PR: reviewed-approved

#1796 feat(module: tree): bring SearchExpression back
  components/tree/Tree.razor.cs
  components/tree/TreeNodeTitle.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/Search_.razor
  site/AntDesign.Docs/Demos/Components/Tree/demo/search.md
  site/AntDesign.Docs/Demos/Components/Tree/doc/index.en-US.md
  site/AntDesign.Docs/Demos/Components/Tree/doc/index.zh-CN.md
Labels: PR: unreviewed

#1788 fix(module:rangePicker): ShowTime issues addressed
  components/date-picker/RangePicker.razor
  components/date-picker/RangePicker.razor.cs
  components/date-picker/internal/DatePickerBase.cs
  components/date-picker/internal/DatePickerDatePanel.razor
  components/date-picker/internal/DatePickerDatetimePanel.razor
  components/date-picker/internal/DatePickerDatetimePanel.razor.cs
  components/date-picker/internal/DatePickerDecadePanel.razor
  components/date-picker/internal/DatePickerMonthPanel.razor
  components/date-picker/internal/DatePickerPanelBase.cs
  components/date-picker/internal/DatePickerPanelChooser.razor
  components/date-picker/internal/DatePickerQuarterPanel.razor
  components/date-picker/internal/DatePickerYearPanel.razor
Labels: PR: unreviewed

#1797 fix(module:overlay): fix overlay position when container element has border
  components/core/Component/Overlay/Overlay.razor.cs
Labels: PR: reviewed-approved
